/**
 * Harness v1 public entry point.
 *
 * This subpath is introduced separately from the runtime implementation so the
 * migration stack can land reviewable foundations before the Harness + Session
 * behavior is extracted from the fork.
 */

export { Harness } from './harness';
export { Session } from './session';
export {
  EventEmitter,
  assertCustomEventType,
  assertJsonSerializable,
  sessionCreatedPayload,
  suspensionRequiredFor,
} from './events';

export type {
  HarnessMessage,
  HarnessMessageContent,
  HarnessMode,
  HarnessThread,
  ToolCategory,
  ToolsetInput,
  Workspace,
  WorkspaceConfig,
} from './shared';
export type {
  HarnessConfig,
  HarnessConfigCommon,
  HarnessObservationalMemoryConfig,
  HarnessStorageLike,
  HarnessWorkspaceConfig,
  WorkspaceProvider,
  WorkspaceProviderContext,
} from './config';
export type { HarnessRequestContext, RegisterPlanApprovalParams, RegisterQuestionParams, SetStateFn } from './context';
export type {
  AgentResult,
  AgentStream,
  AttachmentDeleteOptions,
  AttachmentRef,
  AttachmentUploadOptions,
  EffectiveHarnessMode,
  GoalJudgeDecision,
  GoalOptions,
  GoalState,
  HarnessDisplayStateSnapshotV1,
  HarnessLease,
  HarnessRunOperationalState,
  HarnessSkill,
  ListMessagesOptions,
  ListPage,
  MessageOptions,
  MessageOptionsDefault,
  MessageOptionsStream,
  MessageOptionsStructured,
  MessageOverrides,
  ModelAuthStatus,
  ModelInfo,
  PendingApproval,
  PendingBase,
  PendingPlanApproval,
  PendingQuestion,
  PendingReceipt,
  PendingResume,
  PendingToolSuspension,
  PermissionPolicy,
  PermissionRules,
  PersistedAttachment,
  QueueOptions,
  QueueOverrides,
  QueuedItem,
  RawAgentExecutionOptions,
  SessionGrants,
  SessionInjectSystemReminderOptions,
  SessionInjectSystemReminderResult,
  SessionLifecycleState,
  SessionListOptions,
  SessionLoadByIdOptions,
  SessionResolveById,
  SessionResolveByIdScoped,
  SessionResolveByResource,
  SessionResolveByThread,
  SessionRecord,
  SessionResolveOptions,
  SessionSignalOptions,
  SessionSignalResult,
  ShutdownOptions,
  SubagentDefinition,
  ThreadCloneOptions,
  ThreadCreateOptions,
  ThreadDeleteOptions,
  ThreadGetOptions,
  ThreadGetSettingOptions,
  ThreadGetSettingsOptions,
  ThreadListOptions,
  ThreadListResult,
  ThreadRecord,
  ThreadRenameOptions,
  ThreadSelectOrCreateOptions,
  ThreadSetSettingsOptions,
  UseSkillOptions,
  WorkspaceSessionBinding,
} from './types';
export type {
  AgentEndEvent,
  AgentStartEvent,
  CustomEvent,
  EmitInput,
  EmitterScope,
  GoalClearedEvent,
  GoalDoneEvent,
  GoalJudgedEvent,
  GoalPausedEvent,
  GoalResumedEvent,
  GoalSetEvent,
  HarnessEvent,
  HarnessEventBase,
  HarnessEventListener,
  HarnessEventUnsubscribe,
  MessageEndEvent,
  MessageStartEvent,
  MessageUpdateEvent,
  ModeChangedEvent,
  ModelChangedEvent,
  ModelOverrideSetEvent,
  PermissionGrantedEvent,
  PermissionPolicyChangedEvent,
  PermissionRevokedEvent,
  QueueItemReplayedEvent,
  QueueItemStartedEvent,
  SessionClosedEvent,
  SessionCreatedEvent,
  SessionEvictedEvent,
  ShellOutputEvent,
  StateChangedEvent,
  SubagentEndEvent,
  SubagentStartEvent,
  SubagentTextDeltaEvent,
  SubagentToolEndEvent,
  SubagentToolStartEvent,
  SuspensionRequiredEvent,
  SuspensionResolvedEvent,
  TaskUpdatedEvent,
  ThreadClonedEvent,
  ThreadCreatedEvent,
  ThreadDeletedEvent,
  ThreadRenamedEvent,
  ThreadSettingsChangedEvent,
  ToolEndEvent,
  ToolInputDeltaEvent,
  ToolInputEndEvent,
  ToolInputStartEvent,
  ToolStartEvent,
  ToolUpdateEvent,
  WorkspaceErrorEvent,
  WorkspaceStatusChangedEvent,
} from './events';
export {
  HarnessConfigError,
  HarnessEventSerializationError,
  HarnessModelNotFoundError,
  HarnessOverrideConflictError,
  HarnessQueueFullError,
  HarnessSessionClosedError,
  HarnessSessionLockedError,
  HarnessSessionNotFoundError,
  HarnessSkillArgsValidationError,
  HarnessSkillNotFoundError,
  HarnessStorageError,
  HarnessSubagentDepthExceededError,
  HarnessThreadNotFoundError,
  HarnessValidationError,
  HarnessWorkspaceInUseError,
  HarnessWorkspaceLostError,
  HarnessWorkspaceProviderMismatchError,
  HarnessWorkspaceProvisioningError,
} from './errors';
export type { EventSerializationReason } from './errors';
