/**
 * Harness v1 — public entry point.
 *
 * Exported as `@mastra/core/harness/v1`. See HARNESS_V1_SPEC.md.
 *
 * The legacy Harness lives at `@mastra/core/harness` and remains the
 * default through v1.0. See §11 for the migration story.
 */

export { Harness } from './harness';
export { Session } from './session';
export type { SessionLifecycleState, SessionDisplayState } from './session';

export type {
  AgentEndEvent,
  AgentStartEvent,
  CustomEvent,
  CustomEvent as HarnessCustomEvent,
  EmitInput,
  EmitterScope,
  GoalClearedEvent,
  GoalDoneEvent,
  GoalJudgedEvent,
  GoalPausedEvent,
  GoalResumedEvent,
  GoalSetEvent,
  HarnessEvent,
  HarnessEventBase,
  HarnessEventListener,
  HarnessEventUnsubscribe,
  MessageEndEvent,
  MessageStartEvent,
  MessageUpdateEvent,
  ModeChangedEvent,
  ModelChangedEvent,
  ModelOverrideSetEvent,
  PermissionGrantedEvent,
  PermissionPolicyChangedEvent,
  PermissionRevokedEvent,
  QueueItemReplayedEvent,
  QueueItemStartedEvent,
  SessionClosedEvent,
  SessionClosingEvent,
  SessionCreatedEvent,
  SessionEvictedEvent,
  StateChangedEvent,
  SubagentEndEvent,
  SubagentStartEvent,
  SubagentTextDeltaEvent,
  SubagentToolEndEvent,
  SubagentToolStartEvent,
  SuspensionRequiredEvent,
  SuspensionResolvedEvent,
  ShellOutputEvent,
  TaskUpdatedEvent,
  ThreadClonedEvent,
  ThreadCreatedEvent,
  ThreadDeletedEvent,
  ThreadRenamedEvent,
  ThreadSettingsChangedEvent,
  ToolEndEvent,
  ToolInputDeltaEvent,
  ToolInputEndEvent,
  ToolInputStartEvent,
  ToolStartEvent,
  ToolUpdateEvent,
  WorkspaceErrorEvent,
  WorkspaceStatusChangedEvent,
} from './events';

export {
  EventEmitter,
  HARNESS_EVENT_ID_PREFIX,
  assertCustomEventType,
  assertJsonSerializable,
  formatHarnessEventId,
  parseHarnessEventId,
  sessionCreatedPayload,
  snapshotHarnessEventForJson,
  suspensionRequiredFor,
} from './events';

export {
  HarnessAttachmentInUseError,
  HarnessAttachmentUnavailableError,
  HarnessConfigError,
  HarnessAdmissionConflictError,
  HarnessEventSerializationError,
  HarnessInboxItemNotFoundError,
  HarnessInboxResponseConflictError,
  HarnessModelNotFoundError,
  HarnessOverrideConflictError,
  HarnessQueueFullError,
  HarnessRuntimeDependencyDriftError,
  HarnessSessionClosedError,
  HarnessSessionClosingError,
  HarnessSessionDeleteBlockedError,
  HarnessSessionDeletedError,
  HarnessSessionLockedError,
  HarnessSessionNotFoundError,
  HarnessSkillNotFoundError,
  HarnessStateConflictError,
  HarnessSkillArgsValidationError,
  HarnessStorageError,
  HarnessSubagentDepthExceededError,
  HarnessThreadNotFoundError,
  HarnessValidationError,
  HarnessWorkspaceInUseError,
  HarnessWorkspaceLostError,
  HarnessWorkspaceProviderMismatchError,
  HarnessWorkspaceProvisioningError,
} from './errors';
export type { EventSerializationReason } from './errors';

export { nonDurableProvider } from './workspace-provider';
export type { WorkspaceOwnershipKind, WorkspaceProvider, WorkspaceProviderContext } from './workspace-provider';

/**
 * `HarnessMessage` and `HarnessMessageContent` are stable cross-version
 * interfaces (spec §11.1). They are re-exported from v1 and back the same
 * underlying definitions used by the legacy `Harness`, so renderers can
 * import from either entry point and consume the same shape.
 */
export type { HarnessMessage, HarnessMessageContent } from '../types';

/**
 * Goal-loop primitive types (§4.7). `GoalState` lives in `SessionRecord.goal`
 * and is returned by `Session.getGoal()` / `setGoal(...)`. `GoalJudgeDecision`
 * captures one judge verdict.
 */
export type { GoalJudgeDecision, GoalState } from '../../storage/domains/harness';

export type {
  AgentResult,
  AgentStream,
  AttachmentDeleteOptions,
  AttachmentRef,
  AttachmentUploadOptions,
  AvailableModel,
  ElementAttachmentUploadOptions,
  CustomAvailableModel,
  CustomModelCatalogProvider,
  EffectiveHarnessMode,
  FileAttachmentUploadOptions,
  GoalOptions,
  HarnessChannelAdapter,
  HarnessChannelBinding,
  HarnessChannelConfig,
  HarnessChannelDiagnostics,
  HarnessChannelDiagnosticsOptions,
  HarnessChannelDeliveryContext,
  HarnessChannelDiagnosticError,
  HarnessChannelDiagnosticLease,
  HarnessChannelActionReceiptDiagnostic,
  HarnessChannelActionTokenDiagnostic,
  HarnessChannelInboxDiagnostic,
  HarnessChannelOutboxDiagnostic,
  ChannelOutboxDispatchOptions,
  ChannelOutboxDispatchResult,
  HarnessChannelRouteContext,
  HarnessChannelTransportRequest,
  HarnessConfig,
  HarnessConfigCommon,
  HarnessDisplayStateSnapshotV1,
  HarnessLease,
  HarnessMode,
  HarnessRunOperationalState,
  HarnessSkill,
  InboxResponseOptions,
  InboxResponseResult,
  PrimitiveAttachmentUploadOptions,
  UseSkillOptions,
  HarnessWorkspaceConfig,
  ListPage,
  ListMessagesOptions,
  MessageOptions,
  MessageOptionsDefault,
  MessageOptionsStream,
  MessageOptionsStructured,
  MessageAdmissionResult,
  MessageOverrides,
  ModelAuthChecker,
  ModelAuthStatus,
  ModelInfo,
  ModelUseCountProvider,
  ModelUseCountTracker,
  PendingApproval,
  PendingBase,
  PendingPlanApproval,
  PendingQuestion,
  PendingReceipt,
  PendingToolSuspension,
  PermissionPolicy,
  QueueOptions,
  QueueAdmissionResult,
  QueueOverrides,
  RawAgentExecutionOptions,
  HarnessRequestContext,
  RegisterPlanApprovalParams,
  RegisterQuestionParams,
  SessionInjectSystemReminderOptions,
  SessionInjectSystemReminderResult,
  SessionDeleteOptions,
  SessionListOptions,
  SessionLoadByIdOptions,
  SessionRecord,
  SessionResolveByResource,
  SessionResolveById,
  SessionResolveByIdScoped,
  SessionResolveByThread,
  SessionResolveOptions,
  SessionSignalOptions,
  SessionSignalResult,
  SetStateFn,
  SetStateOptions,
  ShutdownOptions,
  SubagentDefinition,
  ThreadCloneOptions,
  ThreadCreateOptions,
  ThreadDeleteOptions,
  ThreadGetOptions,
  ThreadGetSettingOptions,
  ThreadGetSettingsOptions,
  ThreadListOptions,
  ThreadListResult,
  ThreadRecord,
  ThreadRenameOptions,
  ThreadSelectOrCreateOptions,
  ThreadSetSettingsOptions,
  ToolCategory,
  WorkspaceSessionBinding,
} from './types';

export type {
  AttachmentObjectPointer,
  AttachmentRendererDescriptor,
  ChannelDeliverySemantics,
  ChannelOutboxEnqueueOptions,
  ChannelOutboxItem,
  ChannelOutboxKind,
  ChannelOutboxOperationKind,
  ChannelOutboxSource,
  ChannelOutboxTarget,
  ChannelProviderDeliveryReceipt,
  HarnessAttachmentKind,
  HarnessPrimitiveType,
  InboxResponseReceipt,
  JsonValue,
  PendingResume,
  PermissionRules,
  PersistedAttachment,
  QueuedItem,
  SessionGrants,
} from '../../storage/domains/harness';
