/** Immutable compatibility vectors generated by the pre-migration Node crypto implementation. */
export const WEB_CRYPTO_COMPAT_VECTORS = {
  generatedBy: 'pre-migration Node crypto at base 83bbee21ddf75504006f6b4a7b589438656aaf9a',
  digest: {
    emptySha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    unicodeSha256: 'dd75b31d7eae77273742d1c695a3be3d3cbf9457fe3cebd1ebd9649761f69f8a',
    binarySha256: '801e856b1349a0dca69f3df3f8ae7076df76c863de2b5c6356b9985f0185a6de',
    multipartSha256: '31c2ef902e3dd2f20fb5ea907f401295b36d33db4bae80bfbc1994ede465a2e4',
  },
  hmac: {
    slackSigningSecret: 'test-signing-secret',
    timestamp: '1700000000',
    body: 'token=abc&team_id=T123',
    signature: 'v0=978c45477d8e6c231ca34d973a4bd9473eace6fde9d74e621da7557edc0332bf',
  },
  pkce: {
    verifier: 'dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk',
    challenge: 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM',
  },
  oauthState: {
    secret: 'state-secret-for-compatibility',
    body: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJvcmdJZCI6Im9yZy0xMjMiLCJ1c2VySWQiOiJ1c2VyLTQ1NiIsIm5vbmNlIjoiMDAxMTIyMzM0NDU1NjY3NyIsImlzc3VlZEF0IjoxNzAwMDAwMDAwMDAwfQ',
    signature: 'QzDMlyV099-kPt736Egq8ofEJv4GfJQ_EaCUY7K_LVs',
  },
  hkdfAndAesGcm: {
    slack: {
      passphrase: 'test-encryption-key-32-chars-ok!',
      salt: 'ABEiM0RVZneImaq7zN3u/w==',
      iv: 'ECEyQ1RldoeYqbrL',
      plaintext: 'Slack compatibility ✅',
      derivedKey: 'r/TKhxe5XjAAYnWWL1cPQXeFf5ENyKEsNzQU9Xwf7js=',
      authTag: 'iq6t26hOeylqa1GMRTUYHg==',
      ciphertext: 'zXqY/MADEefhXFyfrtFj9vMC8mDu2N0=',
      envelope:
        'aes-256-gcm-hkdf:ABEiM0RVZneImaq7zN3u/w==:ECEyQ1RldoeYqbrL:iq6t26hOeylqa1GMRTUYHg==:zXqY/MADEefhXFyfrtFj9vMC8mDu2N0=',
    },
    telegram: {
      passphrase: 'telegram-test-passphrase',
      salt: '8ODQwLCgkIBwYFBAMCAQAA==',
      iv: 'ABEiM0RVZneImaq7',
      plaintext: 'Telegram compatibility ✅',
      derivedKey: 'vOXhNmXa+EsCy4L69LR/NPV0HDSZjBd/Rk56Y6No8PE=',
      authTag: 'aPd7Px1cLWU/nBqHMYDMPA==',
      ciphertext: 'TguKH0uB9gBANA78/tLaZGbNhZBBOzjmoKU=',
      envelope:
        'aes-256-gcm-hkdf:8ODQwLCgkIBwYFBAMCAQAA==:ABEiM0RVZneImaq7:aPd7Px1cLWU/nBqHMYDMPA==:TguKH0uB9gBANA78/tLaZGbNhZBBOzjmoKU=',
    },
    factory: {
      keyId: 'primary',
      key: 'MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY',
      iv: 'ABEiM0RVZneImaq7',
      plaintext: '{"apiKey":"value","nested":{"enabled":true}}',
      ciphertext: 'Jble7gjdWJ6qf5VOTwijDPRZdGflu-mxUPgXJg6GFYP2qNaw0pPQNEGqMFI',
      tag: 'D2m1mmUMJDcrPg7qQ-PynA',
    },
  },
  asymmetric: {
    signingInput: 'agent-card-signing-input',
    rsa: {
      algorithm: 'RS256',
      privateKeyPkcs8Pem:
        '-----BEGIN PRIVATE KEY-----\nMIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQCQy/ZzuL6kfjZL\nTcbpXgxL0Ke34hG9Nz71x1BCXfusjk3lvNo0AaxJoH93BX7AEA8DQ+qYtjnUGz/d\no+OkN9JQWg8//XNnBRS9ARqSqhzTurXS2GHxzT/5Km/fKzcrkZOLUP+oIhaNKqxI\nxcskjq0T3EcG4ZMMj4qF6/7ghHObDOYtVRXPmVB7WY4o6q9InW1zy9Q5YFWgXTDz\n1+r7AyMZ3Ge6OBNFdIHvElqPqQ/NVVSkXRn3deHW7aSmTHo9IfRhz1dq4pKs84Zh\nIzZ5oZ7LJzyejmk1FFJXYiFrP7BTJYNnl9WIyMlMHXoe2UVlxDYH4TaPC3lPz4A3\novTcspztAgMBAAECgf9+u4NgLxRKMGUzViw9LT5yLvu2w5u/J8JFzXAJvGZQoJQ6\nObTd9bqjcTD1rU2vQht2k4cT6OHEZcnenk7m1PLi8BgHqXW0kNDEkL6qZE/eyeLv\na8PrCkZeIYoGn9NxX6zqpV6bnaWGjdP/rjzeo5765czN1M9X7pYlDlKwmS1odeiU\n3znvu7ibDl9l9V/Eqbg3w9v/NAVIufu9S9CFcU+WGrtsX4oEFzNNDJSMpUNtuYli\nDtuq0JCabunBcyp5BefbeGGF2cLl/2ANc9WnzI7uW/FPsYwJT1QbL4UBb7RnPNxY\nuD8KYOgkL6peqbGwRADAHRLAy9m+YJ91pKemWA8CgYEAy0HqFdtj0JkqLRwcR9HY\nrX49BAEHbieGScEc5tx/9jxLbeb8jI19WWyHkHbHqaXQcwssSEcFMvGkLVZpTEFM\nrbzTmLxD2ttCiizxfdKbHtYqOfYBx0zbBm4uuHD2GfaIv2zcLUr/jXh1y4wW2Csj\nnKFQkIXyqmU+42AIsktdhR8CgYEAtl6W7EoV/2ND9LjWgKDTqAk5XSDhdI1utlfn\n//dB+2hEToIc3gEo9MOjOT9gCwbR+GIb0HvxklQ06JdQc2qEW5uYY0HfnC0RQEFL\nnnRwG2eUCc5PPWme4N8CG2Qa7KVbTOSEV7OrJ4JArDcmoT3lrz7DNaG+9kmgDUiK\ngGYGMHMCgYBWZ8rvR7iC8NmxG4YaMeb+ue+OSDG0bjD0IZf7vDjZoIAgVFWAGpXy\n8eQfUZ9HSyn1/gXxI9/d7ENy0o0o0YmbQe5hu4bM/vCmdLykVGeFEF4bDa1r4Aws\nC6Lo3XyBRQCU/94JkxxYM6E/ymnbs1sMNrdc+NRUA35cgnKv+MHk2QKBgGc5XQW7\n3X2jyyguo0NFROg86Fo9LT/SehL96NRqOM+7scYaQYqrb2ozfiT+KTe0kY6cwY+d\nSBwCS7xHQYNCjE5p4LR16cK1g6kyDEJRN89bLmDqhNGHAiXYNJIadF70LZx1UC9w\nA/Wl9UNFKDlmFqa9yLKHrdYr0EsUf0iz9tbfAoGAJmDjjQMOZGCVGOJiSc5gvRW5\nAy5qXmkmzHo63db7Cg25sPGSMdzKd4c70IC+BeCxXdRVaz9skRmkns5NtKI5NPoZ\nuhwU7jIAwYJuJeFGlEUwj8sMQW1fMBx5VObEyEVWDYLo42DfhJoUz6BFIibf7SQj\nGkWz5oqB633l3N1ALzg=\n-----END PRIVATE KEY-----\n',
      publicKeySpkiPem:
        '-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkMv2c7i+pH42S03G6V4M\nS9Cnt+IRvTc+9cdQQl37rI5N5bzaNAGsSaB/dwV+wBAPA0PqmLY51Bs/3aPjpDfS\nUFoPP/1zZwUUvQEakqoc07q10thh8c0/+Spv3ys3K5GTi1D/qCIWjSqsSMXLJI6t\nE9xHBuGTDI+Khev+4IRzmwzmLVUVz5lQe1mOKOqvSJ1tc8vUOWBVoF0w89fq+wMj\nGdxnujgTRXSB7xJaj6kPzVVUpF0Z93Xh1u2kpkx6PSH0Yc9XauKSrPOGYSM2eaGe\nyyc8no5pNRRSV2Ihaz+wUyWDZ5fViMjJTB16HtlFZcQ2B+E2jwt5T8+AN6L03LKc\n7QIDAQAB\n-----END PUBLIC KEY-----\n',
      signature:
        'NedkCuXAGc6evIczdGXXbjzer6pLFobLr3R7Gs4CTHC8HKeTWfNRr34QgE0aFc1b2euAAELZhghBaojynV6xoDp0oLHL5NEB8OIv6yBaR6nF3kV5ZGSmT3_43tpDHvdEtSZv6CcRl_JTLWoezy8L287HBNN-JxT5aaRi4uKweOoPUMLN6lR3RHido9PW_0gKyTWlPLtg-ps81Jao4ny_K2yYbeXCYvjZSSbmcf7pWccSrTCsUIfQsA9cE-6P2YOoQgxZ_pIOzLVBDZKqhh4PCIVRfniQ3MzcqoCsMemORhjf3AxlT57KFPxha4QqMZgXOGlMOuwXAT4Ee0z5My2tNw',
      privateKeyJwk: {
        kty: 'RSA',
        n: 'kMv2c7i-pH42S03G6V4MS9Cnt-IRvTc-9cdQQl37rI5N5bzaNAGsSaB_dwV-wBAPA0PqmLY51Bs_3aPjpDfSUFoPP_1zZwUUvQEakqoc07q10thh8c0_-Spv3ys3K5GTi1D_qCIWjSqsSMXLJI6tE9xHBuGTDI-Khev-4IRzmwzmLVUVz5lQe1mOKOqvSJ1tc8vUOWBVoF0w89fq-wMjGdxnujgTRXSB7xJaj6kPzVVUpF0Z93Xh1u2kpkx6PSH0Yc9XauKSrPOGYSM2eaGeyyc8no5pNRRSV2Ihaz-wUyWDZ5fViMjJTB16HtlFZcQ2B-E2jwt5T8-AN6L03LKc7Q',
        e: 'AQAB',
        d: 'fruDYC8USjBlM1YsPS0-ci77tsObvyfCRc1wCbxmUKCUOjm03fW6o3Ew9a1Nr0IbdpOHE-jhxGXJ3p5O5tTy4vAYB6l1tJDQxJC-qmRP3sni72vD6wpGXiGKBp_TcV-s6qVem52lho3T_6483qOe-uXMzdTPV-6WJQ5SsJktaHXolN8577u4mw5fZfVfxKm4N8Pb_zQFSLn7vUvQhXFPlhq7bF-KBBczTQyUjKVDbbmJYg7bqtCQmm7pwXMqeQXn23hhhdnC5f9gDXPVp8yO7lvxT7GMCU9UGy-FAW-0ZzzcWLg_CmDoJC-qXqmxsEQAwB0SwMvZvmCfdaSnplgP',
        p: 'y0HqFdtj0JkqLRwcR9HYrX49BAEHbieGScEc5tx_9jxLbeb8jI19WWyHkHbHqaXQcwssSEcFMvGkLVZpTEFMrbzTmLxD2ttCiizxfdKbHtYqOfYBx0zbBm4uuHD2GfaIv2zcLUr_jXh1y4wW2CsjnKFQkIXyqmU-42AIsktdhR8',
        q: 'tl6W7EoV_2ND9LjWgKDTqAk5XSDhdI1utlfn__dB-2hEToIc3gEo9MOjOT9gCwbR-GIb0HvxklQ06JdQc2qEW5uYY0HfnC0RQEFLnnRwG2eUCc5PPWme4N8CG2Qa7KVbTOSEV7OrJ4JArDcmoT3lrz7DNaG-9kmgDUiKgGYGMHM',
        dp: 'VmfK70e4gvDZsRuGGjHm_rnvjkgxtG4w9CGX-7w42aCAIFRVgBqV8vHkH1GfR0sp9f4F8SPf3exDctKNKNGJm0HuYbuGzP7wpnS8pFRnhRBeGw2ta-AMLAui6N18gUUAlP_eCZMcWDOhP8pp27NbDDa3XPjUVAN-XIJyr_jB5Nk',
        dq: 'ZzldBbvdfaPLKC6jQ0VE6DzoWj0tP9J6Ev3o1Go4z7uxxhpBiqtvajN-JP4pN7SRjpzBj51IHAJLvEdBg0KMTmngtHXpwrWDqTIMQlE3z1suYOqE0YcCJdg0khp0XvQtnHVQL3AD9aX1Q0UoOWYWpr3Isoet1ivQSxR_SLP21t8',
        qi: 'JmDjjQMOZGCVGOJiSc5gvRW5Ay5qXmkmzHo63db7Cg25sPGSMdzKd4c70IC-BeCxXdRVaz9skRmkns5NtKI5NPoZuhwU7jIAwYJuJeFGlEUwj8sMQW1fMBx5VObEyEVWDYLo42DfhJoUz6BFIibf7SQjGkWz5oqB633l3N1ALzg',
      },
      publicKeyJwk: {
        kty: 'RSA',
        n: 'kMv2c7i-pH42S03G6V4MS9Cnt-IRvTc-9cdQQl37rI5N5bzaNAGsSaB_dwV-wBAPA0PqmLY51Bs_3aPjpDfSUFoPP_1zZwUUvQEakqoc07q10thh8c0_-Spv3ys3K5GTi1D_qCIWjSqsSMXLJI6tE9xHBuGTDI-Khev-4IRzmwzmLVUVz5lQe1mOKOqvSJ1tc8vUOWBVoF0w89fq-wMjGdxnujgTRXSB7xJaj6kPzVVUpF0Z93Xh1u2kpkx6PSH0Yc9XauKSrPOGYSM2eaGeyyc8no5pNRRSV2Ihaz-wUyWDZ5fViMjJTB16HtlFZcQ2B-E2jwt5T8-AN6L03LKc7Q',
        e: 'AQAB',
      },
    },
    ecdsa: {
      algorithm: 'ES256',
      privateKeyPkcs8Pem:
        '-----BEGIN PRIVATE KEY-----\nMIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgf8XEXlJrrbqT7b7+\nEa88S5eMQzb0eHyKMsiXPNQVI76hRANCAARuwO9Mzc4qL69gbjQuq11ehjorKk5Q\nE+T1UcE4MxfrXWDRxzc9B2KFCpM47e4Lev7BoBXNjNJZN7bxg5gmjFb9\n-----END PRIVATE KEY-----\n',
      publicKeySpkiPem:
        '-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbsDvTM3OKi+vYG40LqtdXoY6KypO\nUBPk9VHBODMX611g0cc3PQdihQqTOO3uC3r+waAVzYzSWTe28YOYJoxW/Q==\n-----END PUBLIC KEY-----\n',
      signatureFormat: 'ieee-p1363 / JOSE raw R||S',
      signature: 'ovCumiNDB5q-0ZcJlNZPq_Nw_8lHhf_Sk40F6bC8rwqHui3Xys_Ar8ASFbk2tP-QcPypjvHhT4qqYKKkLH0P4Q',
      privateKeyJwk: {
        kty: 'EC',
        x: 'bsDvTM3OKi-vYG40LqtdXoY6KypOUBPk9VHBODMX610',
        y: 'YNHHNz0HYoUKkzjt7gt6_sGgFc2M0lk3tvGDmCaMVv0',
        crv: 'P-256',
        d: 'f8XEXlJrrbqT7b7-Ea88S5eMQzb0eHyKMsiXPNQVI74',
      },
      publicKeyJwk: {
        kty: 'EC',
        x: 'bsDvTM3OKi-vYG40LqtdXoY6KypOUBPk9VHBODMX610',
        y: 'YNHHNz0HYoUKkzjt7gt6_sGgFc2M0lk3tvGDmCaMVv0',
        crv: 'P-256',
      },
    },
  },
} as const;
