/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Login
     * @description Redirect to WorkOS authorization URL. Supports studio (browser), deploy (browser), and cli (token) flows.
     */
    get: operations['getV1AuthLogin'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * OAuth callback
     * @description Handle WorkOS OAuth callback. Creates session (browser) or passes tokens (CLI). Not called directly by clients.
     */
    get: operations['getV1AuthCallback'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current user
     * @description Return the current session user, organization, role, and permissions.
     */
    get: operations['getV1AuthMe'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Refresh session
     * @description Refresh the sealed session cookie using WorkOS refresh token.
     */
    get: operations['getV1AuthRefresh'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/orgs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List organizations
     * @description List organizations the user belongs to. Accepts Bearer token (CLI) or session cookie (browser).
     */
    get: operations['getV1AuthOrgs'];
    put?: never;
    /**
     * Create organization
     * @description Create a new organization and auto-switch the session to it.
     */
    post: operations['postV1AuthOrgs'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/switch-org': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Switch organization
     * @description Switch the current session to a different organization.
     */
    post: operations['postV1AuthSwitchOrg'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Logout
     * @description Clear session cookie and return optional WorkOS logout URL.
     */
    post: operations['postV1AuthLogout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/verify': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Verify CLI token
     * @description Verify a CLI access token (WorkOS JWT) and return user info and organization.
     */
    get: operations['getV1AuthVerify'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/auth/refresh-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh access token
     * @description Exchange a WorkOS refresh token for a new access token (CLI flow).
     */
    post: operations['postV1AuthRefreshToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/org/members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List members
     * @description List all members of the current organization.
     */
    get: operations['getV1OrgMembers'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/org/members/invitations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List invitations
     * @description List all pending invitations for the current organization.
     */
    get: operations['getV1OrgMembersInvitations'];
    put?: never;
    /**
     * Send invitation
     * @description Send an invitation to join the organization. Requires admin role.
     */
    post: operations['postV1OrgMembersInvitations'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/org/members/invitations/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revoke invitation
     * @description Revoke a pending invitation. Requires admin role.
     */
    delete: operations['deleteV1OrgMembersInvitationsById'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/org/members/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove member
     * @description Remove a member from the organization. Requires admin role.
     */
    delete: operations['deleteV1OrgMembersById'];
    options?: never;
    head?: never;
    /**
     * Update member role
     * @description Update the role of a member in the organization. Requires admin role.
     */
    patch: operations['patchV1OrgMembersById'];
    trace?: never;
  };
  '/v1/gateway/projects/{id}/usage/activity': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get usage activity
     * @description Aggregated usage metrics for a project. Supports multiple granularities (1m, 5m, 15m, 1h, daily, weekly, monthly) and optional group-by dimensions (model, provider, source, api_key_id, etc.).
     */
    get: operations['getV1GatewayProjectsByIdUsageActivity'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/gateway/projects/{id}/usage/logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get request logs
     * @description Per-request log entries for a project. Supports filtering by model, provider, source, and API key. Paginated with limit/offset (max 200 per page, default 50).
     */
    get: operations['getV1GatewayProjectsByIdUsageLogs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studio/projects': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List projects
     * @description List all projects for the current organization
     */
    get: operations['getV1StudioProjects'];
    put?: never;
    /**
     * Create project
     * @description Create a new project
     */
    post: operations['postV1StudioProjects'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studio/projects/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get project
     * @description Get project details and all deploys
     */
    get: operations['getV1StudioProjectsById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studio/deploys': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create deploy
     * @description Create a new deployment. When an artifact store is configured, returns a signed upload URL for the client to upload the zip directly. Otherwise accepts the zip body directly (legacy).
     */
    post: operations['postV1StudioDeploys'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studio/deploys/{id}/upload-complete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Confirm artifact upload
     * @description Signal that the client has finished uploading the artifact to the signed URL. Triggers the deploy pipeline.
     */
    post: operations['postV1StudioDeploysByIdUploadComplete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studio/deploys/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get deploy status
     * @description Get the current status of a deployment
     */
    get: operations['getV1StudioDeploysById'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studio/deploys/{id}/logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get deploy logs
     * @description Get combined stdout and stderr logs for a deployment
     */
    get: operations['getV1StudioDeploysByIdLogs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/v1/studio/deploys/{id}/logs/stream': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stream deploy logs
     * @description Stream deployment logs in real-time via Server-Sent Events
     */
    get: operations['getV1StudioDeploysByIdLogsStream'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: never;
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getV1AuthLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to WorkOS authorization URL */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getV1AuthCallback: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redirect to application or CLI callback */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Access denied — user does not belong to the requested organization */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
      /** @description Session creation failed */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  getV1AuthMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current session info */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: {
              id: string;
              email: string;
              firstName: string | null;
              lastName: string | null;
              profilePictureUrl: string | null;
            };
            organizationId: string | null;
            role: string | null;
            permissions: string[];
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  getV1AuthRefresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Session refreshed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            ok: true;
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  getV1AuthOrgs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of organizations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            organizations: {
              id: string;
              name: string;
              role: string | null;
              isCurrent: boolean;
            }[];
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  postV1AuthOrgs: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
        };
      };
    };
    responses: {
      /** @description Organization created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            organization: {
              id: string;
              name: string;
              role: string | null;
              isCurrent: boolean;
            };
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  postV1AuthSwitchOrg: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          organizationId: string;
        };
      };
    };
    responses: {
      /** @description Organization switched */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            ok: true;
            organizationId: string;
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  postV1AuthLogout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logged out */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            ok: true;
            logoutUrl?: string;
          };
        };
      };
    };
  };
  getV1AuthVerify: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Token valid */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            user: {
              id: string;
              email: string;
              firstName: string | null;
              lastName: string | null;
            };
            organizationId: string;
          };
        };
      };
      /** @description Invalid or missing token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
      /** @description Not a member of the organization */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  postV1AuthRefreshToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          refreshToken: string;
        };
      };
    };
    responses: {
      /** @description New tokens */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            accessToken: string;
            refreshToken: string;
          };
        };
      };
      /** @description Refresh failed */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  getV1OrgMembers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of members */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            members: {
              id: string;
              userId: string;
              email: string;
              firstName: string | null;
              lastName: string | null;
              profilePictureUrl: string | null;
              role: string | null;
              status: string;
              createdAt: string;
            }[];
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
      /** @description Forbidden — no organization selected */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  getV1OrgMembersInvitations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of invitations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            invitations: {
              id: string;
              email: string;
              state: string;
              expiresAt: string;
              createdAt: string;
            }[];
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
      /** @description Forbidden — no organization selected */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  postV1OrgMembersInvitations: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** Format: email */
          email: string;
          /** @enum {string} */
          role: 'member' | 'admin';
        };
      };
    };
    responses: {
      /** @description Invitation sent */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            invitation: {
              id: string;
              email: string;
              state: string;
              expiresAt: string;
              createdAt: string;
            };
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
      /** @description Forbidden — admin role required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  deleteV1OrgMembersInvitationsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Invitation revoked */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            ok: true;
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
      /** @description Forbidden — admin role required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  deleteV1OrgMembersById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Member removed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            ok: true;
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
      /** @description Forbidden — admin role required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  patchV1OrgMembersById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          /** @enum {string} */
          role: 'member' | 'admin';
        };
      };
    };
    responses: {
      /** @description Member role updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            member: {
              id: string;
              userId: string;
              email: string;
              firstName: string | null;
              lastName: string | null;
              profilePictureUrl: string | null;
              role: string | null;
              status: string;
              createdAt: string;
            };
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
      /** @description Forbidden — admin role required */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  getV1GatewayProjectsByIdUsageActivity: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Usage activity data */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            project_id: string;
            from: string;
            to: string;
            /** @enum {string} */
            granularity: 'daily' | 'weekly' | 'monthly' | '1m' | '5m' | '15m' | '1h';
            group_by: string[];
            data:
              | {
                  request_count: number;
                  error_count: number;
                  prompt_tokens: number;
                  completion_tokens: number;
                  total_tokens: number;
                  cached_tokens: number;
                  cache_write_tokens: number;
                  uncached_tokens: number;
                  cache_hit_rate: number;
                  cost_usd: number;
                }
              | {
                  request_count: number;
                  error_count: number;
                  prompt_tokens: number;
                  completion_tokens: number;
                  total_tokens: number;
                  cached_tokens: number;
                  cache_write_tokens: number;
                  uncached_tokens: number;
                  cache_hit_rate: number;
                  cost_usd: number;
                  timestamp: string;
                  model?: string;
                  provider?: string;
                  source?: string;
                  source_category?: string;
                  api_key_id?: string | null;
                  api_key_label?: string | null;
                  api_key_prefix?: string | null;
                  endpoint?: string;
                  status_code?: number;
                }[];
          };
        };
      };
      /** @description Invalid query parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1GatewayProjectsByIdUsageLogs: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Request log entries */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            project_id: string;
            from: string;
            to: string;
            logs: {
              request_id: string;
              api_key_id: string | null;
              api_key_label: string | null;
              api_key_prefix: string | null;
              model: string;
              provider: string;
              source: string;
              source_category: string;
              endpoint: string;
              status_code: number;
              prompt_tokens: number;
              completion_tokens: number;
              total_tokens: number;
              cached_tokens: number;
              cache_write_tokens: number;
              cost_usd: number;
              latency_ms: number;
              is_stream: boolean;
              error: string | null;
              generation_id: string | null;
              thread_id: string | null;
              timestamp: string;
            }[];
          };
        };
      };
      /** @description Invalid query parameters */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            type: string;
            title: string;
            status: number;
            detail?: string;
            errors?: {
              field: string;
              message: string;
            }[];
          };
        };
      };
    };
  };
  getV1StudioProjects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of projects */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            projects: {
              id: string;
              name: string;
              organizationId: string;
              latestDeployId: string | null;
              latestDeployStatus: string | null;
              instanceUrl: string | null;
              createdAt: string | null;
              updatedAt: string | null;
            }[];
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  postV1StudioProjects: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': {
          name: string;
        };
      };
    };
    responses: {
      /** @description Created project */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            project: {
              id: string;
              name: string;
              organizationId: string;
              latestDeployId: string | null;
              latestDeployStatus: string | null;
              instanceUrl: string | null;
              createdAt: string | null;
              updatedAt: string | null;
            };
          };
        };
      };
      /** @description Validation error */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  getV1StudioProjectsById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Project with deploys */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            project: {
              id: string;
              name: string;
              organizationId: string;
              latestDeployId: string | null;
              latestDeployStatus: string | null;
              instanceUrl: string | null;
              createdAt: string | null;
              updatedAt: string | null;
            };
            deploys: {
              id: string;
              projectId: string;
              organizationId: string;
              projectName: string;
              /** @enum {string} */
              status: 'starting' | 'running' | 'stopped' | 'failed' | 'unknown';
              instanceUrl: string | null;
              error: string | null;
              createdAt: string | null;
            }[];
          };
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  postV1StudioDeploys: {
    parameters: {
      query?: never;
      header?: {
        'x-project-id'?: string;
        'x-project-name'?: string;
        'x-git-branch'?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deploy queued */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            deploy: {
              id: string;
              /** @constant */
              status: 'queued';
              uploadUrl?: string;
            };
          };
        };
      };
      /** @description Not authenticated */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  postV1StudioDeploysByIdUploadComplete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Upload confirmed, pipeline started */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            /** @constant */
            status: 'ok';
          };
        };
      };
      /** @description Deploy not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  getV1StudioDeploysById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deploy info */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            deploy: {
              id: string;
              projectId: string;
              organizationId: string;
              projectName: string;
              /** @enum {string} */
              status: 'starting' | 'running' | 'stopped' | 'failed' | 'unknown';
              instanceUrl: string | null;
              error: string | null;
              createdAt: string | null;
            };
          };
        };
      };
      /** @description Deploy not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  getV1StudioDeploysByIdLogs: {
    parameters: {
      query?: {
        /** @description Number of recent log lines to return */
        tail?: string;
      };
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deploy logs */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            logs: string;
          };
        };
      };
      /** @description Deploy not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
  getV1StudioDeploysByIdLogsStream: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description SSE stream of log lines */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'text/event-stream': string;
        };
      };
      /** @description Deploy not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            error: string;
          };
        };
      };
    };
  };
}
