WHENEVER SQLERROR EXIT SQL.SQLCODE

ALTER SESSION SET CONTAINER = FREEPDB1;

BEGIN
  EXECUTE IMMEDIATE 'ALTER SYSTEM SET VECTOR_MEMORY_SIZE = 256M SCOPE=MEMORY';
EXCEPTION
  WHEN OTHERS THEN
    NULL;
END;
/
