# Reese Configuration Example
# Copy this to .reese.yaml in your project or ~/.reese/config.yaml globally

# ============================================
# Model Router Configuration
# ============================================
# Specify a model string to enable intelligent model routing based on conversation context
# Any model that Mastra can resolve is supported!
#
# Examples:
#   routerModel: claude-sonnet-4-5                  # Use Claude Sonnet for routing
#   routerModel: claude-haiku-4-5                   # Use Claude Haiku for routing
#   routerModel: lmstudio+arch-router-1.5b.gguf     # Use LM Studio with arch-router
#   routerModel: anthropic/claude-3.5-sonnet        # Use anthropic provider format
#   routerModel: null                               # Disable routing entirely
#
# Defaults to: lmstudio+arch-router-1.5b.gguf (if omitted)
#
# 💡 Recommendations:
#   - For best routing: claude-sonnet-4-5 (costs API calls, very smart)
#   - For fast/cheap routing: claude-haiku-4-5 (costs less, still good)
#   - For free routing: lmstudio+arch-router-1.5b.gguf (requires LM Studio, less sophisticated)
#   - To disable routing: null (always uses default model)
routerModel: claude-haiku-4-5 # Good balance of speed, cost, and accuracy

# ============================================
# Default Model Settings
# ============================================
defaultModel: claude-4-sonnet-20250514
temperature: 0.3
maxTokens: 4000
contextSizeLimit: 100000

# ============================================
# Model Strategy
# ============================================
# How to handle model fallbacks when rate limits are hit
# Options: 'fallback' (try next model in list) or 'round-robin' (cycle through models)
modelStrategy: fallback

# ============================================
# Rate Limiting Configuration
# ============================================
rateLimit:
  maxRetries: 3
  retryDelay: 1000 # milliseconds
  maxRetryDelay: 10000 # milliseconds
  backoffMultiplier: 2
  fallbackModels:
    - claude-4-sonnet-20250514
    - claude-haiku-4-5

# ============================================
# Tavily (Web Search) Configuration
# ============================================
tavily:
  cacheEnabled: true
  cacheTtlMs: 3600000 # 1 hour

