packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  # - "integrations/*"
  # - "examples/*"
  - "!packages/cli/admin"
  - "integration-generator/*"
  - "integrations-next/*"
  # - "examples/kitchen-sink"
  - "examples/vnext"
  - "examples/bird-checker-with-nextjs"
  - "examples/bird-checker-with-nextjs-and-eval"
  - "examples/bird-checker-with-express"
  - "examples/crypto-chatbot"
  - "examples/openapi-spec-writer"
  - "examples/stock-price-tool"
  - "docs"
