packages:
  - "packages/*"
  - "deployers/*"
  - "storage/*"
  - "vector-stores/*"
  - "speech/*"
  - "integration-generator/*"
  - "integrations/*"
  - "examples/*"
  - "examples/basics/**/*"
  - "docs"
  - "packages/cli/src/playground"
