packages:
  - "packages/*"
  - "!packages/cli/admin"
  - "integration-generator/*"
  - "integrations/*"
  - "examples/*"
  - "!examples/travel-app"
  - "examples/basics/llms/*"
  - "docs"
  - "packages/cli/src/shared/ui"
