packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  - "integrations/*"
  - "examples/*"
  - "packages/cli/admin"
  - "integration-generator/*"
  - "examples/kitchen-sink"
  - "docs"
