packages:
  - "packages/*"
  - "deployers/*"
  - "stores/*"
  - "voice/*"
  - "workflows/*"
  - "pubsub/*"
  - "client-sdks/*"
  - "!packages/cli/admin"
  - "integrations/*"
  - "examples/dane"
  - "packages/cli/src/playground"
  - "packages/*/integration-tests"
  - "packages/*/integration-tests-v5"
  - "packages/cloud"
  - "auth/*"
  - "observability/*"
  - "explorations/longmemeval"
