packages:
  - packages/*
  - deployers/*
  - stores/*
  - voice/*
  - workflows/*
  - pubsub/*
  - client-sdks/*
  - integrations/*
  - examples/dane
  - auth/*
  - observability/*
  - observability/otel-bridge/examples/*
  - explorations/longmemeval
  - explorations/agent-builder-gh-repro

patchedDependencies:
  '@changesets/get-dependents-graph': patches/@changesets__get-dependents-graph.patch
