packages:
  - "packages/*"
  - "deployers/*"
  - "storage/*"
  - "vector-stores/*"
  - "stores/*"
  - "speech/*"
  - "client-sdks/*"
  - "!packages/cli/admin"
  - "integration-generator/*"
  - "integrations/*"
  - "examples/*"
  - "examples/basics/**/*"
  - "examples/basics/llms/*"
  - "examples/client-sdk-js/*"
  - "docs"
  - "packages/cli/src/playground"
  - "packages/*/integration-tests"
