packages:
  - "packages/*"
  - "deployers/*"
  - "stores/*"
  - "voice/*"
  - "workflows/*"
  - "pubsub/*"
  - "client-sdks/*"
  - "integrations/*"
  - "examples/dane"
  - "auth/*"
  - "observability/*"
  - "explorations/longmemeval"
  - "explorations/agent-builder-gh-repro"
