packages:
  # all packages in direct subdirs of packages/
  - "packages/*"
  # - "integrations/*"
  # - "examples/*"
  - "!packages/cli/admin"
  - "integration-generator/*"
  - "integrations-next/*"
  # - "examples/kitchen-sink"
  - "examples/vnext"
  - "examples/stock-price-tool"
  - "docs"
