import type { ListScoresFilter } from '../../types';
import { StorageDomain } from '../base';

/** Comparison operator used when checking an aggregated value against a monitor threshold. */
export type MonitorThresholdOp = 'lt' | 'lte' | 'gt' | 'gte';

/** Aggregation applied to the scores matched by a monitor's filter within its window. */
export type MonitorAggregation = 'avg' | 'p50' | 'p95' | 'count' | 'passRate';

/**
 * Delivery channel for monitor breach notifications. v1 supports webhooks
 * (plain JSON payload or Slack-compatible payload); callers route these into
 * Datadog/PagerDuty/etc. themselves.
 */
export type MonitorChannel = {
  type: 'webhook';
  url: string;
  /** `json` (default) posts the raw breach payload; `slack` posts a Slack-compatible `{ text }` body. */
  format?: 'json' | 'slack';
};

/**
 * Score filter attached to a monitor. Identical to {@link ListScoresFilter}
 * except the date bounds are excluded — the monitor's evaluation window
 * supplies them at evaluation time.
 */
export type MonitorScoreFilter = Omit<ListScoresFilter, 'startDate' | 'endDate'>;

/** Lifecycle status of a monitor. */
export type MonitorStatus = 'active' | 'paused';

/** A persisted monitor definition. */
export type Monitor = {
  id: string;
  name: string;
  /** Score filter evaluated within the window (scorerIds, entity, metadata, …). */
  filter?: MonitorScoreFilter;
  /** Evaluation window size in minutes (lookback from evaluation time). */
  windowMinutes: number;
  aggregation: MonitorAggregation;
  /** Scores >= this value count as passing when `aggregation === 'passRate'`. Defaults to 1. */
  passThreshold?: number;
  threshold: { op: MonitorThresholdOp; value: number };
  /** Minimum minutes between consecutive breach notifications. Defaults to 0 (no cooldown). */
  cooldownMinutes?: number;
  channels: MonitorChannel[];
  /** Behavior when the window contains no scores: `skip` (default) or `breach`. */
  noDataBehavior?: 'skip' | 'breach';
  status: MonitorStatus;
  /** Epoch ms of the last evaluation, breach state used for cooldown/recovery. */
  lastEvaluatedAt?: number;
  lastBreachAt?: number;
  /** True while the monitor is in a breached state (used to emit recovery events). */
  breached?: boolean;
  metadata?: Record<string, unknown>;
  createdAt: number;
  updatedAt: number;
};

/** Kind of event recorded in a monitor's history. */
export type MonitorEventType = 'breach' | 'recovery' | 'delivery_failure';

/** Audit record produced when a monitor breaches, recovers, or fails to deliver. */
export type MonitorEvent = {
  /** Generated by storage when omitted on write. */
  id?: string;
  monitorId: string;
  type: MonitorEventType;
  /** Aggregated value observed for the window (null when the window had no scores). */
  value: number | null;
  /** Number of scores in the window. */
  count: number;
  threshold: { op: MonitorThresholdOp; value: number };
  /** Window bounds (epoch ms). */
  windowStart: number;
  windowEnd: number;
  /** Delivery error message when `type === 'delivery_failure'`. */
  error?: string;
  metadata?: Record<string, unknown>;
  createdAt: number;
};

/** Fields that can be patched via {@link MonitorsStorage.updateMonitor}. */
export type MonitorUpdate = Partial<
  Pick<
    Monitor,
    | 'name'
    | 'filter'
    | 'windowMinutes'
    | 'aggregation'
    | 'passThreshold'
    | 'threshold'
    | 'cooldownMinutes'
    | 'channels'
    | 'noDataBehavior'
    | 'status'
    | 'lastEvaluatedAt'
    | 'lastBreachAt'
    | 'breached'
    | 'metadata'
  >
>;

/** Filter / pagination options for listing monitor event history. */
export type MonitorEventListOptions = {
  limit?: number;
  type?: MonitorEventType;
  /** Inclusive lower bound on createdAt (epoch ms). */
  fromCreatedAt?: number;
  /** Exclusive upper bound on createdAt (epoch ms). */
  toCreatedAt?: number;
};

const MONITOR_THRESHOLD_OPS: MonitorThresholdOp[] = ['lt', 'lte', 'gt', 'gte'];
const MONITOR_AGGREGATIONS: MonitorAggregation[] = ['avg', 'p50', 'p95', 'count', 'passRate'];

/**
 * Validates a monitor definition's semantic fields. Throws on invalid
 * threshold op, aggregation, window, or channels. Shared by all adapters so
 * validation stays consistent regardless of backend.
 */
export function validateMonitor(monitor: Pick<Monitor, 'windowMinutes' | 'aggregation' | 'threshold' | 'channels'>) {
  if (!MONITOR_THRESHOLD_OPS.includes(monitor.threshold?.op)) {
    throw new Error(`Invalid monitor threshold op: ${String(monitor.threshold?.op)}`);
  }
  if (typeof monitor.threshold.value !== 'number' || Number.isNaN(monitor.threshold.value)) {
    throw new Error(`Invalid monitor threshold value: ${String(monitor.threshold?.value)}`);
  }
  if (!MONITOR_AGGREGATIONS.includes(monitor.aggregation)) {
    throw new Error(`Invalid monitor aggregation: ${String(monitor.aggregation)}`);
  }
  if (typeof monitor.windowMinutes !== 'number' || monitor.windowMinutes <= 0) {
    throw new Error(`Invalid monitor window: ${String(monitor.windowMinutes)}`);
  }
  for (const channel of monitor.channels ?? []) {
    if (channel.type !== 'webhook' || !channel.url) {
      throw new Error(`Invalid monitor channel: ${JSON.stringify(channel)}`);
    }
  }
}

/**
 * Abstract storage domain for score monitors and their breach history.
 * Powers the monitor evaluation loop: the evaluator lists active monitors,
 * aggregates scores via the scores domain, and records breach/recovery
 * events here.
 */
export abstract class MonitorsStorage extends StorageDomain {
  constructor() {
    super({
      component: 'STORAGE',
      name: 'MONITORS',
    });
  }

  async dangerouslyClearAll(): Promise<void> {
    // Default no-op — subclasses override
  }

  /** Insert a new monitor. Throws if a row with the same id already exists. Returns the stored row. */
  abstract createMonitor(monitor: Monitor): Promise<Monitor>;

  /** Get a single monitor by id. Returns null if not found. */
  abstract getMonitor(id: string): Promise<Monitor | null>;

  /** List monitors, optionally filtered by status. Oldest first. */
  abstract listMonitors(filter?: { status?: MonitorStatus }): Promise<Monitor[]>;

  /** Partial update of a monitor. Throws if not found. */
  abstract updateMonitor(id: string, patch: MonitorUpdate): Promise<Monitor>;

  /** Delete a monitor and its event history. */
  abstract deleteMonitor(id: string): Promise<void>;

  /** Append an entry to a monitor's event history. Returns the stored event (with id). */
  abstract recordMonitorEvent(event: MonitorEvent): Promise<MonitorEvent>;

  /** List event history for a monitor, newest first. */
  abstract listMonitorEvents(monitorId: string, opts?: MonitorEventListOptions): Promise<MonitorEvent[]>;
}
