export const Colors = {
  accent1: 'var(--accent1)',
  accent2: 'var(--accent2)',
  accent3: 'var(--accent3)',
  accent5: 'var(--accent5)',
  accent6: 'var(--accent6)',
  accent1Dark: 'var(--accent1Dark)',
  accent2Dark: 'var(--accent2Dark)',
  accent3Dark: 'var(--accent3Dark)',
  accent5Dark: 'var(--accent5Dark)',
  accent6Dark: 'var(--accent6Dark)',
  accent1Darker: 'var(--accent1Darker)',
  accent2Darker: 'var(--accent2Darker)',
  accent3Darker: 'var(--accent3Darker)',
  accent5Darker: 'var(--accent5Darker)',
  accent6Darker: 'var(--accent6Darker)',
  neutral1: 'var(--neutral1)',
  neutral2: 'var(--neutral2)',
  neutral3: 'var(--neutral3)',
  neutral4: 'var(--neutral4)',
  neutral5: 'var(--neutral5)',
  neutral6: 'var(--neutral6)',
  background: 'var(--background)',
  sidebar: 'var(--sidebar)',
  card: 'var(--card)',
  popover: 'var(--popover)',
  'surface-panel': 'var(--surface-panel)',
  'fill-subtle': 'var(--fill-subtle)',
  fill: 'var(--fill)',
  'fill-hover': 'var(--fill-hover)',
  'fill-active': 'var(--fill-active)',
  'fill-strong': 'var(--fill-strong)',
  muted: 'var(--muted)',
  foreground: 'var(--foreground)',
  'muted-foreground': 'var(--muted-foreground)',
  placeholder: 'var(--placeholder)',
  ring: 'var(--ring)',
  destructive: 'var(--destructive)',
  'destructive-foreground': 'var(--destructive-foreground)',

  error: 'var(--error)',

  overlay: 'var(--overlay)',
};

export const BorderColors = {
  border: 'var(--border)',
  'border-strong': 'var(--border-strong)',
  'border-hover': 'var(--border-hover)',
  'border-focus': 'var(--border-focus)',
};
