export const Colors = {
  'ds-green': 'var(--color-ds-green)',
  'ds-orange': 'var(--color-ds-orange)',
  'ds-pink': 'var(--color-ds-pink)',
  'ds-purple': 'var(--color-ds-purple)',
  'ds-blue': 'var(--color-ds-blue)',
  'ds-red': 'var(--color-ds-red)',
  'ds-yellow': 'var(--color-ds-yellow)',

  'destructive-bg': 'var(--destructive-bg)',
  'destructive-border': 'var(--destructive-border)',
  'destructive-indicator': 'var(--destructive-indicator)',
  'destructive-fg': 'var(--destructive-fg)',
  'warning-bg': 'var(--warning-bg)',
  'warning-border': 'var(--warning-border)',
  'warning-indicator': 'var(--warning-indicator)',
  'warning-fg': 'var(--warning-fg)',
  'success-bg': 'var(--success-bg)',
  'success-border': 'var(--success-border)',
  'success-indicator': 'var(--success-indicator)',
  'success-fg': 'var(--success-fg)',
  'info-bg': 'var(--info-bg)',
  'info-border': 'var(--info-border)',
  'info-indicator': 'var(--info-indicator)',
  'info-fg': 'var(--info-fg)',
  'product-studio-bg': 'var(--product-studio-bg)',
  'product-studio-fg': 'var(--product-studio-fg)',
  'product-server-bg': 'var(--product-server-bg)',
  'product-server-fg': 'var(--product-server-fg)',
  'product-observability-bg': 'var(--product-observability-bg)',
  'product-observability-fg': 'var(--product-observability-fg)',
  'product-factory-bg': 'var(--product-factory-bg)',
  'product-factory-fg': 'var(--product-factory-fg)',
  'product-workers-bg': 'var(--product-workers-bg)',
  'product-workers-fg': 'var(--product-workers-fg)',
  'product-persistent-server-bg': 'var(--product-persistent-server-bg)',
  'product-persistent-server-fg': 'var(--product-persistent-server-fg)',
  background: 'var(--background)',
  sidebar: 'var(--sidebar)',
  card: 'var(--card)',
  popover: 'var(--popover)',
  'surface-panel': 'var(--surface-panel)',
  'surface-overlay-soft': 'var(--surface-overlay-soft)',
  'surface-overlay-strong': 'var(--surface-overlay-strong)',
  'fill-subtle': 'var(--fill-subtle)',
  fill: 'var(--fill)',
  'fill-hover': 'var(--fill-hover)',
  'fill-active': 'var(--fill-active)',
  'fill-strong': 'var(--fill-strong)',
  'fill-inverse': 'var(--fill-inverse)',
  'fill-inverse-hover': 'var(--fill-inverse-hover)',
  'fill-inverse-active': 'var(--fill-inverse-active)',
  'fill-inverse-disabled': 'var(--fill-inverse-disabled)',
  'fill-destructive': 'var(--fill-destructive)',
  'fill-destructive-hover': 'var(--fill-destructive-hover)',
  'fill-destructive-active': 'var(--fill-destructive-active)',
  'fill-destructive-disabled': 'var(--fill-destructive-disabled)',
  muted: 'var(--muted)',
  foreground: 'var(--foreground)',
  'muted-foreground': 'var(--muted-foreground)',
  placeholder: 'var(--placeholder)',
  ring: 'var(--ring)',
  destructive: 'var(--destructive)',
  'destructive-foreground': 'var(--destructive-foreground)',

  error: 'var(--error)',

  scrim: 'var(--scrim)',

  'notice-note': 'var(--notice-note)',
  'notice-note-fg': 'var(--notice-note-fg)',

  'badge-purple-bg': 'var(--badge-purple-bg)',
  'badge-purple-border': 'var(--badge-purple-border)',
  'badge-orange-bg': 'var(--badge-orange-bg)',
  'badge-orange-border': 'var(--badge-orange-border)',
  'badge-cyan-bg': 'var(--badge-cyan-bg)',
  'badge-cyan-border': 'var(--badge-cyan-border)',
  'badge-pink-bg': 'var(--badge-pink-bg)',
  'badge-pink-border': 'var(--badge-pink-border)',
  'badge-neutral-fg': 'var(--badge-neutral-fg)',
  'badge-purple': 'var(--badge-purple)',
  'badge-purple-fg': 'var(--badge-purple-fg)',
  'badge-orange': 'var(--badge-orange)',
  'badge-orange-fg': 'var(--badge-orange-fg)',
  'badge-cyan': 'var(--badge-cyan)',
  'badge-cyan-fg': 'var(--badge-cyan-fg)',
  'badge-pink': 'var(--badge-pink)',
  'badge-pink-fg': 'var(--badge-pink-fg)',

  'green-50': 'var(--green-50)',
  'green-100': 'var(--green-100)',
  'green-200': 'var(--green-200)',
  'green-300': 'var(--green-300)',
  'green-400': 'var(--green-400)',
  'green-500': 'var(--green-500)',
  'green-600': 'var(--green-600)',
  'green-700': 'var(--green-700)',
  'green-800': 'var(--green-800)',
  'green-900': 'var(--green-900)',
  'green-950': 'var(--green-950)',
};

export const BorderColors = {
  border: 'var(--border)',
  'border-strong': 'var(--border-strong)',
  'border-hover': 'var(--border-hover)',
  'border-focus': 'var(--border-focus)',
};

export const CHART_LABEL_COLOR = 'var(--muted-foreground)';
