export const Sizes = {
  'icon-default': '16px',
  'icon-lg': '20px',
  'icon-sm': '12px',
  'button-md': '24px',
  'button-lg': '40px',
  'header-default': '40px',
  'table-header': '28px',
  'table-row': '44px',
  'table-row-small': '32px',
  'badge-default': '20px',
  'avatar-sm': '24px',
  'avatar-md': '32px',
  'avatar-lg': '40px',
  'dropdown-max-height': '300px',
};
