services:
  db:
    image: postgres:13
    container_name: 'contact-book-db'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-mastra}
    volumes:
      - pgdata:/var/lib/postgresql/data

  inngest:
    container_name: 'contact-book-inngest'
    image: inngest/inngest:v0.27.0
    ports:
      - '8288:8288'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command: 'inngest dev -u http://app:3000/api/inngest'

volumes:
  pgdata:
