/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is generated by packages/server/scripts/generate-permissions.ts
 * Run `pnpm generate:permissions` from packages/server to regenerate.
 *
 * Source of truth: SERVER_ROUTES in @mastra/server
 */

/**
 * All known API resources.
 * Derived from SERVER_ROUTES paths in @mastra/server.
 */
export const RESOURCES = [
  'a2a',
  'agent-builder',
  'agents',
  'logs',
  'mcp',
  'memory',
  'observability',
  'processors',
  'scores',
  'stored-agents',
  'system',
  'tools',
  'vector',
  'workflows',
  'workspaces',
] as const;

/**
 * Resource type union.
 */
export type Resource = (typeof RESOURCES)[number];

/**
 * All permission actions.
 * Derived from HTTP methods and route overrides:
 * - GET → read
 * - POST → write or execute (context-dependent)
 * - PUT/PATCH → write
 * - DELETE → delete
 * - Additional actions from explicit requiresPermission overrides
 */
export const ACTIONS = ['delete', 'execute', 'read', 'write'] as const;

/**
 * Action type union.
 */
export type Action = (typeof ACTIONS)[number];

/**
 * All valid permission patterns.
 * Use `keyof typeof PERMISSION_PATTERNS` or the `PermissionPattern` type.
 */
export const PERMISSION_PATTERNS = {
  '*': '*',
  '*:delete': '*:delete',
  '*:execute': '*:execute',
  '*:read': '*:read',
  '*:write': '*:write',
  'a2a:*': 'a2a:*',
  'agent-builder:*': 'agent-builder:*',
  'agents:*': 'agents:*',
  'logs:*': 'logs:*',
  'mcp:*': 'mcp:*',
  'memory:*': 'memory:*',
  'observability:*': 'observability:*',
  'processors:*': 'processors:*',
  'scores:*': 'scores:*',
  'stored-agents:*': 'stored-agents:*',
  'system:*': 'system:*',
  'tools:*': 'tools:*',
  'vector:*': 'vector:*',
  'workflows:*': 'workflows:*',
  'workspaces:*': 'workspaces:*',
  'a2a:read': 'a2a:read',
  'a2a:write': 'a2a:write',
  'agent-builder:execute': 'agent-builder:execute',
  'agent-builder:read': 'agent-builder:read',
  'agent-builder:write': 'agent-builder:write',
  'agents:execute': 'agents:execute',
  'agents:read': 'agents:read',
  'agents:write': 'agents:write',
  'logs:read': 'logs:read',
  'mcp:execute': 'mcp:execute',
  'mcp:read': 'mcp:read',
  'mcp:write': 'mcp:write',
  'memory:delete': 'memory:delete',
  'memory:execute': 'memory:execute',
  'memory:read': 'memory:read',
  'memory:write': 'memory:write',
  'observability:read': 'observability:read',
  'observability:write': 'observability:write',
  'processors:execute': 'processors:execute',
  'processors:read': 'processors:read',
  'scores:read': 'scores:read',
  'scores:write': 'scores:write',
  'stored-agents:delete': 'stored-agents:delete',
  'stored-agents:read': 'stored-agents:read',
  'stored-agents:write': 'stored-agents:write',
  'system:read': 'system:read',
  'tools:execute': 'tools:execute',
  'tools:read': 'tools:read',
  'vector:delete': 'vector:delete',
  'vector:execute': 'vector:execute',
  'vector:read': 'vector:read',
  'vector:write': 'vector:write',
  'workflows:delete': 'workflows:delete',
  'workflows:execute': 'workflows:execute',
  'workflows:read': 'workflows:read',
  'workflows:write': 'workflows:write',
  'workspaces:delete': 'workspaces:delete',
  'workspaces:read': 'workspaces:read',
  'workspaces:write': 'workspaces:write',
} as const;

/**
 * Permission pattern that can be used in role definitions.
 * Supports:
 * - Specific permissions: 'agents:read', 'workflows:execute'
 * - Resource wildcards: 'agents:*', 'workflows:*' (all actions on a resource)
 * - Action wildcards: '*:read', '*:write' (an action across all resources)
 * - Global wildcard: '*' (full access)
 */
export type PermissionPattern = keyof typeof PERMISSION_PATTERNS;

/**
 * All valid resource:action permission combinations (excludes wildcards).
 */
export const PERMISSIONS = [
  'a2a:read',
  'a2a:write',
  'agent-builder:execute',
  'agent-builder:read',
  'agent-builder:write',
  'agents:execute',
  'agents:read',
  'agents:write',
  'logs:read',
  'mcp:execute',
  'mcp:read',
  'mcp:write',
  'memory:delete',
  'memory:execute',
  'memory:read',
  'memory:write',
  'observability:read',
  'observability:write',
  'processors:execute',
  'processors:read',
  'scores:read',
  'scores:write',
  'stored-agents:delete',
  'stored-agents:read',
  'stored-agents:write',
  'system:read',
  'tools:execute',
  'tools:read',
  'vector:delete',
  'vector:execute',
  'vector:read',
  'vector:write',
  'workflows:delete',
  'workflows:execute',
  'workflows:read',
  'workflows:write',
  'workspaces:delete',
  'workspaces:read',
  'workspaces:write',
] as const;

/**
 * Specific permission type (e.g., 'agents:read', 'workflows:execute').
 */
export type Permission = (typeof PERMISSIONS)[number];

/**
 * Type-safe role mapping configuration.
 *
 * Maps role names (from your identity provider) to Mastra permission patterns.
 *
 * @example
 * ```typescript
 * const roleMapping: TypedRoleMapping = {
 *   "Engineering": ["agents:*", "workflows:*"],
 *   "Product": ["agents:read", "workflows:read"],
 *   "Admin": ["*"],
 *   "_default": [],
 * };
 * ```
 */
export type TypedRoleMapping = {
  [role: string]: PermissionPattern[];
};

/**
 * Validates that a string is a valid permission pattern.
 * Useful for runtime validation of permission strings.
 */
export function isValidPermissionPattern(pattern: string): pattern is PermissionPattern {
  return pattern in PERMISSION_PATTERNS;
}

/**
 * Validates that all permissions in an array are valid patterns.
 */
export function validatePermissions(permissions: string[]): permissions is PermissionPattern[] {
  return permissions.every(isValidPermissionPattern);
}
