/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is generated by packages/server/scripts/generate-permissions.ts
 * Run `pnpm generate:permissions` from packages/server to regenerate.
 *
 * Source of truth: SERVER_ROUTES in @mastra/server
 */

/**
 * All known API resources.
 * Derived from SERVER_ROUTES paths in @mastra/server.
 */
export const RESOURCES = [
  'a2a',
  'agent-builder',
  'agents',
  'auth',
  'logs',
  'mcp',
  'memory',
  'observability',
  'processors',
  'scores',
  'settings',
  'stored-agents',
  'studio',
  'system',
  'tools',
  'users',
  'vector',
  'workflows',
  'workspaces',
] as const;

/**
 * Resource type union.
 */
export type Resource = (typeof RESOURCES)[number];

/**
 * All permission actions.
 * Derived from METHOD_TO_ACTION mapping:
 * - GET → read
 * - POST → write or execute (context-dependent)
 * - PUT/PATCH → write
 * - DELETE → delete
 * Plus Studio-specific actions: admin, invite
 */
export const ACTIONS = ['admin', 'delete', 'execute', 'invite', 'read', 'write'] as const;

/**
 * Action type union.
 */
export type Action = (typeof ACTIONS)[number];

/**
 * All valid resource:action permission combinations.
 */
export const PERMISSIONS = [
  'a2a:admin',
  'a2a:delete',
  'a2a:execute',
  'a2a:invite',
  'a2a:read',
  'a2a:write',
  'agent-builder:admin',
  'agent-builder:delete',
  'agent-builder:execute',
  'agent-builder:invite',
  'agent-builder:read',
  'agent-builder:write',
  'agents:admin',
  'agents:delete',
  'agents:execute',
  'agents:invite',
  'agents:read',
  'agents:write',
  'auth:admin',
  'auth:delete',
  'auth:execute',
  'auth:invite',
  'auth:read',
  'auth:write',
  'logs:admin',
  'logs:delete',
  'logs:execute',
  'logs:invite',
  'logs:read',
  'logs:write',
  'mcp:admin',
  'mcp:delete',
  'mcp:execute',
  'mcp:invite',
  'mcp:read',
  'mcp:write',
  'memory:admin',
  'memory:delete',
  'memory:execute',
  'memory:invite',
  'memory:read',
  'memory:write',
  'observability:admin',
  'observability:delete',
  'observability:execute',
  'observability:invite',
  'observability:read',
  'observability:write',
  'processors:admin',
  'processors:delete',
  'processors:execute',
  'processors:invite',
  'processors:read',
  'processors:write',
  'scores:admin',
  'scores:delete',
  'scores:execute',
  'scores:invite',
  'scores:read',
  'scores:write',
  'settings:admin',
  'settings:delete',
  'settings:execute',
  'settings:invite',
  'settings:read',
  'settings:write',
  'stored-agents:admin',
  'stored-agents:delete',
  'stored-agents:execute',
  'stored-agents:invite',
  'stored-agents:read',
  'stored-agents:write',
  'studio:admin',
  'studio:delete',
  'studio:execute',
  'studio:invite',
  'studio:read',
  'studio:write',
  'system:admin',
  'system:delete',
  'system:execute',
  'system:invite',
  'system:read',
  'system:write',
  'tools:admin',
  'tools:delete',
  'tools:execute',
  'tools:invite',
  'tools:read',
  'tools:write',
  'users:admin',
  'users:delete',
  'users:execute',
  'users:invite',
  'users:read',
  'users:write',
  'vector:admin',
  'vector:delete',
  'vector:execute',
  'vector:invite',
  'vector:read',
  'vector:write',
  'workflows:admin',
  'workflows:delete',
  'workflows:execute',
  'workflows:invite',
  'workflows:read',
  'workflows:write',
  'workspaces:admin',
  'workspaces:delete',
  'workspaces:execute',
  'workspaces:invite',
  'workspaces:read',
  'workspaces:write',
] as const;

/**
 * Specific permission type (e.g., 'agents:read', 'workflows:execute').
 */
export type Permission = (typeof PERMISSIONS)[number];

/**
 * Permission pattern that can be used in role definitions.
 * Supports:
 * - Specific permissions: 'agents:read', 'workflows:execute'
 * - Resource wildcards: 'agents:*', 'workflows:*' (all actions on a resource)
 * - Action wildcards: '*:read', '*:write' (an action across all resources)
 * - Global wildcard: '*' (full access)
 */
export type PermissionPattern = Permission | '*' | `${Resource}:*` | `*:${Action}`;

/**
 * Type-safe role mapping configuration.
 *
 * Maps role names (from your identity provider) to Mastra permission patterns.
 *
 * @example
 * ```typescript
 * const roleMapping: TypedRoleMapping = {
 *   "Engineering": ["agents:*", "workflows:*"],
 *   "Product": ["agents:read", "workflows:read"],
 *   "Admin": ["*"],
 *   "_default": [],
 * };
 * ```
 */
export type TypedRoleMapping = {
  [role: string]: PermissionPattern[];
};

/**
 * Validates that a string is a valid permission pattern.
 * Useful for runtime validation of permission strings.
 */
export function isValidPermissionPattern(pattern: string): pattern is PermissionPattern {
  if (pattern === '*') return true;
  // Resource wildcard: 'agents:*'
  if (pattern.endsWith(':*')) {
    const resource = pattern.slice(0, -2);
    return (RESOURCES as readonly string[]).includes(resource);
  }
  // Action wildcard: '*:read'
  if (pattern.startsWith('*:')) {
    const action = pattern.slice(2);
    return (ACTIONS as readonly string[]).includes(action);
  }
  return (PERMISSIONS as readonly string[]).includes(pattern);
}

/**
 * Validates that all permissions in an array are valid patterns.
 */
export function validatePermissions(permissions: string[]): permissions is PermissionPattern[] {
  return permissions.every(isValidPermissionPattern);
}
