/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is generated by packages/server/scripts/generate-permissions.ts
 * Run `pnpm generate:permissions` from packages/server to regenerate.
 *
 * Source of truth: SERVER_ROUTES in @mastra/server
 */

/**
 * All known API resources.
 * Derived from SERVER_ROUTES paths in @mastra/server.
 */
export const RESOURCES = [
  'a2a',
  'agent-builder',
  'agents',
  'logs',
  'mcp',
  'memory',
  'observability',
  'processors',
  'scores',
  'stored-agents',
  'system',
  'tools',
  'vector',
  'workflows',
  'workspaces',
] as const;

/**
 * Resource type union.
 */
export type Resource = (typeof RESOURCES)[number];

/**
 * All permission actions.
 * Derived from HTTP methods and route overrides:
 * - GET → read
 * - POST → write or execute (context-dependent)
 * - PUT/PATCH → write
 * - DELETE → delete
 * - Additional actions from explicit requiresPermission overrides
 */
export const ACTIONS = ['delete', 'execute', 'read', 'write'] as const;

/**
 * Action type union.
 */
export type Action = (typeof ACTIONS)[number];

/**
 * All valid permission patterns.
 */
export const PERMISSION_PATTERNS = {
  /** Full access to all resources and actions */
  '*': '*',
  /** Delete all resources */
  '*:delete': '*:delete',
  /** Execute all resources */
  '*:execute': '*:execute',
  /** View all resources */
  '*:read': '*:read',
  /** Create and modify all resources */
  '*:write': '*:write',
  /** Full access to agent-to-agent communication */
  'a2a:*': 'a2a:*',
  /** Full access to agent builder */
  'agent-builder:*': 'agent-builder:*',
  /** Full access to agents */
  'agents:*': 'agents:*',
  /** Full access to logs */
  'logs:*': 'logs:*',
  /** Full access to MCP servers */
  'mcp:*': 'mcp:*',
  /** Full access to memory and threads */
  'memory:*': 'memory:*',
  /** Full access to traces and spans */
  'observability:*': 'observability:*',
  /** Full access to processors */
  'processors:*': 'processors:*',
  /** Full access to evaluation scores */
  'scores:*': 'scores:*',
  /** Full access to stored agents */
  'stored-agents:*': 'stored-agents:*',
  /** Full access to system info */
  'system:*': 'system:*',
  /** Full access to tools */
  'tools:*': 'tools:*',
  /** Full access to vector stores */
  'vector:*': 'vector:*',
  /** Full access to workflows */
  'workflows:*': 'workflows:*',
  /** Full access to workspaces */
  'workspaces:*': 'workspaces:*',
  /** View agent-to-agent communication */
  'a2a:read': 'a2a:read',
  /** Create and modify agent-to-agent communication */
  'a2a:write': 'a2a:write',
  /** Execute agent builder */
  'agent-builder:execute': 'agent-builder:execute',
  /** View agent builder */
  'agent-builder:read': 'agent-builder:read',
  /** Create and modify agent builder */
  'agent-builder:write': 'agent-builder:write',
  /** Execute agents */
  'agents:execute': 'agents:execute',
  /** View agents */
  'agents:read': 'agents:read',
  /** Create and modify agents */
  'agents:write': 'agents:write',
  /** View logs */
  'logs:read': 'logs:read',
  /** Execute MCP servers */
  'mcp:execute': 'mcp:execute',
  /** View MCP servers */
  'mcp:read': 'mcp:read',
  /** Create and modify MCP servers */
  'mcp:write': 'mcp:write',
  /** Delete memory and threads */
  'memory:delete': 'memory:delete',
  /** Execute memory and threads */
  'memory:execute': 'memory:execute',
  /** View memory and threads */
  'memory:read': 'memory:read',
  /** Create and modify memory and threads */
  'memory:write': 'memory:write',
  /** View traces and spans */
  'observability:read': 'observability:read',
  /** Create and modify traces and spans */
  'observability:write': 'observability:write',
  /** Execute processors */
  'processors:execute': 'processors:execute',
  /** View processors */
  'processors:read': 'processors:read',
  /** View evaluation scores */
  'scores:read': 'scores:read',
  /** Create and modify evaluation scores */
  'scores:write': 'scores:write',
  /** Delete stored agents */
  'stored-agents:delete': 'stored-agents:delete',
  /** View stored agents */
  'stored-agents:read': 'stored-agents:read',
  /** Create and modify stored agents */
  'stored-agents:write': 'stored-agents:write',
  /** View system info */
  'system:read': 'system:read',
  /** Execute tools */
  'tools:execute': 'tools:execute',
  /** View tools */
  'tools:read': 'tools:read',
  /** Delete vector stores */
  'vector:delete': 'vector:delete',
  /** Execute vector stores */
  'vector:execute': 'vector:execute',
  /** View vector stores */
  'vector:read': 'vector:read',
  /** Create and modify vector stores */
  'vector:write': 'vector:write',
  /** Delete workflows */
  'workflows:delete': 'workflows:delete',
  /** Execute workflows */
  'workflows:execute': 'workflows:execute',
  /** View workflows */
  'workflows:read': 'workflows:read',
  /** Create and modify workflows */
  'workflows:write': 'workflows:write',
  /** Delete workspaces */
  'workspaces:delete': 'workspaces:delete',
  /** View workspaces */
  'workspaces:read': 'workspaces:read',
  /** Create and modify workspaces */
  'workspaces:write': 'workspaces:write',
} as const;

/**
 * Permission constants with TSDoc descriptions for IDE autocomplete.
 *
 * Use these instead of string literals to get descriptions in autocomplete:
 * @example
 * ```typescript
 * import { P } from '@mastra/core/auth';
 *
 * const roleMapping = {
 *   admin: [P.All],           // "Full access to all resources and actions"
 *   viewer: [P.AllRead],      // "View all resources"
 *   agent_user: [P.AgentsExecute, P.AgentsRead],
 * };
 * ```
 */

export namespace P {
  /** Full access to all resources and actions */
  export const All = '*' as const;
  /** Delete all resources */
  export const AllDelete = '*:delete' as const;
  /** Execute all resources */
  export const AllExecute = '*:execute' as const;
  /** View all resources */
  export const AllRead = '*:read' as const;
  /** Create and modify all resources */
  export const AllWrite = '*:write' as const;
  /** Full access to agent-to-agent communication */
  export const A2aAll = 'a2a:*' as const;
  /** Full access to agent builder */
  export const AgentBuilderAll = 'agent-builder:*' as const;
  /** Full access to agents */
  export const AgentsAll = 'agents:*' as const;
  /** Full access to logs */
  export const LogsAll = 'logs:*' as const;
  /** Full access to MCP servers */
  export const McpAll = 'mcp:*' as const;
  /** Full access to memory and threads */
  export const MemoryAll = 'memory:*' as const;
  /** Full access to traces and spans */
  export const ObservabilityAll = 'observability:*' as const;
  /** Full access to processors */
  export const ProcessorsAll = 'processors:*' as const;
  /** Full access to evaluation scores */
  export const ScoresAll = 'scores:*' as const;
  /** Full access to stored agents */
  export const StoredAgentsAll = 'stored-agents:*' as const;
  /** Full access to system info */
  export const SystemAll = 'system:*' as const;
  /** Full access to tools */
  export const ToolsAll = 'tools:*' as const;
  /** Full access to vector stores */
  export const VectorAll = 'vector:*' as const;
  /** Full access to workflows */
  export const WorkflowsAll = 'workflows:*' as const;
  /** Full access to workspaces */
  export const WorkspacesAll = 'workspaces:*' as const;
  /** View agent-to-agent communication */
  export const A2aRead = 'a2a:read' as const;
  /** Create and modify agent-to-agent communication */
  export const A2aWrite = 'a2a:write' as const;
  /** Execute agent builder */
  export const AgentBuilderExecute = 'agent-builder:execute' as const;
  /** View agent builder */
  export const AgentBuilderRead = 'agent-builder:read' as const;
  /** Create and modify agent builder */
  export const AgentBuilderWrite = 'agent-builder:write' as const;
  /** Execute agents */
  export const AgentsExecute = 'agents:execute' as const;
  /** View agents */
  export const AgentsRead = 'agents:read' as const;
  /** Create and modify agents */
  export const AgentsWrite = 'agents:write' as const;
  /** View logs */
  export const LogsRead = 'logs:read' as const;
  /** Execute MCP servers */
  export const McpExecute = 'mcp:execute' as const;
  /** View MCP servers */
  export const McpRead = 'mcp:read' as const;
  /** Create and modify MCP servers */
  export const McpWrite = 'mcp:write' as const;
  /** Delete memory and threads */
  export const MemoryDelete = 'memory:delete' as const;
  /** Execute memory and threads */
  export const MemoryExecute = 'memory:execute' as const;
  /** View memory and threads */
  export const MemoryRead = 'memory:read' as const;
  /** Create and modify memory and threads */
  export const MemoryWrite = 'memory:write' as const;
  /** View traces and spans */
  export const ObservabilityRead = 'observability:read' as const;
  /** Create and modify traces and spans */
  export const ObservabilityWrite = 'observability:write' as const;
  /** Execute processors */
  export const ProcessorsExecute = 'processors:execute' as const;
  /** View processors */
  export const ProcessorsRead = 'processors:read' as const;
  /** View evaluation scores */
  export const ScoresRead = 'scores:read' as const;
  /** Create and modify evaluation scores */
  export const ScoresWrite = 'scores:write' as const;
  /** Delete stored agents */
  export const StoredAgentsDelete = 'stored-agents:delete' as const;
  /** View stored agents */
  export const StoredAgentsRead = 'stored-agents:read' as const;
  /** Create and modify stored agents */
  export const StoredAgentsWrite = 'stored-agents:write' as const;
  /** View system info */
  export const SystemRead = 'system:read' as const;
  /** Execute tools */
  export const ToolsExecute = 'tools:execute' as const;
  /** View tools */
  export const ToolsRead = 'tools:read' as const;
  /** Delete vector stores */
  export const VectorDelete = 'vector:delete' as const;
  /** Execute vector stores */
  export const VectorExecute = 'vector:execute' as const;
  /** View vector stores */
  export const VectorRead = 'vector:read' as const;
  /** Create and modify vector stores */
  export const VectorWrite = 'vector:write' as const;
  /** Delete workflows */
  export const WorkflowsDelete = 'workflows:delete' as const;
  /** Execute workflows */
  export const WorkflowsExecute = 'workflows:execute' as const;
  /** View workflows */
  export const WorkflowsRead = 'workflows:read' as const;
  /** Create and modify workflows */
  export const WorkflowsWrite = 'workflows:write' as const;
  /** Delete workspaces */
  export const WorkspacesDelete = 'workspaces:delete' as const;
  /** View workspaces */
  export const WorkspacesRead = 'workspaces:read' as const;
  /** Create and modify workspaces */
  export const WorkspacesWrite = 'workspaces:write' as const;
}

/**
 * Permission pattern that can be used in role definitions.
 * Supports:
 * - Specific permissions: 'agents:read', 'workflows:execute'
 * - Resource wildcards: 'agents:*', 'workflows:*' (all actions on a resource)
 * - Action wildcards: '*:read', '*:write' (an action across all resources)
 * - Global wildcard: '*' (full access)
 */
export type PermissionPattern = keyof typeof PERMISSION_PATTERNS;

/**
 * All valid resource:action permission combinations (excludes wildcards).
 */
export const PERMISSIONS = [
  'a2a:read',
  'a2a:write',
  'agent-builder:execute',
  'agent-builder:read',
  'agent-builder:write',
  'agents:execute',
  'agents:read',
  'agents:write',
  'logs:read',
  'mcp:execute',
  'mcp:read',
  'mcp:write',
  'memory:delete',
  'memory:execute',
  'memory:read',
  'memory:write',
  'observability:read',
  'observability:write',
  'processors:execute',
  'processors:read',
  'scores:read',
  'scores:write',
  'stored-agents:delete',
  'stored-agents:read',
  'stored-agents:write',
  'system:read',
  'tools:execute',
  'tools:read',
  'vector:delete',
  'vector:execute',
  'vector:read',
  'vector:write',
  'workflows:delete',
  'workflows:execute',
  'workflows:read',
  'workflows:write',
  'workspaces:delete',
  'workspaces:read',
  'workspaces:write',
] as const;

/**
 * Specific permission type (e.g., 'agents:read', 'workflows:execute').
 */
export type Permission = (typeof PERMISSIONS)[number];

/**
 * Type-safe role mapping configuration.
 *
 * Maps role names (from your identity provider) to Mastra permission patterns.
 *
 * @example
 * ```typescript
 * const roleMapping: TypedRoleMapping = {
 *   "Engineering": ["agents:*", "workflows:*"],
 *   "Product": ["agents:read", "workflows:read"],
 *   "Admin": ["*"],
 *   "_default": [],
 * };
 * ```
 */
export type TypedRoleMapping = {
  [role: string]: PermissionPattern[];
};

/**
 * Validates that a string is a valid permission pattern.
 * Useful for runtime validation of permission strings.
 */
export function isValidPermissionPattern(pattern: string): pattern is PermissionPattern {
  return pattern in PERMISSION_PATTERNS;
}

/**
 * Validates that all permissions in an array are valid patterns.
 */
export function validatePermissions(permissions: string[]): permissions is PermissionPattern[] {
  return permissions.every(isValidPermissionPattern);
}
