services:
  db:
    image: postgres:13
    container_name: 'vnext-db'
    ports:
      - '5433:5433'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-mastra}
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
