const meta = {
  "mastra-scorer": "MastraScorer クラス",
  "create-scorer": "createScorer",
  "run-experiment": "runExperiment",
  "answer-relevancy": "回答の関連性",
  "answer-similarity": "回答の類似性",
  bias: "バイアス",
  completeness: "網羅性",
  "content-similarity": "内容の類似性",
  "context-relevance": "文脈適合性",
  "context-precision": "文脈の精度",
  faithfulness: "忠実度",
  hallucination: "幻覚",
  "keyword-coverage": "キーワード網羅率",
  "textual-difference": "テキスト差分",
  "tone-consistency": "トーンの一貫性",
  "tool-call-accuracy": "ツール呼び出しの正確度",
  toxicity: "有害性",
  "noise-sensitivity": "ノイズ感受性",
  "prompt-alignment": "プロンプト適合性",
};
export default meta;