const meta = {
  index: "Overview",
  openai: "OpenAI",
  anthropic: "Anthropic",
  google: "Google",
  deepseek: "DeepSeek",
  mistral: "Mistral",
  xai: "xAI",
  alibaba: "Alibaba",
  baseten: "BaseTen",
  cerebras: "Cerebras",
  chutes: "Chutes",
  deepinfra: "DeepInfra",
  fastrouter: "FastRouter",
  github_copilot: "GitHub Copilot",
  github_models: "GitHub Models",
  inception: "Inception",
  inference: "Inference",
  llama: "Llama",
  lmstudio: "LM Studio",
  modelscope: "ModelScope",
  moonshotai: "MoonshotAI",
  moonshotai_cn: "MoonshotAI CN",
  morph: "Morph",
  nvidia: "NVIDIA",
  opencode: "OpenCode",
  submodel: "Submodel",
  synthetic: "Synthetic",
  upstage: "Upstage",
  venice: "Venice",
  wandb: "Weights & Biases",
  zai: "ZAI",
  zhipuai: "ZhipuAI",
};

export default meta;
