packages:
  - instrumentation
  - service-one
  - service-two
  - service-mastra

catalog:
  tsx: ^4.21.0
  typescript: ^5.9.3

overrides:
  protobufjs@>=7.0.0 <7.6.5: 7.6.6
  '@opentelemetry/propagator-jaeger@<2.9.0': 2.11.0
  hono: 4.13.5
  nanoid@>=3.0.0 <3.3.19: 3.3.19
  zod@>=4.0.0 <4.5.5: 4.6.5
  '@mastra/core': link:../../../../packages/core
  '@mastra/hono': link:../../../../server-adapters/hono
  '@mastra/observability': link:../../../mastra
  '@mastra/otel-bridge': link:../../../otel-bridge
  '@mastra/otel-exporter': link:../../../otel-exporter
  'brace-expansion@>=2.0.0 <2.1.4': 2.1.4
  mastra: link:../../../../packages/cli
