// Workspace hooks - filesystem and search
export {
  type WorkspaceCapabilities,
  type WorkspaceInfo,
  type WorkspaceItem,
  type WorkspacesListResponse,
  type FileEntry,
  type FileReadResponse,
  type FileListResponse,
  type FileStatResponse,
  type WriteFileParams,
  type WriteFileFromFileParams,
  type SearchWorkspaceParams,
  type SearchResult,
  type SearchResponse,
  useWorkspaceInfo,
  useWorkspaces,
  useWorkspaceFiles,
  useWorkspaceFile,
  useWorkspaceFileStat,
  useWriteWorkspaceFile,
  useWriteWorkspaceFileFromFile,
  useDeleteWorkspaceFile,
  useCreateWorkspaceDirectory,
  useSearchWorkspace,
  useIndexWorkspaceContent,
  useUnindexWorkspaceContent,
} from './use-workspace';

// Skills hooks and types
export {
  type SkillSource,
  type SkillMetadata,
  type Skill,
  type ListSkillsResponse,
  type SkillSearchResult,
  type SearchSkillsResponse,
  type ListReferencesResponse,
  type GetReferenceResponse,
  type SearchSkillsParams,
  useWorkspaceSkills,
  useWorkspaceSkill,
  useWorkspaceSkillReferences,
  useWorkspaceSkillReference,
  useSearchWorkspaceSkills,
  useAgentSkill,
} from './use-workspace-skills';
