// Workflow entrypoint: every turn is generated by the `phoneConversation` workflow instead of
// an agent loop. LiveKit owns the turn boundary, so the workflow runs once to completion per
// turn (no suspend/resume). The full transcript is passed in via `workflowInput`, so the
// workflow stays stateless between turns. For the agent entrypoint, see voice-worker.ts. Run
// one worker at a time — both register as `mastra-voice`.
import { fileURLToPath } from 'node:url';
import { chatContextToMessages, createLiveKitWorker, runLiveKitWorker } from '@mastra/livekit';
import { mastra } from './index';

export default createLiveKitWorker({
  mastra,
  workflow: 'phoneConversation',
  // Map each turn into the workflow's inputData. Passing the full LiveKit transcript every turn
  // keeps the workflow stateless — there is no conversation state to reconcile.
  workflowInput: ({ chatCtx }) => ({ history: chatContextToMessages(chatCtx) }),
  // The `generateResponse` step is the one that pipes text into its writer; only stream that.
  replyStep: 'generateResponse',
  stt: 'deepgram/nova-3',
  tts: 'cartesia/sonic-3',
  turnDetection: 'multilingual',
  greeting: 'Thanks for calling Meridian Trades, this is Jordan. How can I help you today?',
});

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runLiveKitWorker({ entry: import.meta.url, agentName: 'mastra-voice' });
}
