// Workflow entrypoint: every turn is generated by the `phoneConversation` workflow (classify
// intent, then reply) instead of an agent loop. LiveKit owns the turn boundary, so the workflow
// runs once to completion per turn (no suspend/resume). This worker is now at feature parity with
// the agent worker (voice-worker.ts): the same caller-scoped memory, greeting persistence, spoken
// tool feedback, and post-turn CRM log all work here too. Run one worker at a time — both
// register as `mastra-voice`.
import { fileURLToPath } from 'node:url';
import { createLiveKitWorker, runLiveKitWorker } from '@mastra/livekit/worker';
import { hasSummaryConsent, recordContact, summaryStorageRequired } from './backend';
import { mastra } from './index';
import { callCenterMemory, flushObservationalMemory } from './memory';

export default createLiveKitWorker({
  mastra,
  workflow: 'phoneConversation',
  // Map each turn into the workflow's inputData. `messages` is the new turn only — the reply
  // step's memory-backed agent.stream backfills prior turns from the thread, so there is no
  // conversation state to carry and no history duplication. `memory` scopes the call thread and
  // caller. (A stateless workflow would instead pass `chatContextToMessages(chatCtx)`.)
  workflowInput: ({ messages, memory }) => ({ turn: messages, memory: memory || undefined }),
  // The `generateResponse` step is the one that pipes text into its writer; only stream that.
  replyStep: 'generateResponse',
  // Scope memory for the call exactly like the agent worker: `thread` is this call, `resource`
  // is the caller so their collected details and working memory persist across calls.
  memory: ({ metadata, roomName }) => {
    const thread = metadata.threadId ?? roomName;
    return { thread, resource: metadata.resourceId ?? thread };
  },
  // On the workflow path there is no agent for the worker to source memory from, so hand it the
  // same Memory the steps read and write. This bootstraps the call thread up front and persists
  // the greeting, so the saved transcript is faithful (greeting + every turn) — just like the
  // agent path.
  memoryInstance: callCenterMemory,
  stt: 'deepgram/nova-3',
  tts: 'cartesia/sonic-3',
  turnDetection: 'multilingual',
  configuration: {
    greeting: {
      text: 'Thanks for calling Meridian Trades, this is Jordan. How can I help you today?',
      // Re-disclose the AI status every ~3 minutes on long calls, at the next turn boundary.
      repeatEvery: 3 * 60_000,
    },
    // Require consent before storing a summary of the call (the end-of-call OM distillation).
    requireConsent: { summaryStorage: true },
    // Agent-initiated hang-up — works on the workflow path too: the reply step pipes the agent's
    // fullStream, so the `endCall` tool call reaches the worker, which waits for the goodbye then
    // disconnects. Same detection as the agent worker.
    endCall: {},
  },
  // Spoken filler while a tool runs, so the caller isn't left in silence — same map as the agent
  // worker. On the workflow path it fires because the reply step pipes the agent's fullStream, so
  // tool-call chunks reach the package.
  toolFeedback: ({ toolName }) => {
    if (toolName === 'lookupCustomer') return 'Let me pull up your account.';
    if (toolName === 'checkAvailability') return 'One moment while I check the diary.';
    if (toolName === 'bookAppointment') return 'Okay, booking that site visit for you now.';
    if (toolName === 'rescheduleAppointment') return 'Let me move that visit.';
    if (toolName === 'cancelAppointment') return 'One second while I cancel that.';
    if (toolName === 'checkServiceArea') return 'Let me check whether you are in our service area.';
    if (toolName === 'finalizeIntake') return 'Great, let me get that logged for you.';
    return undefined;
  },
  // Post-turn maintenance, fully off the audio path — identical to the agent worker. `onTurnComplete`
  // now fires on the workflow path too: after the reply has streamed to TTS, and not awaited, so the
  // CRM write never adds to the caller's latency. It carries the reply text, the tool calls the
  // reply step surfaced, and whether barge-in cut the turn short.
  onTurnComplete: async ({ result, memory }) => {
    if (!memory) return;
    await recordContact({
      resourceId: memory.resource ?? memory.thread,
      reply: result.text,
      tools: result.toolCalls.map(t => t.toolName),
      interrupted: result.interrupted,
    });
  },
  // Same consent-aware end-of-call OM flush as the agent worker — distill the call into durable
  // memory once, after hang-up, off the audio path, and only when summary-storage consent isn't
  // required or has been granted.
  onCallEnd: async ({ memory, configuration }) => {
    if (!memory) return;
    const callerId = memory.resource ?? memory.thread;
    if (summaryStorageRequired(configuration?.requireConsent) && !hasSummaryConsent(callerId)) return;
    await flushObservationalMemory(memory);
  },
});

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  runLiveKitWorker({ entry: import.meta.url, agentName: 'mastra-voice' });
}
