import { getServerSideFallbackInfo } from '../llm/model/server-side-fallback';
import { getTransformedToolPayload, hasTransformedToolPayload } from '../tools/payload-transform';
import type { ToolPayloadTransformPhase } from '../tools/types';
import type { TokenUsage } from './types';

/**
 * Pure transforms shared by the run engine for folding raw agent-stream chunk
 * payloads into the `MastraDBMessage` shape a Session renders, plus terminal
 * finish-reason and server-side-fallback diagnostics. They hold no
 * AgentController or Session state, so they live in their own module.
 */

export function getDisplayTransform(metadata: unknown, phase: ToolPayloadTransformPhase, fallback: unknown) {
  const transform = getTransformedToolPayload(metadata, 'display', phase);
  return hasTransformedToolPayload(transform) ? transform.transformed : fallback;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function getAnthropicStopDetails(providerMetadata: unknown): Record<string, unknown> | undefined {
  if (!isRecord(providerMetadata)) {
    return undefined;
  }
  const anthropic = providerMetadata.anthropic;
  if (!isRecord(anthropic)) {
    return undefined;
  }
  const stopDetails = anthropic.stopDetails;
  return isRecord(stopDetails) ? stopDetails : undefined;
}

/**
 * Map a non-success terminal finish reason (content-filter, error, length, or a missing reason when the stream closed early) to a
 * user-facing message, or `undefined` for success reasons. A non-success finish
 * must become an explicit terminal error rather than a silent `complete`.
 */
export function describeNonSuccessFinishReason(reason: string, providerMetadata: unknown): string | undefined {
  switch (reason) {
    case 'content-filter': {
      const stopDetails = getAnthropicStopDetails(providerMetadata);
      const explanation =
        stopDetails && typeof stopDetails.explanation === 'string' ? stopDetails.explanation : undefined;
      const category = stopDetails && typeof stopDetails.category === 'string' ? stopDetails.category : undefined;
      const detail = explanation ?? (category ? `category: ${category}` : undefined);
      return detail ? `The model stopped on a content filter (${detail}).` : 'The model stopped on a content filter.';
    }
    case 'error':
      return 'The model stream ended with an error before producing a final response.';
    case 'length':
      return 'The model stopped because it reached its maximum output length before finishing.';
    // The model stream closed without ever sending a finish reason, so the run stopped mid-work.
    case '':
      return 'The model stream ended without a finish reason before producing a final response.';
    default:
      return undefined;
  }
}

/**
 * Build a user-facing notice when a turn was served by an Anthropic server-side
 * fallback model instead of the primary model. Without a notice the user has no
 * way to tell the response did not come from the model they selected.
 */
export function describeServerSideFallback(providerMetadata: unknown): string | undefined {
  const fallback = getServerSideFallbackInfo(providerMetadata);
  if (!fallback) {
    return undefined;
  }
  return fallback.model
    ? `The selected model declined this turn; the response was generated by fallback model ${fallback.model}.`
    : 'The selected model declined this turn; the response was generated by a fallback model.';
}

/** Coerce a usage field to a finite number, accepting numeric strings. */
export function getUsageNumber(usage: Record<string, unknown>, key: string): number | undefined {
  const value = usage[key];
  if (typeof value === 'number' && Number.isFinite(value)) {
    return value;
  }
  if (typeof value === 'string' && value.trim() !== '') {
    const numericValue = Number(value);
    if (Number.isFinite(numericValue)) {
      return numericValue;
    }
  }
  return undefined;
}

/**
 * Normalize a step's usage payload. Returns undefined when no primary count is
 * present so an absent measurement is never reported as a measured zero.
 */
export function toStepTokenUsage(usage: unknown): TokenUsage | undefined {
  if (typeof usage !== 'object' || usage === null || Array.isArray(usage)) return undefined;
  const record = usage as Record<string, unknown>;
  const rawPrompt = getUsageNumber(record, 'promptTokens') ?? getUsageNumber(record, 'inputTokens');
  const rawCompletion = getUsageNumber(record, 'completionTokens') ?? getUsageNumber(record, 'outputTokens');
  const rawTotal = getUsageNumber(record, 'totalTokens');
  if (rawPrompt === undefined && rawCompletion === undefined && rawTotal === undefined) return undefined;
  const promptTokens = rawPrompt ?? 0;
  const completionTokens = rawCompletion ?? 0;
  const stepUsage: TokenUsage = {
    promptTokens,
    completionTokens,
    totalTokens: rawTotal ?? promptTokens + completionTokens,
  };
  for (const key of OPTIONAL_USAGE_FIELDS) addOptionalUsageField(stepUsage, key, getUsageNumber(record, key));
  if (record.raw !== undefined) stepUsage.raw = record.raw;
  return stepUsage;
}

/** Return a new tally with one step's usage folded in. */
export function addTokenUsage(total: TokenUsage, step: TokenUsage): TokenUsage {
  const next: TokenUsage = {
    ...total,
    promptTokens: total.promptTokens + step.promptTokens,
    completionTokens: total.completionTokens + step.completionTokens,
    totalTokens: total.totalTokens + step.totalTokens,
  };
  for (const key of OPTIONAL_USAGE_FIELDS) addOptionalUsageField(next, key, step[key]);
  if (step.raw !== undefined) next.raw = step.raw;
  return next;
}

const OPTIONAL_USAGE_FIELDS = [
  'reasoningTokens',
  'cachedInputTokens',
  'cacheCreationInputTokens',
  'cacheCreationInputTokens5m',
  'cacheCreationInputTokens1h',
] as const;

/** Fold an optional usage field into a tally when present. */
export function addOptionalUsageField(
  usage: TokenUsage,
  key: keyof Pick<
    TokenUsage,
    | 'reasoningTokens'
    | 'cachedInputTokens'
    | 'cacheCreationInputTokens'
    | 'cacheCreationInputTokens5m'
    | 'cacheCreationInputTokens1h'
  >,
  value: number | undefined,
): void {
  if (value !== undefined) {
    usage[key] = (usage[key] ?? 0) + value;
  }
}
