import { Agent } from '@mastra/core/agent';
import { Harness } from '@mastra/core/harness';
import { InMemoryStore } from '@mastra/core/storage';
import { Workspace, LocalFilesystem, LocalSandbox, createWorkspaceTools } from '@mastra/core/workspace';
import { createRequire } from 'node:module';
import { mkdtempSync } from 'node:fs'; import { tmpdir } from 'node:os'; import { join } from 'node:path';
import { startAimock } from './aimock.ts';
const req = createRequire(new URL(import.meta.url));
const reqMc = createRequire(req.resolve('../../../mastracode/package.json'));
const { createOpenAI } = reqMc('@ai-sdk/openai');
const aimock = await startAimock('tool-approval.json');
const openai = createOpenAI({ apiKey:'k', baseURL: aimock.baseUrl });
const root = mkdtempSync(join(tmpdir(),'chk-'));
const ws = new Workspace({ id:'w', name:'w', filesystem:new LocalFilesystem({basePath:root,allowedPaths:[root]}), sandbox:new LocalSandbox({workingDirectory:root}) });
const tools = await createWorkspaceTools(ws);
const agent = new Agent({ id:'code-agent', name:'code-agent', instructions:'x', model: openai('gpt-5.4-mini'), tools });
const harness = new Harness({ id:'code', storage:new InMemoryStore(), workspace:ws, initialState:{yolo:false}, modes:[{id:'build',name:'B',default:true,agent}], defaultModeId:'build' });
await harness.init();
const session = await harness.createSession({ resourceId:'r' });
let approval;
session.subscribe(e => { if(e.type==='tool_approval_required')approval=e; });
await session.sendMessage({ content:'Write notes.txt with the text draft' });
await new Promise(r=>setTimeout(r,2500));
console.log('stream.isOpen=', session.stream.isOpen(), 'isActive=', session.stream.isActive(), 'activeRunId=', session.stream.activeRunId());
process.exit(0);
