version: '3.8'

services:
  duckdb:
    image: duckdb/duckdb:latest
    container_name: mastra-duckdb
    command: |
      sh -c "
        duckdb /data/mastra.duckdb <<EOF
        -- Install and load VSS extension
        INSTALL vss;
        LOAD vss;

        -- Create embeddings table if not exists
        CREATE TABLE IF NOT EXISTS embeddings (
          id VARCHAR PRIMARY KEY,
          embedding FLOAT[],
          content TEXT,
          metadata JSON,
          created_at TIMESTAMP DEFAULT current_timestamp,
          updated_at TIMESTAMP DEFAULT current_timestamp
        );

        -- Create HNSW index for similarity search
        CREATE INDEX IF NOT EXISTS idx_embeddings_hnsw
        ON embeddings
        USING HNSW (embedding)
        WITH (metric = 'cosine', ef_construction = 128, M = 16);

        -- Keep container running
        .timer 30000
        SELECT 'DuckDB ready for vector operations' as status;
        EOF
        tail -f /dev/null
      "
    volumes:
      - duckdb-data:/data
    ports:
      - "5433:5432"  # Different port to avoid conflict with PostgreSQL
    environment:
      - DUCKDB_MEMORY_LIMIT=2GB
      - DUCKDB_THREADS=4
    healthcheck:
      test: ["CMD", "duckdb", "/data/mastra.duckdb", "-c", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mastra-network

volumes:
  duckdb-data:
    driver: local

networks:
  mastra-network:
    driver: bridge