services:
  db:
    image: postgres:13
    container_name: email_client_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-arkwright}
    volumes:
      - ./db:/var/lib/postgresql/data

  inngest:
    build:
      context: ./inngest
      dockerfile: Dockerfile
    container_name: email_client_inngest
    image: inngest:latest
    ports:
      - '8288:8288'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command:
      - '--no-discovery'
      - '-u'
      - ${INNGEST_SERVE_URL:-http://host.docker.internal:3000/api/integrations/inngest}
