services:
  db:
    image: postgres:13
    container_name: 'email-client-db'
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-kepler}
    volumes:
      - pgdata:/var/lib/postgresql/data

  inngest:
    build:
      context: ./inngest
      dockerfile: Dockerfile
    container_name: 'email-client-inngest'
    image: inngest:latest
    ports:
      - '8288:8288'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    command:
      - '--no-discovery'
      - '-u'
      - ${INNGEST_SERVE_URL:-http://host.docker.internal:3456/api/kpl/inngest}

volumes:
  pgdata:
