# This file makes agent-hub a standalone workspace
packages:
  - .

minimumReleaseAgeExclude:
  - fastify@5.12.4
  - protobufjs@7.6.6
  - '@opentelemetry/propagator-jaeger@2.11.0'
  - systeminformation@5.33.10
  - nanoid@3.3.19

overrides:
  '@mastra/core': link:../../../../packages/core
  '@mastra/libsql': link:../../../../stores/libsql
  '@mastra/observability': link:../../../mastra
  '@mastra/otel-bridge': link:../../../otel-bridge
  '@mastra/server': link:../../../../packages/server
  systeminformation: 5.33.10
  protobufjs@>=7.0.0 <7.6.5: 7.6.6
  '@opentelemetry/propagator-jaeger@<2.9.0': 2.11.0
  nanoid@>=3.0.0 <3.3.19: 3.3.19
  ajv@<=8.18.0: 8.18.0
  fast-uri@<3.1.7: 3.1.7
  minimatch@<=10.2.1: 10.2.1
  '@isaacs/brace-expansion@<=5.0.1': 5.0.1
  brace-expansion@>=4.0.0 <5.0.9: 5.0.9

allowBuilds:
  esbuild: false
  protobufjs: false
