import type { AuditEvent } from '../../../ee/interfaces/audit.js';

/**
 * Audit event record stored in database
 *
 * Extends AuditEvent with additional fields for storage and indexing.
 */
export interface AuditEventRecord extends AuditEvent {
  /**
   * Unique identifier for the audit event (generated by storage)
   */
  id: string;

  /**
   * Timestamp when the event occurred (generated by storage)
   */
  timestamp: Date;
}
