import type { AnySpan, ObservabilityExporter, TracingEvent } from '@mastra/core/observability';
import { SpanType } from '@mastra/core/observability';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { DefaultObservabilityInstance } from '../instances';
import { SensitiveDataFilter } from './sensitive-data-filter';

afterEach(() => {
  vi.restoreAllMocks();
});

describe('SensitiveDataFilter JSON candidates', () => {
  it.each([
    '[MaxDepth]',
    '[Circular]',
    '[Circular Reference]',
    '[Function]',
    '[Symbol(example)]',
    '[REDACTED]',
    '[TOKEN_1]',
    ' \n[MaxDepth]\t',
    '{not JSON}',
    '[undefined]',
    '{',
    '[',
  ])('preserves %j without attempting JSON.parse', value => {
    const span = {
      traceId: 'synthetic-trace',
      attributes: { value },
      metadata: { value },
      input: { value },
      output: [value],
      errorInfo: { message: value },
      requestContext: { value },
    } as unknown as AnySpan;
    const parse = vi.spyOn(JSON, 'parse');

    const result = new SensitiveDataFilter().process(span);
    const calls = parse.mock.calls.length;
    parse.mockRestore();

    expect(calls).toBe(0);
    expect(result.input).toEqual({ value });
    expect(result.output).toEqual([value]);
    expect(result.attributes).toEqual({ value });
    expect(result.metadata).toEqual({ value });
    expect(result.errorInfo).toEqual({ message: value });
    expect(result.requestContext).toEqual({ value });
  });

  it.each(['"text"', '{}', '[]', 'true', 'false', 'null', '-1', ...'0123456789'])(
    'still redacts an array whose first element is %s',
    first => {
      const input = ` \n[ \t${first}, {"password":"synthetic-secret"}]\r `;
      const result = new SensitiveDataFilter().process({ input } as AnySpan);

      expect(JSON.parse(result.input as string)).toEqual([JSON.parse(first), { password: '[REDACTED]' }]);
    },
  );

  it.each(['full', 'partial', 'indexed'] as const)('preserves nested JSON redaction with %s style', redactionStyle => {
    const input = JSON.stringify({ payload: JSON.stringify({ password: 'synthetic-secret' }) });
    const result = new SensitiveDataFilter({ redactionStyle }).process({
      traceId: 'synthetic-trace',
      input,
    } as AnySpan);
    const expected = { full: '[REDACTED]', partial: 'syn…ret', indexed: '[PASSWORD_1]' }[redactionStyle];

    expect(JSON.parse(JSON.parse(result.input as string).payload)).toEqual({ password: expected });
  });

  it.each([' \n{\t}\r ', ' \n[\t]\r '])('still parses the empty container %j', input => {
    const result = new SensitiveDataFilter().process({ input } as AnySpan);
    expect(result.input).toBe(JSON.stringify(JSON.parse(input)));
  });

  it.each(['{"password":', '[true,', '[{"password":"synthetic-secret"},]'])(
    'preserves malformed JSON with a plausible prefix: %j',
    input => {
      const result = new SensitiveDataFilter().process({ input } as AnySpan);
      expect(result.input).toBe(input);
    },
  );

  it('does not parse depth markers generated by real span serialization', async () => {
    const events: TracingEvent[] = [];
    const exporter: ObservabilityExporter = {
      name: 'synthetic-exporter',
      async exportTracingEvent(event) {
        events.push(event);
      },
      async flush() {},
      async shutdown() {},
    };
    const tracing = new DefaultObservabilityInstance({
      name: 'synthetic-instance',
      serviceName: 'synthetic-service',
      serializationOptions: { maxDepth: 5 },
      exporters: [exporter],
      spanOutputProcessors: [new SensitiveDataFilter()],
    });
    const input = {
      password: 'synthetic-secret',
      rows: Array.from({ length: 50 }, () => ({ a: { b: { c: { d: { value: 'synthetic' } } } } })),
    };
    const originalInput = structuredClone(input);
    const parse = vi.spyOn(JSON, 'parse');

    try {
      const span = tracing.startSpan({ name: 'synthetic-span', type: SpanType.AGENT_RUN, input });
      span.end({ output: input });
      await tracing.flush();
      const markerCalls = parse.mock.calls.filter(([value]) => value === '[MaxDepth]').length;
      parse.mockRestore();

      expect(events).toHaveLength(2);
      expect(JSON.stringify(events[0].exportedSpan.input)).toContain('[MaxDepth]');
      expect(markerCalls).toBe(0);
      for (const event of events) {
        expect(event.exportedSpan.input.password).toBe('[REDACTED]');
      }
      expect(events[1].exportedSpan.output.password).toBe('[REDACTED]');
      expect(input).toEqual(originalInput);
    } finally {
      parse.mockRestore();
      await tracing.shutdown();
    }
  });
});
