import { compile } from 'json-schema-to-typescript';
import type { JSONSchema } from 'json-schema-to-typescript';

import type { SerializableMCPToolCatalog } from './types';

/**
 * Options for {@link generateToolTypes}.
 */
export interface GenerateToolTypesOptions {
  /**
   * Banner comment placed at the top of the generated file.
   * Defaults to a "generated, do not edit" notice listing the discovered servers.
   */
  banner?: string;
}

/**
 * Converts an arbitrary server/tool name into a valid PascalCase TypeScript identifier.
 * Splits on any non-alphanumeric character and uppercases each segment's first letter.
 * A leading digit is prefixed with an underscore so the result is always a legal identifier.
 */
function pascalCase(name: string): string {
  const joined = name
    .split(/[^a-zA-Z0-9]+/u)
    .filter(Boolean)
    // Capitalize the first letter and any letter following a digit, matching the identifier
    // normalization json-schema-to-typescript applies to root type names, so the names we
    // reference in the aggregate interface are exactly the names it emits.
    .map(segment => segment.replace(/(^|[0-9])([a-z])/gu, (_, prefix: string, letter: string) => prefix + letter.toUpperCase()))
    .join('');
  if (joined.length === 0) return '_';
  return /^[0-9]/u.test(joined) ? `_${joined}` : joined;
}

function isCompilableSchema(schema: unknown): schema is JSONSchema {
  return typeof schema === 'object' && schema !== null && !Array.isArray(schema);
}

async function compileSchema(schema: unknown, typeName: string): Promise<string> {
  if (!isCompilableSchema(schema)) {
    return `export type ${typeName} = unknown;\n`;
  }
  try {
    // Clone: json-schema-to-typescript mutates its input while resolving refs.
    const cloned = JSON.parse(JSON.stringify(schema)) as JSONSchema;
    return await compile(cloned, typeName, {
      bannerComment: '',
      additionalProperties: false,
      format: false,
    });
  } catch {
    return `/** Schema for ${typeName} could not be converted; falling back to unknown. */\nexport type ${typeName} = unknown;\n`;
  }
}

/**
 * Generates TypeScript source code describing every tool in a serializable MCP tool catalog.
 *
 * For each tool this emits `<Server><Tool>Input` and `<Server><Tool>Output` types compiled from
 * the JSON Schemas the server advertised (`unknown` when the server declared no output schema),
 * plus two aggregates:
 *
 * - `MCPToolTypes` — an interface keyed by server name, then tool name, mapping each tool to its
 *   `{ input, output }` types.
 * - `MCPToolName` — a union of namespaced `serverName_toolName` strings, matching the naming that
 *   `MCPClient.getTools()` uses.
 *
 * The catalog is the shape returned by `MCPClient.listToolDefinitions()`, so the output can be
 * produced at build time (for example by `mastra mcp typegen`) and checked into the project.
 * Generated types are compile-time contracts only — servers remain the source of truth at
 * runtime and inputs are still validated against the live schemas.
 */
export async function generateToolTypes(
  catalog: SerializableMCPToolCatalog,
  options?: GenerateToolTypesOptions,
): Promise<string> {
  const serverNames = Object.keys(catalog).sort();

  const bannerLines =
    options?.banner ??
    [
      '/* eslint-disable */',
      '/**',
      ' * Generated by `mastra mcp typegen`. Do not edit.',
      ' *',
      ' * Servers:',
      ...serverNames.map(serverName => {
        const tools = Object.values(catalog[serverName] ?? {});
        const version = tools.find(tool => tool.server.version)?.server.version;
        return ` *   - ${serverName}${version ? ` (v${version})` : ''}`;
      }),
      ' */',
    ].join('\n');

  const sections: string[] = [bannerLines];
  const aggregateEntries: string[] = [];
  const toolNameUnion: string[] = [];

  for (const serverName of serverNames) {
    const tools = catalog[serverName] ?? {};
    const toolNames = Object.keys(tools).sort();
    const toolEntries: string[] = [];

    for (const toolName of toolNames) {
      const definition = tools[toolName]!;
      const baseName = `${pascalCase(serverName)}${pascalCase(toolName)}`;
      const inputName = `${baseName}Input`;
      const outputName = `${baseName}Output`;

      if (definition.description) {
        sections.push(`/** ${definition.description.replace(/\*\//gu, '*\\/')} */`);
      }
      sections.push((await compileSchema(definition.inputSchema, inputName)).trimEnd());
      if (definition.outputSchema !== undefined) {
        sections.push((await compileSchema(definition.outputSchema, outputName)).trimEnd());
      } else {
        sections.push(`export type ${outputName} = unknown;`);
      }

      toolEntries.push(`    ${JSON.stringify(toolName)}: { input: ${inputName}; output: ${outputName} };`);
      toolNameUnion.push(JSON.stringify(`${serverName}_${toolName}`));
    }

    aggregateEntries.push(`  ${JSON.stringify(serverName)}: {\n${toolEntries.join('\n')}\n  };`);
  }

  sections.push(
    `/** Input/output contracts for every discovered MCP tool, keyed by server then tool name. */\nexport interface MCPToolTypes {\n${aggregateEntries.join('\n')}\n}`,
  );
  sections.push(
    `/** Namespaced tool names as returned by \`MCPClient.getTools()\`. */\nexport type MCPToolName = ${
      toolNameUnion.length > 0 ? toolNameUnion.join(' | ') : 'never'
    };`,
  );

  return `${sections.join('\n\n')}\n`;
}
