import * as ts from 'typescript';
import { describe, expect, it } from 'vitest';

import { generateToolTypes } from './typegen';
import type { SerializableMCPToolCatalog } from './types';

function makeDefinition(overrides: {
  name: string;
  serverName: string;
  inputSchema?: unknown;
  outputSchema?: unknown;
  description?: string;
  version?: string;
}) {
  return {
    name: overrides.name,
    description: overrides.description,
    inputSchema: overrides.inputSchema ?? { type: 'object', properties: {}, additionalProperties: false },
    outputSchema: overrides.outputSchema,
    server: { name: overrides.serverName, version: overrides.version },
  };
}

const catalog: SerializableMCPToolCatalog = {
  weather: {
    getForecast: makeDefinition({
      name: 'getForecast',
      serverName: 'weather',
      description: 'Get the forecast for a city',
      version: '1.2.3',
      inputSchema: {
        type: 'object',
        properties: { city: { type: 'string' }, days: { type: 'number' } },
        required: ['city'],
        additionalProperties: false,
      },
      outputSchema: {
        type: 'object',
        properties: { summary: { type: 'string' } },
        required: ['summary'],
        additionalProperties: false,
      },
    }),
  },
  stocks: {
    getPrice: makeDefinition({
      name: 'getPrice',
      serverName: 'stocks',
      inputSchema: {
        type: 'object',
        properties: { ticker: { type: 'string' } },
        required: ['ticker'],
        additionalProperties: false,
      },
    }),
  },
};

function compileCheck(source: string): string[] {
  const fileName = 'generated.ts';
  const sourceFile = ts.createSourceFile(fileName, source, ts.ScriptTarget.ES2022, true);
  const options: ts.CompilerOptions = { strict: true, noEmit: true, skipLibCheck: true };
  const host = ts.createCompilerHost(options);
  const originalGetSourceFile = host.getSourceFile.bind(host);
  host.getSourceFile = (name, languageVersion, ...rest) =>
    name === fileName ? sourceFile : originalGetSourceFile(name, languageVersion, ...rest);
  const program = ts.createProgram([fileName], options, host);
  return ts.getPreEmitDiagnostics(program).map(d => ts.flattenDiagnosticMessageText(d.messageText, '\n'));
}

describe('generateToolTypes', () => {
  it('generates named input/output types for a multi-server catalog', async () => {
    const source = await generateToolTypes(catalog);

    expect(source).toContain('export interface WeatherGetForecastInput');
    expect(source).toContain('export interface WeatherGetForecastOutput');
    expect(source).toContain('export interface StocksGetPriceInput');
    // No outputSchema declared -> unknown
    expect(source).toContain('export type StocksGetPriceOutput = unknown;');
    // Aggregate interface with literal keys
    expect(source).toContain('export interface MCPToolTypes');
    expect(source).toContain('"weather"');
    expect(source).toContain('"getForecast": { input: WeatherGetForecastInput; output: WeatherGetForecastOutput };');
    // Namespaced tool-name union matching getTools() naming
    expect(source).toContain('export type MCPToolName = "stocks_getPrice" | "weather_getForecast";');
    // Banner
    expect(source).toContain('Generated by `mastra mcp typegen`');
    expect(source).toContain('weather (v1.2.3)');
  });

  it('includes tool descriptions as doc comments', async () => {
    const source = await generateToolTypes(catalog);
    expect(source).toContain('/** Get the forecast for a city */');
  });

  it('sanitizes non-identifier server and tool names while quoting catalog keys', async () => {
    const source = await generateToolTypes({
      'my-server.v2': {
        '1st-tool': makeDefinition({
          name: '1st-tool',
          serverName: 'my-server.v2',
          inputSchema: { type: 'object', properties: { a: { type: 'string' } }, additionalProperties: false },
        }),
      },
    });

    expect(source).toContain('export interface MyServerV2_1StToolInput');
    expect(source).toContain('"my-server.v2"');
    expect(source).toContain('"1st-tool"');
    expect(source).toContain('export type MCPToolName = "my-server.v2_1st-tool";');
    expect(compileCheck(source)).toEqual([]);
  });

  it('falls back to unknown for uncompilable schemas', async () => {
    const source = await generateToolTypes({
      srv: {
        weird: makeDefinition({ name: 'weird', serverName: 'srv', inputSchema: 'not-a-schema' }),
      },
    });

    expect(source).toContain('export type SrvWeirdInput = unknown;');
  });

  it('produces an empty catalog with a never union', async () => {
    const source = await generateToolTypes({});
    expect(source).toContain('export type MCPToolName = never;');
    expect(compileCheck(source)).toEqual([]);
  });

  it('generates source that compiles under strict TypeScript', async () => {
    const source = await generateToolTypes(catalog);
    expect(compileCheck(source)).toEqual([]);
  });

  it('respects a custom banner', async () => {
    const source = await generateToolTypes({}, { banner: '// custom banner' });
    expect(source.startsWith('// custom banner')).toBe(true);
    expect(source).not.toContain('Do not edit');
  });
});
