overrides:
  '@mastra/core': link:../../core
  '@mastra/agent-builder': link:../../agent-builder
  '@mastra/libsql': link:../../../stores/libsql
  '@mastra/mcp': link:../../mcp
  mastra: link:../../cli
