packages:
  - '.'

overrides:
  '@mastra/core': link:../../core
  '@mastra/agent': link:../../agent
  '@mastra/memory': link:../../memory
  '@mastra/tools': link:../../tools
  '@mastra/rag': link:../../rag
  '@mastra/voice': link:../../voice
  mastra: link:../../cli
  '@internal/test-utils': link:../../_test-utils
  '@internal/llm-recorder': link:../../_llm-recorder

allowBuilds:
  esbuild: false
  sharp: false
