import {
  getAgentCardByIdHandler,
  handleMessageSend,
  handleTaskGet,
  handleMessageStream,
  handleTaskCancel,
  getAgentExecutionHandler,
} from '../../handlers/a2a';
import {
  a2aAgentIdPathParams,
  a2aTaskPathParams,
  messageSendBodySchema,
  taskQueryBodySchema,
  agentExecutionBodySchema,
  agentCardResponseSchema,
  taskResponseSchema,
  agentExecutionResponseSchema,
} from '../../schemas/a2a';
import { createRoute } from './route-builder';
import type { ServerRoute, ServerRouteHandler } from '.';

export const A2A_ROUTES: ServerRoute[] = [
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getAgentCardByIdHandler as unknown as ServerRouteHandler,
    path: '/a2a/:agentId/card',
    pathParamSchema: a2aAgentIdPathParams,
    responseSchema: agentCardResponseSchema,
    summary: 'Get agent card',
    description: 'Returns the agent card information for A2A protocol discovery',
    tags: ['Agent-to-Agent'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: handleMessageSend as unknown as ServerRouteHandler,
    path: '/a2a/:agentId/message/send',
    pathParamSchema: a2aAgentIdPathParams,
    bodySchema: messageSendBodySchema,
    responseSchema: taskResponseSchema,
    summary: 'Send message',
    description: 'Sends a message to an agent via A2A protocol',
    tags: ['Agent-to-Agent'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: handleTaskGet as unknown as ServerRouteHandler,
    path: '/a2a/:agentId/tasks/:taskId',
    pathParamSchema: a2aTaskPathParams,
    responseSchema: taskResponseSchema,
    summary: 'Get task status',
    description: 'Returns the current status of an A2A task',
    tags: ['Agent-to-Agent'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'stream',
    handler: handleMessageStream as unknown as ServerRouteHandler,
    path: '/a2a/:agentId/message/stream',
    pathParamSchema: a2aAgentIdPathParams,
    bodySchema: messageSendBodySchema,
    summary: 'Stream message',
    description: 'Sends a message and streams the response via A2A protocol',
    tags: ['Agent-to-Agent'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: handleTaskCancel as unknown as ServerRouteHandler,
    path: '/a2a/:agentId/tasks/:taskId/cancel',
    pathParamSchema: a2aTaskPathParams,
    responseSchema: taskResponseSchema,
    summary: 'Cancel task',
    description: 'Cancels an in-progress A2A task',
    tags: ['Agent-to-Agent'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: getAgentExecutionHandler as unknown as ServerRouteHandler,
    path: '/a2a/:agentId/execute',
    pathParamSchema: a2aAgentIdPathParams,
    bodySchema: agentExecutionBodySchema,
    responseSchema: agentExecutionResponseSchema,
    summary: 'Execute agent',
    description: 'Executes an agent action via JSON-RPC 2.0 over A2A protocol',
    tags: ['Agent-to-Agent'],
  }),
];
