import {
  approveToolCallHandler,
  declineToolCallHandler,
  generateHandler,
  getAgentByIdHandler,
  getProvidersHandler,
  listAgentsHandler,
  reorderAgentModelListHandler,
  resetAgentModelHandler,
  streamGenerateHandler,
  streamNetworkHandler,
  updateAgentModelHandler,
  updateAgentModelInModelListHandler,
} from '../../handlers/agents';
import { executeAgentToolHandler, getAgentToolHandler } from '../../handlers/tools';
import {
  getSpeakersHandler,
  generateSpeechHandler,
  transcribeSpeechHandler,
  getListenerHandler,
} from '../../handlers/voice';
import {
  agentExecutionBodySchema,
  agentIdPathParams,
  agentToolPathParams,
  approveToolCallBodySchema,
  declineToolCallBodySchema,
  executeToolBodySchema,
  listAgentsResponseSchema,
  modelConfigIdPathParams,
  modelManagementResponseSchema,
  providersResponseSchema,
  reorderAgentModelListBodySchema,
  serializedAgentSchema,
  serializedToolSchema,
  toolCallResponseSchema,
  updateAgentModelBodySchema,
  updateAgentModelInModelListBodySchema,
  voiceSpeakersResponseSchema,
  generateSpeechBodySchema,
  transcribeSpeechBodySchema,
  transcribeSpeechResponseSchema,
  getListenerResponseSchema,
} from '../../schemas/agents';
import { createRoute } from './route-builder';
import type { ServerRoute, ServerRouteHandler } from '.';

export const AGENTS_ROUTES: ServerRoute[] = [
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: listAgentsHandler as unknown as ServerRouteHandler,
    path: '/api/agents',
    responseSchema: listAgentsResponseSchema,
    summary: 'List all agents',
    description: 'Returns a list of all available agents in the system',
    tags: ['Agents'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getProvidersHandler as unknown as ServerRouteHandler,
    path: '/api/agents/providers',
    responseSchema: providersResponseSchema,
    summary: 'List AI providers',
    description: 'Returns a list of all configured AI model providers',
    tags: ['Agents'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getAgentByIdHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId',
    pathParamSchema: agentIdPathParams,
    responseSchema: serializedAgentSchema,
    summary: 'Get agent by ID',
    description: 'Returns details for a specific agent including configuration, tools, and memory settings',
    tags: ['Agents'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getSpeakersHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId/voice/speakers',
    pathParamSchema: agentIdPathParams,
    responseSchema: voiceSpeakersResponseSchema,
    summary: 'Get voice speakers',
    description: 'Returns available voice speakers for the specified agent',
    tags: ['Agents', 'Voice'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: generateHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId/generate',
    pathParamSchema: agentIdPathParams,
    bodySchema: agentExecutionBodySchema,
    summary: 'Generate agent response',
    description: 'Executes an agent with the provided messages and returns the complete response',
    tags: ['Agents'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'stream',
    handler: streamGenerateHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId/stream',
    pathParamSchema: agentIdPathParams,
    bodySchema: agentExecutionBodySchema,
    summary: 'Stream agent response',
    description: 'Executes an agent with the provided messages and streams the response in real-time',
    tags: ['Agents'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: executeAgentToolHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId/tools/:toolId/execute',
    pathParamSchema: agentToolPathParams,
    bodySchema: executeToolBodySchema,
    summary: 'Execute agent tool',
    description: 'Executes a specific tool assigned to the agent with the provided input data',
    tags: ['Agents', 'Tools'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'stream',
    handler: approveToolCallHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId/approve-tool-call',
    pathParamSchema: agentIdPathParams,
    bodySchema: approveToolCallBodySchema,
    responseSchema: toolCallResponseSchema,
    summary: 'Approve tool call',
    description: 'Approves a pending tool call and continues agent execution',
    tags: ['Agents', 'Tools'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'stream',
    handler: declineToolCallHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId/decline-tool-call',
    pathParamSchema: agentIdPathParams,
    bodySchema: declineToolCallBodySchema,
    responseSchema: toolCallResponseSchema,
    summary: 'Decline tool call',
    description: 'Declines a pending tool call and continues agent execution without executing the tool',
    tags: ['Agents', 'Tools'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'stream',
    handler: streamNetworkHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId/network',
    pathParamSchema: agentIdPathParams,
    bodySchema: agentExecutionBodySchema,
    summary: 'Stream agent network',
    description: 'Executes an agent network with multiple agents and streams the response',
    tags: ['Agents'],
  }),
  createRoute({
    method: 'PUT',
    responseType: 'json',
    handler: updateAgentModelHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId/model',
    pathParamSchema: agentIdPathParams,
    bodySchema: updateAgentModelBodySchema,
    responseSchema: modelManagementResponseSchema,
    summary: 'Update agent model',
    description: 'Updates the AI model used by the agent',
    tags: ['Agents', 'Models'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: resetAgentModelHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId/model/reset',
    pathParamSchema: agentIdPathParams,
    responseSchema: modelManagementResponseSchema,
    summary: 'Reset agent model',
    description: 'Resets the agent model to its original configuration',
    tags: ['Agents', 'Models'],
  }),
  createRoute({
    method: 'PUT',
    responseType: 'json',
    handler: reorderAgentModelListHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId/models/reorder',
    pathParamSchema: agentIdPathParams,
    bodySchema: reorderAgentModelListBodySchema,
    responseSchema: modelManagementResponseSchema,
    summary: 'Reorder agent model list',
    description: 'Reorders the model list for agents with multiple model configurations',
    tags: ['Agents', 'Models'],
  }),
  createRoute({
    method: 'PUT',
    responseType: 'json',
    handler: updateAgentModelInModelListHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId/models/:modelConfigId',
    pathParamSchema: modelConfigIdPathParams,
    bodySchema: updateAgentModelInModelListBodySchema,
    responseSchema: modelManagementResponseSchema,
    summary: 'Update model in model list',
    description: 'Updates a specific model configuration in the agent model list',
    tags: ['Agents', 'Models'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getAgentToolHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId/tools/:toolId',
    pathParamSchema: agentToolPathParams,
    responseSchema: serializedToolSchema,
    summary: 'Get agent tool',
    description: 'Returns details for a specific tool assigned to the agent',
    tags: ['Agents', 'Tools'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'stream',
    handler: generateSpeechHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId/voice/speak',
    pathParamSchema: agentIdPathParams,
    bodySchema: generateSpeechBodySchema,
    summary: 'Generate speech',
    description: 'Generates speech audio from text using the agent voice configuration',
    tags: ['Agents', 'Voice'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: transcribeSpeechHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId/voice/transcribe',
    pathParamSchema: agentIdPathParams,
    bodySchema: transcribeSpeechBodySchema,
    responseSchema: transcribeSpeechResponseSchema,
    summary: 'Transcribe speech',
    description: 'Transcribes speech audio to text using the agent voice configuration',
    tags: ['Agents', 'Voice'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getListenerHandler as unknown as ServerRouteHandler,
    path: '/api/agents/:agentId/voice/listener',
    pathParamSchema: agentIdPathParams,
    responseSchema: getListenerResponseSchema,
    summary: 'Get voice listener',
    description: 'Returns the voice listener configuration for the agent',
    tags: ['Agents', 'Voice'],
  }),
];
