import {
  getAgentBuilderActionsHandler,
  getAgentBuilderActionByIdHandler,
  getAgentBuilderActionRunsHandler,
  getAgentBuilderActionRunByIdHandler,
  getAgentBuilderActionRunExecutionResultHandler,
  createAgentBuilderActionRunHandler,
  streamAgentBuilderActionHandler,
  streamVNextAgentBuilderActionHandler,
  startAsyncAgentBuilderActionHandler,
  startAgentBuilderActionRunHandler,
  observeStreamAgentBuilderActionHandler,
  observeStreamVNextAgentBuilderActionHandler,
  resumeAsyncAgentBuilderActionHandler,
  resumeAgentBuilderActionHandler,
  resumeStreamAgentBuilderActionHandler,
  cancelAgentBuilderActionRunHandler,
} from '../../handlers/agent-builder';
import {
  actionIdPathParams,
  actionRunPathParams,
  listWorkflowRunsQuerySchema,
  optionalRunIdQuerySchema,
  resumeBodySchema,
  runIdQuerySchema,
  streamWorkflowBodySchema,
  startAsyncWorkflowBodySchema,
  workflowExecutionResultSchema,
  workflowControlResponseSchema,
  workflowRunResponseSchema,
  workflowRunsResponseSchema,
  workflowInfoSchema,
  listWorkflowsResponseSchema,
} from '../../schemas/agent-builder';
import { createRoute } from './route-builder';
import type { ServerRoute, ServerRouteHandler } from '.';

export const AGENT_BUILDER_ROUTES: ServerRoute[] = [
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getAgentBuilderActionsHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions',
    responseSchema: listWorkflowsResponseSchema,
    summary: 'List agent-builder actions',
    description: 'Returns a list of all available agent-builder actions',
    tags: ['Agent Builder'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getAgentBuilderActionByIdHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions/:actionId',
    pathParamSchema: actionIdPathParams,
    responseSchema: workflowInfoSchema,
    summary: 'Get action by ID',
    description: 'Returns details for a specific agent-builder action',
    tags: ['Agent Builder'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getAgentBuilderActionRunsHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions/:actionId/runs',
    pathParamSchema: actionIdPathParams,
    queryParamSchema: listWorkflowRunsQuerySchema,
    responseSchema: workflowRunsResponseSchema,
    summary: 'List action runs',
    description: 'Returns a paginated list of execution runs for the specified action',
    tags: ['Agent Builder'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getAgentBuilderActionRunByIdHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions/:actionId/runs/:runId',
    pathParamSchema: actionRunPathParams,
    responseSchema: workflowRunResponseSchema,
    summary: 'Get action run by ID',
    description: 'Returns details for a specific action run',
    tags: ['Agent Builder'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getAgentBuilderActionRunExecutionResultHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions/:actionId/runs/:runId/execution-result',
    pathParamSchema: actionRunPathParams,
    responseSchema: workflowExecutionResultSchema,
    summary: 'Get action execution result',
    description: 'Returns the final execution result of a completed action run',
    tags: ['Agent Builder'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: createAgentBuilderActionRunHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions/:actionId/create-run',
    pathParamSchema: actionIdPathParams,
    queryParamSchema: optionalRunIdQuerySchema,
    summary: 'Create action run',
    description: 'Creates a new action execution instance with an optional custom run ID',
    tags: ['Agent Builder'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'stream',
    handler: streamAgentBuilderActionHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions/:actionId/stream',
    pathParamSchema: actionIdPathParams,
    queryParamSchema: runIdQuerySchema,
    bodySchema: streamWorkflowBodySchema,
    summary: 'Stream action execution',
    description: 'Executes an action and streams the results in real-time',
    tags: ['Agent Builder'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'stream',
    handler: streamVNextAgentBuilderActionHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions/:actionId/streamVNext',
    pathParamSchema: actionIdPathParams,
    queryParamSchema: runIdQuerySchema,
    bodySchema: streamWorkflowBodySchema,
    summary: 'Stream action execution (v2)',
    description: 'Executes an action using the v2 streaming API and streams the results in real-time',
    tags: ['Agent Builder'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: startAsyncAgentBuilderActionHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions/:actionId/start-async',
    pathParamSchema: actionIdPathParams,
    queryParamSchema: runIdQuerySchema,
    bodySchema: startAsyncWorkflowBodySchema,
    summary: 'Start action asynchronously',
    description: 'Starts an action execution asynchronously without streaming results',
    tags: ['Agent Builder'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: startAgentBuilderActionRunHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions/:actionId/runs/:runId/start',
    pathParamSchema: actionRunPathParams,
    bodySchema: startAsyncWorkflowBodySchema,
    summary: 'Start specific action run',
    description: 'Starts execution of a specific action run by ID',
    tags: ['Agent Builder'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'stream',
    handler: observeStreamAgentBuilderActionHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions/:actionId/runs/:runId/observe-stream',
    pathParamSchema: actionRunPathParams,
    summary: 'Observe action stream',
    description: 'Observes and streams updates from an already running action execution',
    tags: ['Agent Builder'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'stream',
    handler: observeStreamVNextAgentBuilderActionHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions/:actionId/runs/:runId/observe-stream-vnext',
    pathParamSchema: actionRunPathParams,
    summary: 'Observe action stream (v2)',
    description: 'Observes and streams updates from an already running action execution using v2 streaming API',
    tags: ['Agent Builder'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: resumeAsyncAgentBuilderActionHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions/:actionId/runs/:runId/resume-async',
    pathParamSchema: actionRunPathParams,
    bodySchema: resumeBodySchema,
    summary: 'Resume action asynchronously',
    description: 'Resumes a suspended action execution asynchronously without streaming',
    tags: ['Agent Builder'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: resumeAgentBuilderActionHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions/:actionId/runs/:runId/resume',
    pathParamSchema: actionRunPathParams,
    bodySchema: resumeBodySchema,
    summary: 'Resume action',
    description: 'Resumes a suspended action execution from a specific step',
    tags: ['Agent Builder'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'stream',
    handler: resumeStreamAgentBuilderActionHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions/:actionId/resume-stream',
    pathParamSchema: actionIdPathParams,
    queryParamSchema: runIdQuerySchema,
    bodySchema: resumeBodySchema,
    summary: 'Resume action stream',
    description: 'Resumes a suspended action execution and continues streaming results',
    tags: ['Agent Builder'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: cancelAgentBuilderActionRunHandler as unknown as ServerRouteHandler,
    path: '/api/agent-builder/actions/:actionId/runs/:runId/cancel',
    pathParamSchema: actionRunPathParams,
    responseSchema: workflowControlResponseSchema,
    summary: 'Cancel action run',
    description: 'Cancels an in-progress action execution',
    tags: ['Agent Builder'],
  }),
];
