import { CREATE_CONVERSATION_ROUTE, GET_CONVERSATION_ITEMS_ROUTE } from '../../handlers/conversations';

export const CONVERSATIONS_ROUTES = [CREATE_CONVERSATION_ROUTE, GET_CONVERSATION_ITEMS_ROUTE] as const;
