import {
  LIST_HARNESSES_ROUTE,
  CREATE_HARNESS_SESSION_ROUTE,
  STREAM_HARNESS_SESSION_ROUTE,
  SEND_HARNESS_MESSAGE_ROUTE,
  ABORT_HARNESS_SESSION_ROUTE,
  HARNESS_TOOL_APPROVAL_ROUTE,
} from '../../handlers/harness';
import type { ServerRoute } from '.';

export const HARNESS_ROUTES: readonly ServerRoute[] = [
  LIST_HARNESSES_ROUTE,
  CREATE_HARNESS_SESSION_ROUTE,
  STREAM_HARNESS_SESSION_ROUTE,
  SEND_HARNESS_MESSAGE_ROUTE,
  ABORT_HARNESS_SESSION_ROUTE,
  HARNESS_TOOL_APPROVAL_ROUTE,
];
