import type { ServerRoute } from './index';
import {
  LIST_INBOXES_ROUTE,
  LIST_TASKS_ROUTE,
  GET_TASK_ROUTE,
  LIST_WAITING_TASKS_ROUTE,
  GET_INBOX_STATS_ROUTE,
  CREATE_TASK_ROUTE,
  CREATE_TASKS_BATCH_ROUTE,
  CANCEL_TASK_ROUTE,
  RELEASE_TASK_ROUTE,
  RESUME_TASK_ROUTE,
} from '../../handlers/inbox';

export const INBOX_ROUTES: ServerRoute<any, any, any>[] = [
  LIST_INBOXES_ROUTE,
  LIST_TASKS_ROUTE,
  GET_TASK_ROUTE,
  LIST_WAITING_TASKS_ROUTE,
  GET_INBOX_STATS_ROUTE,
  CREATE_TASK_ROUTE,
  CREATE_TASKS_BATCH_ROUTE,
  CANCEL_TASK_ROUTE,
  RELEASE_TASK_ROUTE,
  RESUME_TASK_ROUTE,
];
