import {
  LIST_KNOWLEDGE_NAMESPACES_ROUTE,
  CREATE_KNOWLEDGE_NAMESPACE_ROUTE,
  DELETE_KNOWLEDGE_NAMESPACE_ROUTE,
  LIST_KNOWLEDGE_ARTIFACTS_ROUTE,
  GET_KNOWLEDGE_ARTIFACT_ROUTE,
  ADD_KNOWLEDGE_ARTIFACT_ROUTE,
  ADD_KNOWLEDGE_FILE_ARTIFACT_ROUTE,
  DELETE_KNOWLEDGE_ARTIFACT_ROUTE,
  SEARCH_KNOWLEDGE_ROUTE,
} from '../../handlers/knowledge';
import type { ServerRoute } from '.';

export const KNOWLEDGE_ROUTES: ServerRoute<any, any, any>[] = [
  LIST_KNOWLEDGE_NAMESPACES_ROUTE,
  CREATE_KNOWLEDGE_NAMESPACE_ROUTE,
  DELETE_KNOWLEDGE_NAMESPACE_ROUTE,
  LIST_KNOWLEDGE_ARTIFACTS_ROUTE,
  GET_KNOWLEDGE_ARTIFACT_ROUTE,
  ADD_KNOWLEDGE_ARTIFACT_ROUTE,
  ADD_KNOWLEDGE_FILE_ARTIFACT_ROUTE,
  DELETE_KNOWLEDGE_ARTIFACT_ROUTE,
  SEARCH_KNOWLEDGE_ROUTE,
];
