import {
  getMemoryConfigHandler,
  getMemoryStatusHandler,
  getMessagesHandler,
  getThreadByIdHandler,
  getWorkingMemoryHandler,
  listThreadsHandler,
  saveMessagesHandler,
  createThreadHandler,
  updateThreadHandler,
  deleteThreadHandler,
  listMessagesHandler,
  updateWorkingMemoryHandler,
  deleteMessagesHandler,
  searchMemoryHandler,
} from '../../handlers/memory';
import {
  getMemoryConfigQuerySchema,
  memoryConfigResponseSchema,
  getMemoryStatusQuerySchema,
  getMessagesQuerySchema,
  getMessagesResponseSchema,
  getThreadByIdQuerySchema,
  getThreadByIdResponseSchema,
  getWorkingMemoryQuerySchema,
  getWorkingMemoryResponseSchema,
  listThreadsQuerySchema,
  listThreadsResponseSchema,
  memoryStatusResponseSchema,
  threadIdPathParams,
  saveMessagesBodySchema,
  saveMessagesResponseSchema,
  createThreadBodySchema,
  updateThreadBodySchema,
  deleteThreadResponseSchema,
  listMessagesQuerySchema,
  listMessagesResponseSchema,
  updateWorkingMemoryBodySchema,
  updateWorkingMemoryResponseSchema,
  deleteMessagesQuerySchema,
  deleteMessagesResponseSchema,
  searchMemoryQuerySchema,
  searchMemoryResponseSchema,
} from '../../schemas/memory';
import { createRoute } from './route-builder';
import type { ServerRoute, ServerRouteHandler } from '.';

export const MEMORY_ROUTES: ServerRoute[] = [
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getMemoryStatusHandler as unknown as ServerRouteHandler,
    path: '/api/memory/status',
    queryParamSchema: getMemoryStatusQuerySchema,
    responseSchema: memoryStatusResponseSchema,
    summary: 'Get memory status',
    description: 'Returns the current status of the memory system including configuration and health information',
    tags: ['Memory'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getMemoryConfigHandler as unknown as ServerRouteHandler,
    path: '/api/memory/config',
    queryParamSchema: getMemoryConfigQuerySchema,
    responseSchema: memoryConfigResponseSchema,
    summary: 'Get memory configuration',
    description: 'Returns the memory configuration for a specific agent or the system default',
    tags: ['Memory'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: listThreadsHandler as unknown as ServerRouteHandler,
    path: '/api/memory/threads',
    queryParamSchema: listThreadsQuerySchema,
    responseSchema: listThreadsResponseSchema,
    summary: 'List memory threads',
    description: 'Returns a paginated list of conversation threads filtered by resource ID',
    tags: ['Memory'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getThreadByIdHandler as unknown as ServerRouteHandler,
    path: '/api/memory/threads/:threadId',
    pathParamSchema: threadIdPathParams,
    queryParamSchema: getThreadByIdQuerySchema,
    responseSchema: getThreadByIdResponseSchema,
    summary: 'Get thread by ID',
    description: 'Returns details for a specific conversation thread',
    tags: ['Memory'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getMessagesHandler as unknown as ServerRouteHandler,
    path: '/api/memory/threads/:threadId/messages',
    pathParamSchema: threadIdPathParams,
    queryParamSchema: getMessagesQuerySchema,
    responseSchema: getMessagesResponseSchema,
    summary: 'Get thread messages',
    description: 'Returns all messages in a conversation thread',
    tags: ['Memory'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getWorkingMemoryHandler as unknown as ServerRouteHandler,
    path: '/api/memory/threads/:threadId/working-memory',
    pathParamSchema: threadIdPathParams,
    queryParamSchema: getWorkingMemoryQuerySchema,
    responseSchema: getWorkingMemoryResponseSchema,
    summary: 'Get working memory',
    description: 'Returns the current working memory state for a conversation thread',
    tags: ['Memory'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: saveMessagesHandler as unknown as ServerRouteHandler,
    path: '/api/memory/messages',
    bodySchema: saveMessagesBodySchema,
    responseSchema: saveMessagesResponseSchema,
    summary: 'Save messages',
    description: 'Saves one or more messages to memory storage',
    tags: ['Memory'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: createThreadHandler as unknown as ServerRouteHandler,
    path: '/api/memory/threads',
    bodySchema: createThreadBodySchema,
    responseSchema: getThreadByIdResponseSchema,
    summary: 'Create thread',
    description: 'Creates a new conversation thread',
    tags: ['Memory'],
  }),
  createRoute({
    method: 'PUT',
    responseType: 'json',
    handler: updateThreadHandler as unknown as ServerRouteHandler,
    path: '/api/memory/threads/:threadId',
    pathParamSchema: threadIdPathParams,
    bodySchema: updateThreadBodySchema,
    responseSchema: getThreadByIdResponseSchema,
    summary: 'Update thread',
    description: 'Updates an existing conversation thread',
    tags: ['Memory'],
  }),
  createRoute({
    method: 'DELETE',
    responseType: 'json',
    handler: deleteThreadHandler as unknown as ServerRouteHandler,
    path: '/api/memory/threads/:threadId',
    pathParamSchema: threadIdPathParams,
    responseSchema: deleteThreadResponseSchema,
    summary: 'Delete thread',
    description: 'Deletes a conversation thread and all its messages',
    tags: ['Memory'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: listMessagesHandler as unknown as ServerRouteHandler,
    path: '/api/memory/messages',
    queryParamSchema: listMessagesQuerySchema,
    responseSchema: listMessagesResponseSchema,
    summary: 'List messages',
    description: 'Returns a list of messages with optional filtering and pagination',
    tags: ['Memory'],
  }),
  createRoute({
    method: 'PUT',
    responseType: 'json',
    handler: updateWorkingMemoryHandler as unknown as ServerRouteHandler,
    path: '/api/memory/threads/:threadId/working-memory',
    pathParamSchema: threadIdPathParams,
    bodySchema: updateWorkingMemoryBodySchema,
    responseSchema: updateWorkingMemoryResponseSchema,
    summary: 'Update working memory',
    description: 'Updates the working memory state for a conversation thread',
    tags: ['Memory'],
  }),
  createRoute({
    method: 'DELETE',
    responseType: 'json',
    handler: deleteMessagesHandler as unknown as ServerRouteHandler,
    path: '/api/memory/messages',
    queryParamSchema: deleteMessagesQuerySchema,
    responseSchema: deleteMessagesResponseSchema,
    summary: 'Delete messages',
    description: 'Deletes one or more messages by ID',
    tags: ['Memory'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: searchMemoryHandler as unknown as ServerRouteHandler,
    path: '/api/memory/search',
    queryParamSchema: searchMemoryQuerySchema,
    responseSchema: searchMemoryResponseSchema,
    summary: 'Search memory',
    description: 'Performs semantic or text search across conversation memory',
    tags: ['Memory'],
  }),
];
