import {
  LIST_TRACES_ROUTE,
  GET_TRACE_ROUTE,
  SCORE_TRACES_ROUTE,
  LIST_SCORES_BY_SPAN_ROUTE,
  // Logs
  LIST_LOGS_ROUTE,
  // Scores
  LIST_SCORES_ROUTE,
  CREATE_SCORE_ROUTE,
  // Feedback
  LIST_FEEDBACK_ROUTE,
  CREATE_FEEDBACK_ROUTE,
  // Metrics
  GET_METRIC_AGGREGATE_ROUTE,
  GET_METRIC_BREAKDOWN_ROUTE,
  GET_METRIC_TIME_SERIES_ROUTE,
  GET_METRIC_PERCENTILES_ROUTE,
  // Discovery
  GET_METRIC_NAMES_ROUTE,
  GET_METRIC_LABEL_KEYS_ROUTE,
  GET_METRIC_LABEL_VALUES_ROUTE,
  GET_ENTITY_TYPES_ROUTE,
  GET_ENTITY_NAMES_ROUTE,
  GET_SERVICE_NAMES_ROUTE,
  GET_ENVIRONMENTS_ROUTE,
  GET_TAGS_ROUTE,
} from '../../handlers/observability';

/** All observability server routes: traces, logs, scores, feedback, metrics, and discovery. */
export const OBSERVABILITY_ROUTES = [
  // Traces
  LIST_TRACES_ROUTE,
  GET_TRACE_ROUTE,
  SCORE_TRACES_ROUTE,
  LIST_SCORES_BY_SPAN_ROUTE,
  // Logs
  LIST_LOGS_ROUTE,
  // Scores (observability storage)
  LIST_SCORES_ROUTE,
  CREATE_SCORE_ROUTE,
  // Feedback
  LIST_FEEDBACK_ROUTE,
  CREATE_FEEDBACK_ROUTE,
  // Metrics
  GET_METRIC_AGGREGATE_ROUTE,
  GET_METRIC_BREAKDOWN_ROUTE,
  GET_METRIC_TIME_SERIES_ROUTE,
  GET_METRIC_PERCENTILES_ROUTE,
  // Discovery
  GET_METRIC_NAMES_ROUTE,
  GET_METRIC_LABEL_KEYS_ROUTE,
  GET_METRIC_LABEL_VALUES_ROUTE,
  GET_ENTITY_TYPES_ROUTE,
  GET_ENTITY_NAMES_ROUTE,
  GET_SERVICE_NAMES_ROUTE,
  GET_ENVIRONMENTS_ROUTE,
  GET_TAGS_ROUTE,
] as const;
