import {
  LIST_STORED_MCP_SERVERS_ROUTE,
  GET_STORED_MCP_SERVER_ROUTE,
  CREATE_STORED_MCP_SERVER_ROUTE,
  UPDATE_STORED_MCP_SERVER_ROUTE,
  DELETE_STORED_MCP_SERVER_ROUTE,
} from '../../handlers/stored-mcp-servers';
import type { ServerRoute } from '.';

export const STORED_MCP_SERVERS_ROUTES: ServerRoute<any, any, any>[] = [
  LIST_STORED_MCP_SERVERS_ROUTE,
  GET_STORED_MCP_SERVER_ROUTE,
  CREATE_STORED_MCP_SERVER_ROUTE,
  UPDATE_STORED_MCP_SERVER_ROUTE,
  DELETE_STORED_MCP_SERVER_ROUTE,
];
