import {
  AUTHORIZE_TOOL_INTEGRATION_ROUTE,
  GET_TOOL_INTEGRATION_AUTH_STATUS_ROUTE,
  GET_TOOL_INTEGRATION_HEALTH_ROUTE,
  LIST_TOOL_INTEGRATION_TOOLS_ROUTE,
  LIST_TOOL_INTEGRATIONS_ROUTE,
  LIST_TOOL_SERVICES_ROUTE,
  TOOL_INTEGRATION_CONNECTION_STATUS_ROUTE,
} from '../../handlers/tool-integrations';

export const TOOL_INTEGRATION_ROUTES = [
  LIST_TOOL_INTEGRATIONS_ROUTE,
  LIST_TOOL_SERVICES_ROUTE,
  LIST_TOOL_INTEGRATION_TOOLS_ROUTE,
  AUTHORIZE_TOOL_INTEGRATION_ROUTE,
  GET_TOOL_INTEGRATION_AUTH_STATUS_ROUTE,
  TOOL_INTEGRATION_CONNECTION_STATUS_ROUTE,
  GET_TOOL_INTEGRATION_HEALTH_ROUTE,
] as const;
