import {
  CHECK_TRAINING_DATA_ROUTE,
  LIST_TRAINING_JOBS_ROUTE,
  GET_TRAINING_JOB_ROUTE,
  START_TRAINING_JOB_ROUTE,
  CANCEL_TRAINING_JOB_ROUTE,
  GET_TRAINING_JOB_EVENTS_ROUTE,
  GET_TRAINING_JOB_CHECKPOINTS_ROUTE,
  LIST_TRAINED_MODELS_ROUTE,
  GET_TRAINED_MODEL_ROUTE,
  SET_ACTIVE_MODEL_ROUTE,
} from '../../handlers/training';
import type { ServerRoute } from '.';

export const TRAINING_ROUTES: ServerRoute<any, any, any>[] = [
  // Training data check
  CHECK_TRAINING_DATA_ROUTE,
  // Training jobs
  LIST_TRAINING_JOBS_ROUTE,
  GET_TRAINING_JOB_ROUTE,
  START_TRAINING_JOB_ROUTE,
  CANCEL_TRAINING_JOB_ROUTE,
  GET_TRAINING_JOB_EVENTS_ROUTE,
  GET_TRAINING_JOB_CHECKPOINTS_ROUTE,
  // Trained models
  LIST_TRAINED_MODELS_ROUTE,
  GET_TRAINED_MODEL_ROUTE,
  SET_ACTIVE_MODEL_ROUTE,
];
