import {
  upsertVectors,
  createIndex,
  queryVectors,
  listIndexes,
  describeIndex,
  deleteIndex,
} from '../../handlers/vector';
import {
  vectorNamePathParams,
  vectorIndexPathParams,
  upsertVectorsBodySchema,
  upsertVectorsResponseSchema,
  createIndexBodySchema,
  createIndexResponseSchema,
  queryVectorsBodySchema,
  queryVectorsResponseSchema,
  listIndexesResponseSchema,
  describeIndexResponseSchema,
  deleteIndexResponseSchema,
} from '../../schemas/vectors';
import { createRoute } from './route-builder';
import type { ServerRoute, ServerRouteHandler } from '.';

export const VECTORS_ROUTES: ServerRoute[] = [
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: upsertVectors as unknown as ServerRouteHandler,
    path: '/api/vector/:vectorName/upsert',
    pathParamSchema: vectorNamePathParams,
    bodySchema: upsertVectorsBodySchema,
    responseSchema: upsertVectorsResponseSchema,
    summary: 'Upsert vectors',
    description: 'Inserts or updates vectors in the specified index',
    tags: ['Vectors'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: createIndex as unknown as ServerRouteHandler,
    path: '/api/vector/:vectorName/indexes',
    pathParamSchema: vectorNamePathParams,
    bodySchema: createIndexBodySchema,
    responseSchema: createIndexResponseSchema,
    summary: 'Create index',
    description: 'Creates a new vector index with the specified dimension and metric',
    tags: ['Vectors'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: queryVectors as unknown as ServerRouteHandler,
    path: '/api/vector/:vectorName/query',
    pathParamSchema: vectorNamePathParams,
    bodySchema: queryVectorsBodySchema,
    responseSchema: queryVectorsResponseSchema,
    summary: 'Query vectors',
    description: 'Performs a similarity search on the vector index',
    tags: ['Vectors'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: listIndexes as unknown as ServerRouteHandler,
    path: '/api/vector/:vectorName/indexes',
    pathParamSchema: vectorNamePathParams,
    responseSchema: listIndexesResponseSchema,
    summary: 'List indexes',
    description: 'Returns a list of all indexes in the vector store',
    tags: ['Vectors'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: describeIndex as unknown as ServerRouteHandler,
    path: '/api/vector/:vectorName/indexes/:indexName',
    pathParamSchema: vectorIndexPathParams,
    responseSchema: describeIndexResponseSchema,
    summary: 'Describe index',
    description: 'Returns statistics and metadata for a specific index',
    tags: ['Vectors'],
  }),
  createRoute({
    method: 'DELETE',
    responseType: 'json',
    handler: deleteIndex as unknown as ServerRouteHandler,
    path: '/api/vector/:vectorName/indexes/:indexName',
    pathParamSchema: vectorIndexPathParams,
    responseSchema: deleteIndexResponseSchema,
    summary: 'Delete index',
    description: 'Deletes a vector index and all its data',
    tags: ['Vectors'],
  }),
];
