import {
  cancelWorkflowRunHandler,
  createWorkflowRunHandler,
  getWorkflowByIdHandler,
  getWorkflowRunByIdHandler,
  getWorkflowRunExecutionResultHandler,
  listWorkflowRunsHandler,
  listWorkflowsHandler,
  observeStreamVNextWorkflowHandler,
  observeStreamWorkflowHandler,
  resumeAsyncWorkflowHandler,
  resumeStreamWorkflowHandler,
  resumeWorkflowHandler,
  startAsyncWorkflowHandler,
  startWorkflowRunHandler,
  streamWorkflowHandler,
} from '../../handlers/workflows';
import {
  createWorkflowRunResponseSchema,
  listWorkflowRunsQuerySchema,
  listWorkflowsResponseSchema,
  optionalRunIdQuerySchema,
  resumeBodySchema,
  runIdQuerySchema,
  startAsyncWorkflowBodySchema,
  streamWorkflowBodySchema,
  workflowControlResponseSchema,
  workflowExecutionResultSchema,
  workflowIdPathParams,
  workflowInfoSchema,
  workflowRunPathParams,
  workflowRunResponseSchema,
  workflowRunsResponseSchema,
} from '../../schemas/workflows';
import { createRoute } from './route-builder';
import type { ServerRoute, ServerRouteHandler } from '.';

export const WORKFLOWS_ROUTES: ServerRoute[] = [
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: listWorkflowsHandler as unknown as ServerRouteHandler,
    path: '/api/workflows',
    responseSchema: listWorkflowsResponseSchema,
    summary: 'List all workflows',
    description: 'Returns a list of all available workflows in the system',
    tags: ['Workflows'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getWorkflowByIdHandler as unknown as ServerRouteHandler,
    path: '/api/workflows/:workflowId',
    pathParamSchema: workflowIdPathParams,
    responseSchema: workflowInfoSchema,
    summary: 'Get workflow by ID',
    description: 'Returns details for a specific workflow including steps and configuration',
    tags: ['Workflows'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: listWorkflowRunsHandler as unknown as ServerRouteHandler,
    path: '/api/workflows/:workflowId/runs',
    pathParamSchema: workflowIdPathParams,
    queryParamSchema: listWorkflowRunsQuerySchema,
    responseSchema: workflowRunsResponseSchema,
    summary: 'List workflow runs',
    description: 'Returns a paginated list of execution runs for the specified workflow',
    tags: ['Workflows'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getWorkflowRunByIdHandler as unknown as ServerRouteHandler,
    path: '/api/workflows/:workflowId/runs/:runId',
    pathParamSchema: workflowRunPathParams,
    responseSchema: workflowRunResponseSchema,
    summary: 'Get workflow run by ID',
    description: 'Returns details for a specific workflow run including execution status and results',
    tags: ['Workflows'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: createWorkflowRunHandler as unknown as ServerRouteHandler,
    path: '/api/workflows/:workflowId/create-run',
    pathParamSchema: workflowIdPathParams,
    queryParamSchema: optionalRunIdQuerySchema,
    responseSchema: createWorkflowRunResponseSchema,
    summary: 'Create workflow run',
    description: 'Creates a new workflow execution instance with an optional custom run ID',
    tags: ['Workflows'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'stream',
    handler: streamWorkflowHandler as unknown as ServerRouteHandler,
    path: '/api/workflows/:workflowId/stream',
    pathParamSchema: workflowIdPathParams,
    queryParamSchema: runIdQuerySchema,
    bodySchema: streamWorkflowBodySchema,
    summary: 'Stream workflow execution',
    description: 'Executes a workflow and streams the results in real-time',
    tags: ['Workflows'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'stream',
    handler: streamWorkflowHandler as unknown as ServerRouteHandler,
    path: '/api/workflows/:workflowId/streamVNext',
    pathParamSchema: workflowIdPathParams,
    queryParamSchema: runIdQuerySchema,
    bodySchema: streamWorkflowBodySchema,
    summary: 'Stream workflow execution (v2)',
    description: 'Executes a workflow using the v2 streaming API and streams the results in real-time',
    tags: ['Workflows'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'stream',
    handler: resumeStreamWorkflowHandler as unknown as ServerRouteHandler,
    path: '/api/workflows/:workflowId/resume-stream',
    pathParamSchema: workflowIdPathParams,
    queryParamSchema: runIdQuerySchema,
    bodySchema: resumeBodySchema,
    summary: 'Resume workflow stream',
    description: 'Resumes a suspended workflow execution and continues streaming results',
    tags: ['Workflows'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'json',
    handler: getWorkflowRunExecutionResultHandler as unknown as ServerRouteHandler,
    path: '/api/workflows/:workflowId/runs/:runId/execution-result',
    pathParamSchema: workflowRunPathParams,
    responseSchema: workflowExecutionResultSchema,
    summary: 'Get workflow execution result',
    description: 'Returns the final execution result of a completed workflow run',
    tags: ['Workflows'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: startAsyncWorkflowHandler as unknown as ServerRouteHandler,
    path: '/api/workflows/:workflowId/start-async',
    pathParamSchema: workflowIdPathParams,
    queryParamSchema: runIdQuerySchema,
    bodySchema: startAsyncWorkflowBodySchema,
    responseSchema: workflowExecutionResultSchema,
    summary: 'Start workflow asynchronously',
    description: 'Starts a workflow execution asynchronously without streaming results',
    tags: ['Workflows'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: startWorkflowRunHandler as unknown as ServerRouteHandler,
    path: '/api/workflows/:workflowId/runs/:runId/start',
    pathParamSchema: workflowRunPathParams,
    bodySchema: startAsyncWorkflowBodySchema,
    responseSchema: workflowControlResponseSchema,
    summary: 'Start specific workflow run',
    description: 'Starts execution of a specific workflow run by ID',
    tags: ['Workflows'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'stream',
    handler: observeStreamWorkflowHandler as unknown as ServerRouteHandler,
    path: '/api/workflows/:workflowId/runs/:runId/observe-stream',
    pathParamSchema: workflowRunPathParams,
    summary: 'Observe workflow stream',
    description: 'Observes and streams updates from an already running workflow execution',
    tags: ['Workflows'],
  }),
  createRoute({
    method: 'GET',
    responseType: 'stream',
    handler: observeStreamVNextWorkflowHandler as unknown as ServerRouteHandler,
    path: '/api/workflows/:workflowId/runs/:runId/observe-stream-vnext',
    pathParamSchema: workflowRunPathParams,
    summary: 'Observe workflow stream (v2)',
    description: 'Observes and streams updates from an already running workflow execution using v2 streaming API',
    tags: ['Workflows'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: resumeAsyncWorkflowHandler as unknown as ServerRouteHandler,
    path: '/api/workflows/:workflowId/runs/:runId/resume-async',
    pathParamSchema: workflowRunPathParams,
    bodySchema: resumeBodySchema,
    responseSchema: workflowExecutionResultSchema,
    summary: 'Resume workflow asynchronously',
    description: 'Resumes a suspended workflow execution asynchronously without streaming',
    tags: ['Workflows'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: resumeWorkflowHandler as unknown as ServerRouteHandler,
    path: '/api/workflows/:workflowId/runs/:runId/resume',
    pathParamSchema: workflowRunPathParams,
    bodySchema: resumeBodySchema,
    responseSchema: workflowControlResponseSchema,
    summary: 'Resume workflow',
    description: 'Resumes a suspended workflow execution from a specific step',
    tags: ['Workflows'],
  }),
  createRoute({
    method: 'POST',
    responseType: 'json',
    handler: cancelWorkflowRunHandler as unknown as ServerRouteHandler,
    path: '/api/workflows/:workflowId/runs/:runId/cancel',
    pathParamSchema: workflowRunPathParams,
    responseSchema: workflowControlResponseSchema,
    summary: 'Cancel workflow run',
    description: 'Cancels an in-progress workflow execution',
    tags: ['Workflows'],
  }),
];
