const meta = {
  workflow: "Workflow",
  step: "Step",
  then: ".then()",
  commit: ".commit()",
  stream: ".stream()",
  streamVNext: ".streamVNext()",
  "create-run": ".createRunAsync()",
  start: ".start()",
  resume: ".resume()",
  watch: ".watch()",
  parallel: ".parallel()",
  branch: ".branch()",
  dowhile: ".dowhile()",
  dountil: ".dountil()",
  foreach: ".foreach()",
  map: ".map()",
  sleep: ".sleep()",
  sleepUntil: ".sleepUntil()",
  waitForEvent: ".waitForEvent()",
  sendEvent: ".sendEvent()",
  execute: ".execute()",
  snapshots: "Snapshots",
};

export default meta;
