import "../dialect-BvcuosDD.mjs";
import "../get-model-name-D4DUV7S2.mjs";
import "../get-migration-6ewabxRC.mjs";
import { n as HIDE_METADATA } from "../utils-DBbaShi0.mjs";
import "../crypto-BQxYXGGX.mjs";
import "../jwt-DzuIBp7t.mjs";
import "../misc-D8A8FGv2.mjs";
import "../schema-CSB7dlK0.mjs";
import "../get-request-ip-RYTz2Uba.mjs";
import "../json-_HMgPUVh.mjs";
import "../url-BLNRhCPO.mjs";
import "../api-q2sbQ7PT.mjs";
import "../cookies-D_dksn7B.mjs";
import "../session-CgfX4vv1.mjs";
import "../password-DBH2q5D6.mjs";
import "../parser-kwbb5q_C.mjs";
import { n as role, t as createAccessControl } from "../access-DXuPG0DH.mjs";
import "../access-Bue6UE97.mjs";
import "../has-permission-DN8I_Icv.mjs";
import "../access-Cr_p-YVH.mjs";
import "../permission-ouQCO-51.mjs";
import { t as twoFactorClient } from "../client-CZZjjkJj.mjs";
import "../plugin-helper-CA_Vvnl9.mjs";
import { t as admin } from "../admin-C0d5dk6O.mjs";
import { t as anonymous } from "../anonymous-B5kAEMza.mjs";
import { a as getMCPProtectedResourceMetadata, c as oAuthDiscoveryMetadata, d as lastLoginMethod, f as API_KEY_TABLE_NAME, h as defaultKeyHasher, i as oneTimeToken, l as oAuthProtectedResourceMetadata, m as apiKey, n as createAuthMiddleware, o as getMCPProviderMetadata, p as ERROR_CODES, r as optionsMiddleware, s as mcp, t as createAuthEndpoint, u as withMcpAuth } from "../plugins-CNNzRsQh.mjs";
import { t as bearer } from "../bearer-Bb8KNDdJ.mjs";
import { t as captcha } from "../captcha-Dnh5mC7N.mjs";
import { t as customSession } from "../custom-session-fyHQcwKB.mjs";
import { n as deviceAuthorizationOptionsSchema, t as deviceAuthorization } from "../device-authorization-F9dLozvK.mjs";
import { t as emailOTP } from "../email-otp-wYPJyq8c.mjs";
import { a as line, c as auth0, i as microsoftEntraId, n as slack, o as keycloak, r as okta, s as hubspot, t as genericOAuth } from "../generic-oauth-BlH-OSQN.mjs";
import { t as haveIBeenPwned } from "../haveibeenpwned-v0bNR9PL.mjs";
import { a as generateExportedKeyPair, i as createJwk, n as verifyJWT, r as getJwtToken, t as jwt } from "../jwt-BcNc-TEx.mjs";
import { t as magicLink } from "../magic-link-B1zZrjdu.mjs";
import { n as getMetadata, r as oidcProvider, t as getClient } from "../oidc-provider-CBEpaKIt.mjs";
import { t as multiSession } from "../multi-session-Cr3eN7zC.mjs";
import { t as oAuthProxy } from "../oauth-proxy-CSxVQ45y.mjs";
import { t as oneTap } from "../one-tap-CPlglews.mjs";
import { t as openAPI } from "../open-api-C33sH63J.mjs";
import { n as parseRoles, t as organization } from "../organization-CWQKXyi5.mjs";
import { t as phoneNumber } from "../phone-number-DIG4Jnsx.mjs";
import { t as siwe } from "../siwe-D4lyacqA.mjs";
import { n as TWO_FACTOR_ERROR_CODES, t as twoFactor } from "../two-factor-1QPLscVk.mjs";
import { n as USERNAME_ERROR_CODES, t as username } from "../username-CxPDW9ty.mjs";

export { API_KEY_TABLE_NAME, ERROR_CODES, HIDE_METADATA, TWO_FACTOR_ERROR_CODES, USERNAME_ERROR_CODES, admin, anonymous, apiKey, auth0, bearer, captcha, createAccessControl, createAuthEndpoint, createAuthMiddleware, createJwk, customSession, defaultKeyHasher, deviceAuthorization, deviceAuthorizationOptionsSchema, emailOTP, generateExportedKeyPair, genericOAuth, getClient, getJwtToken, getMCPProtectedResourceMetadata, getMCPProviderMetadata, getMetadata, haveIBeenPwned, hubspot, jwt, keycloak, lastLoginMethod, line, magicLink, mcp, microsoftEntraId, multiSession, oAuthDiscoveryMetadata, oAuthProtectedResourceMetadata, oAuthProxy, oidcProvider, okta, oneTap, oneTimeToken, openAPI, optionsMiddleware, organization, parseRoles, phoneNumber, role, siwe, slack, twoFactor, twoFactorClient, username, verifyJWT, withMcpAuth };