import { msg } from "gt-react";
export const referenceSections: Record<string, Array<{ title: string; href: string }>> = {
  Agents: [
    { title: 'Agent', href: '/docs/reference/agents/agent' },
    { title: 'Generate', href: '/docs/reference/agents/generate' },
    { title: 'GenerateLegacy', href: '/docs/reference/agents/generateLegacy' },
    {
      title: 'GetDefaultGenerateOptions',
      href: '/docs/reference/agents/getDefaultGenerateOptions',
    },
    {
      title: 'GetDefaultStreamOptions',
      href: '/docs/reference/agents/getDefaultStreamOptions',
    },
    { title: 'GetDescription', href: '/docs/reference/agents/getDescription' },
    { title: 'GetInstructions', href: '/docs/reference/agents/getInstructions' },
    { title: 'GetLLM', href: '/docs/reference/agents/getLLM' },
    { title: 'GetMemory', href: '/docs/reference/agents/getMemory' },
    { title: 'GetModel', href: '/docs/reference/agents/getModel' },
    { title: 'GetScorers', href: '/docs/reference/agents/getScorers' },
    { title: 'GetTools', href: '/docs/reference/agents/getTools' },
    { title: 'GetVoice', href: '/docs/reference/agents/getVoice' },
    { title: 'GetWorkflows', href: '/docs/reference/agents/getWorkflows' },
    { title: 'ListAgents', href: '/docs/reference/agents/listAgents' },
    { title: msg('Migration Guide'), href: '/docs/reference/agents/migration-guide' },
    { title: 'Network', href: '/docs/reference/agents/network' },
  ],
  Auth: [
    { title: 'Auth0', href: '/docs/reference/auth/auth0' },
    { title: 'Clerk', href: '/docs/reference/auth/clerk' },
    { title: 'Firebase', href: '/docs/reference/auth/firebase' },
    { title: 'Jwt', href: '/docs/reference/auth/jwt' },
    { title: 'Supabase', href: '/docs/reference/auth/supabase' },
    { title: 'Workos', href: '/docs/reference/auth/workos' },
  ],
  CLI: [
    { title: 'Create Mastra', href: '/docs/reference/cli/create-mastra' },
    { title: 'Mastra', href: '/docs/reference/cli/mastra' },
  ],
  'Client SDK': [
    { title: 'Agents', href: '/docs/reference/client-js/agents' },
    { title: 'Error Handling', href: '/docs/reference/client-js/error-handling' },
    { title: 'Logs', href: '/docs/reference/client-js/logs' },
    { title: 'Mastra Client', href: '/docs/reference/client-js/mastra-client' },
    { title: 'Memory', href: '/docs/reference/client-js/memory' },
    { title: 'Observability', href: '/docs/reference/client-js/observability' },
    { title: 'Telemetry', href: '/docs/reference/client-js/telemetry' },
    { title: 'Tools', href: '/docs/reference/client-js/tools' },
    { title: 'Vectors', href: '/docs/reference/client-js/vectors' },
    { title: 'Workflows Legacy', href: '/docs/reference/client-js/workflows-legacy' },
    { title: 'Workflows', href: '/docs/reference/client-js/workflows' },
  ],
  Core: [
    { title: 'GetAgent', href: '/docs/reference/core/getAgent' },
    { title: 'GetAgentById', href: '/docs/reference/core/getAgentById' },
    { title: 'GetAgents', href: '/docs/reference/core/getAgents' },
    { title: 'GetDeployer', href: '/docs/reference/core/getDeployer' },
    { title: 'GetLogger', href: '/docs/reference/core/getLogger' },
    { title: 'GetLogs', href: '/docs/reference/core/getLogs' },
    { title: 'GetLogsByRunId', href: '/docs/reference/core/getLogsByRunId' },
    { title: 'GetMCPServer', href: '/docs/reference/core/getMCPServer' },
    { title: 'GetMCPServers', href: '/docs/reference/core/getMCPServers' },
    { title: 'GetMemory', href: '/docs/reference/core/getMemory' },
    { title: 'GetScorer', href: '/docs/reference/core/getScorer' },
    { title: 'GetScorerByName', href: '/docs/reference/core/getScorerByName' },
    { title: 'GetScorers', href: '/docs/reference/core/getScorers' },
    { title: 'GetServer', href: '/docs/reference/core/getServer' },
    { title: 'GetStorage', href: '/docs/reference/core/getStorage' },
    { title: 'GetTelemetry', href: '/docs/reference/core/getTelemetry' },
    { title: 'GetVector', href: '/docs/reference/core/getVector' },
    { title: 'GetVectors', href: '/docs/reference/core/getVectors' },
    { title: 'GetWorkflow', href: '/docs/reference/core/getWorkflow' },
    { title: 'GetWorkflows', href: '/docs/reference/core/getWorkflows' },
    { title: 'Mastra Class', href: '/docs/reference/core/mastra-class' },
    { title: 'SetLogger', href: '/docs/reference/core/setLogger' },
    { title: 'SetStorage', href: '/docs/reference/core/setStorage' },
    { title: 'SetTelemetry', href: '/docs/reference/core/setTelemetry' },
  ],
  Deployer: [
    { title: 'Cloudflare', href: '/docs/reference/deployer/cloudflare' },
    { title: 'Deployer', href: '/docs/reference/deployer/deployer' },
    { title: 'Netlify', href: '/docs/reference/deployer/netlify' },
    { title: 'Vercel', href: '/docs/reference/deployer/vercel' },
  ],
  Evals: [
    { title: 'Answer Relevancy', href: '/docs/reference/evals/answer-relevancy' },
    { title: 'Bias', href: '/docs/reference/evals/bias' },
    { title: 'Completeness', href: '/docs/reference/evals/completeness' },
    { title: 'Content Similarity', href: '/docs/reference/evals/content-similarity' },
    { title: 'Context Position', href: '/docs/reference/evals/context-position' },
    { title: 'Context Precision', href: '/docs/reference/evals/context-precision' },
    { title: 'Context Relevancy', href: '/docs/reference/evals/context-relevancy' },
    { title: 'Contextual Recall', href: '/docs/reference/evals/contextual-recall' },
    { title: 'Faithfulness', href: '/docs/reference/evals/faithfulness' },
    { title: 'Hallucination', href: '/docs/reference/evals/hallucination' },
    { title: 'Keyword Coverage', href: '/docs/reference/evals/keyword-coverage' },
    { title: 'Prompt Alignment', href: '/docs/reference/evals/prompt-alignment' },
    { title: 'Summarization', href: '/docs/reference/evals/summarization' },
    { title: 'Textual Difference', href: '/docs/reference/evals/textual-difference' },
    { title: 'Tone Consistency', href: '/docs/reference/evals/tone-consistency' },
    { title: 'Toxicity', href: '/docs/reference/evals/toxicity' },
  ],
  'Legacy Workflows': [
    { title: 'After', href: '/docs/reference/legacyWorkflows/after' },
    { title: 'AfterEvent', href: '/docs/reference/legacyWorkflows/afterEvent' },
    { title: 'Commit', href: '/docs/reference/legacyWorkflows/commit' },
    { title: 'CreateRun', href: '/docs/reference/legacyWorkflows/createRun' },
    { title: 'Else', href: '/docs/reference/legacyWorkflows/else' },
    { title: 'Events', href: '/docs/reference/legacyWorkflows/events' },
    { title: 'Execute', href: '/docs/reference/legacyWorkflows/execute' },
    { title: 'If', href: '/docs/reference/legacyWorkflows/if' },
    { title: 'Resume', href: '/docs/reference/legacyWorkflows/resume' },
    { title: 'ResumeWithEvent', href: '/docs/reference/legacyWorkflows/resumeWithEvent' },
    { title: 'Snapshots', href: '/docs/reference/legacyWorkflows/snapshots' },
    { title: 'Start', href: '/docs/reference/legacyWorkflows/start' },
    { title: 'Step Class', href: '/docs/reference/legacyWorkflows/step-class' },
    { title: 'Step Condition', href: '/docs/reference/legacyWorkflows/step-condition' },
    { title: 'Step Function', href: '/docs/reference/legacyWorkflows/step-function' },
    { title: 'Step Options', href: '/docs/reference/legacyWorkflows/step-options' },
    { title: 'Step Retries', href: '/docs/reference/legacyWorkflows/step-retries' },
    { title: 'Suspend', href: '/docs/reference/legacyWorkflows/suspend' },
    { title: 'Then', href: '/docs/reference/legacyWorkflows/then' },
    { title: 'Until', href: '/docs/reference/legacyWorkflows/until' },
    { title: 'Watch', href: '/docs/reference/legacyWorkflows/watch' },
    { title: 'While', href: '/docs/reference/legacyWorkflows/while' },
    { title: 'Workflow', href: '/docs/reference/legacyWorkflows/workflow' },
  ],
  Memory: [
    { title: 'Memory', href: '/docs/reference/memory/Memory' },
    { title: 'CreateThread', href: '/docs/reference/memory/createThread' },
    { title: 'DeleteMessages', href: '/docs/reference/memory/deleteMessages' },
    { title: 'GetThreadById', href: '/docs/reference/memory/getThreadById' },
    {
      title: 'GetThreadsByResourceId',
      href: '/docs/reference/memory/getThreadsByResourceId',
    },
    {
      title: 'GetThreadsByResourceIdPaginated',
      href: '/docs/reference/memory/getThreadsByResourceIdPaginated',
    },
    { title: 'Query', href: '/docs/reference/memory/query' },
  ],
  Observability: [
    { title: 'Ai Tracing', href: '/docs/reference/observability/ai-tracing/ai-tracing' },
    { title: 'Configuration', href: '/docs/reference/observability/ai-tracing/configuration' },
    {
      title: 'Braintrust',
      href: '/docs/reference/observability/ai-tracing/exporters/braintrust',
    },
    {
      title: 'Cloud Exporter',
      href: '/docs/reference/observability/ai-tracing/exporters/cloud-exporter',
    },
    {
      title: 'Console Exporter',
      href: '/docs/reference/observability/ai-tracing/exporters/console-exporter',
    },
    {
      title: 'Default Exporter',
      href: '/docs/reference/observability/ai-tracing/exporters/default-exporter',
    },
    { title: 'Langfuse', href: '/docs/reference/observability/ai-tracing/exporters/langfuse' },
    {
      title: 'Langsmith',
      href: '/docs/reference/observability/ai-tracing/exporters/langsmith',
    },
    { title: 'Otel', href: '/docs/reference/observability/ai-tracing/exporters/otel' },
    { title: 'Interfaces', href: '/docs/reference/observability/ai-tracing/interfaces' },
    {
      title: 'Sensitive Data Filter',
      href: '/docs/reference/observability/ai-tracing/processors/sensitive-data-filter',
    },
    { title: 'Span', href: '/docs/reference/observability/ai-tracing/span' },
    { title: 'Pino Logger', href: '/docs/reference/observability/logging/pino-logger' },
    { title: 'Otel Config', href: '/docs/reference/observability/otel-tracing/otel-config' },
    {
      title: 'Arize Ax',
      href: '/docs/reference/observability/otel-tracing/providers/arize-ax',
    },
    {
      title: 'Arize Phoenix',
      href: '/docs/reference/observability/otel-tracing/providers/arize-phoenix',
    },
    {
      title: 'Braintrust',
      href: '/docs/reference/observability/otel-tracing/providers/braintrust',
    },
    { title: 'Dash0', href: '/docs/reference/observability/otel-tracing/providers/dash0' },
    {
      title: 'Keywordsai',
      href: '/docs/reference/observability/otel-tracing/providers/keywordsai',
    },
    { title: 'Laminar', href: '/docs/reference/observability/otel-tracing/providers/laminar' },
    {
      title: 'Langfuse',
      href: '/docs/reference/observability/otel-tracing/providers/langfuse',
    },
    {
      title: 'Langsmith',
      href: '/docs/reference/observability/otel-tracing/providers/langsmith',
    },
    {
      title: 'Langwatch',
      href: '/docs/reference/observability/otel-tracing/providers/langwatch',
    },
    {
      title: 'New Relic',
      href: '/docs/reference/observability/otel-tracing/providers/new-relic',
    },
    { title: 'Signoz', href: '/docs/reference/observability/otel-tracing/providers/signoz' },
    {
      title: 'Traceloop',
      href: '/docs/reference/observability/otel-tracing/providers/traceloop',
    },
  ],
  Processors: [
    {
      title: 'Batch Parts Processor',
      href: '/docs/reference/processors/batch-parts-processor',
    },
    { title: 'Language Detector', href: '/docs/reference/processors/language-detector' },
    {
      title: 'Moderation Processor',
      href: '/docs/reference/processors/moderation-processor',
    },
    { title: 'Pii Detector', href: '/docs/reference/processors/pii-detector' },
    {
      title: 'Prompt Injection Detector',
      href: '/docs/reference/processors/prompt-injection-detector',
    },
    {
      title: 'System Prompt Scrubber',
      href: '/docs/reference/processors/system-prompt-scrubber',
    },
    {
      title: 'Token Limiter Processor',
      href: '/docs/reference/processors/token-limiter-processor',
    },
    { title: 'Unicode Normalizer', href: '/docs/reference/processors/unicode-normalizer' },
  ],
  RAG: [
    { title: 'Chunk', href: '/docs/reference/rag/chunk' },
    { title: 'Database Config', href: '/docs/reference/rag/database-config' },
    { title: 'Document', href: '/docs/reference/rag/document' },
    { title: 'Embeddings', href: '/docs/reference/rag/embeddings' },
    { title: 'Extract Params', href: '/docs/reference/rag/extract-params' },
    { title: 'Graph Rag', href: '/docs/reference/rag/graph-rag' },
    { title: 'Metadata Filters', href: '/docs/reference/rag/metadata-filters' },
    { title: 'Rerank', href: '/docs/reference/rag/rerank' },
    { title: 'RerankWithScorer', href: '/docs/reference/rag/rerankWithScorer' },
  ],
  Scorers: [
    { title: 'Answer Relevancy', href: '/docs/reference/scorers/answer-relevancy' },
    { title: 'Answer Similarity', href: '/docs/reference/scorers/answer-similarity' },
    { title: 'Bias', href: '/docs/reference/scorers/bias' },
    { title: 'Completeness', href: '/docs/reference/scorers/completeness' },
    { title: 'Content Similarity', href: '/docs/reference/scorers/content-similarity' },
    { title: 'Context Precision', href: '/docs/reference/scorers/context-precision' },
    { title: 'Context Relevance', href: '/docs/reference/scorers/context-relevance' },
    { title: 'Create Scorer', href: '/docs/reference/scorers/create-scorer' },
    { title: 'Faithfulness', href: '/docs/reference/scorers/faithfulness' },
    { title: 'Hallucination', href: '/docs/reference/scorers/hallucination' },
    { title: 'Keyword Coverage', href: '/docs/reference/scorers/keyword-coverage' },
    { title: 'Mastra Scorer', href: '/docs/reference/scorers/mastra-scorer' },
    { title: 'Noise Sensitivity', href: '/docs/reference/scorers/noise-sensitivity' },
    { title: 'Prompt Alignment', href: '/docs/reference/scorers/prompt-alignment' },
    { title: 'Run Experiment', href: '/docs/reference/scorers/run-experiment' },
    { title: 'Textual Difference', href: '/docs/reference/scorers/textual-difference' },
    { title: 'Tone Consistency', href: '/docs/reference/scorers/tone-consistency' },
    { title: 'Tool Call Accuracy', href: '/docs/reference/scorers/tool-call-accuracy' },
    { title: 'Toxicity', href: '/docs/reference/scorers/toxicity' },
  ],
  Storage: [
    { title: 'Cloudflare D1', href: '/docs/reference/storage/cloudflare-d1' },
    { title: 'Cloudflare', href: '/docs/reference/storage/cloudflare' },
    { title: 'Dynamodb', href: '/docs/reference/storage/dynamodb' },
    { title: 'Lance', href: '/docs/reference/storage/lance' },
    { title: 'Libsql', href: '/docs/reference/storage/libsql' },
    { title: 'Mssql', href: '/docs/reference/storage/mssql' },
    { title: 'Postgresql', href: '/docs/reference/storage/postgresql' },
    { title: 'Upstash', href: '/docs/reference/storage/upstash' },
  ],
  Streaming: [
    { title: 'ChunkType', href: '/docs/reference/streaming/ChunkType' },
    {
      title: 'MastraModelOutput',
      href: '/docs/reference/streaming/agents/MastraModelOutput',
    },
    { title: 'Stream', href: '/docs/reference/streaming/agents/stream' },
    { title: 'StreamLegacy', href: '/docs/reference/streaming/agents/streamLegacy' },
    { title: 'ObserveStream', href: '/docs/reference/streaming/workflows/observeStream' },
    {
      title: 'ObserveStreamVNext',
      href: '/docs/reference/streaming/workflows/observeStreamVNext',
    },
    {
      title: 'ResumeStreamVNext',
      href: '/docs/reference/streaming/workflows/resumeStreamVNext',
    },
    { title: 'Stream', href: '/docs/reference/streaming/workflows/stream' },
    { title: 'StreamVNext', href: '/docs/reference/streaming/workflows/streamVNext' },
  ],
  Templates: [{ title: 'Overview', href: '/docs/reference/templates/overview' }],
  'Tools & MCP': [
    { title: 'Client', href: '/docs/reference/tools/client' },
    { title: 'Create Tool', href: '/docs/reference/tools/create-tool' },
    {
      title: 'Document Chunker Tool',
      href: '/docs/reference/tools/document-chunker-tool',
    },
    { title: 'Graph Rag Tool', href: '/docs/reference/tools/graph-rag-tool' },
    { title: 'Mcp Client', href: '/docs/reference/tools/mcp-client' },
    { title: 'Mcp Server', href: '/docs/reference/tools/mcp-server' },
    { title: 'Vector Query Tool', href: '/docs/reference/tools/vector-query-tool' },
  ],
  Networks: [
    { title: 'Astra', href: '/docs/reference/vectors/astra' },
    { title: 'Chroma', href: '/docs/reference/vectors/chroma' },
    { title: 'Couchbase', href: '/docs/reference/vectors/couchbase' },
    { title: 'Lance', href: '/docs/reference/vectors/lance' },
    { title: 'Libsql', href: '/docs/reference/vectors/libsql' },
    { title: 'Mongodb', href: '/docs/reference/vectors/mongodb' },
    { title: 'Opensearch', href: '/docs/reference/vectors/opensearch' },
    { title: 'Pg', href: '/docs/reference/vectors/pg' },
    { title: 'Pinecone', href: '/docs/reference/vectors/pinecone' },
    { title: 'Qdrant', href: '/docs/reference/vectors/qdrant' },
    { title: 'S3vectors', href: '/docs/reference/vectors/s3vectors' },
    { title: 'Turbopuffer', href: '/docs/reference/vectors/turbopuffer' },
    { title: 'Upstash', href: '/docs/reference/vectors/upstash' },
    { title: 'Vectorize', href: '/docs/reference/vectors/vectorize' },
  ],
  Voice: [
    { title: 'Azure', href: '/docs/reference/voice/azure' },
    { title: 'Cloudflare', href: '/docs/reference/voice/cloudflare' },
    { title: 'Composite Voice', href: '/docs/reference/voice/composite-voice' },
    { title: 'Deepgram', href: '/docs/reference/voice/deepgram' },
    { title: 'Elevenlabs', href: '/docs/reference/voice/elevenlabs' },
    { title: 'Google Gemini Live', href: '/docs/reference/voice/google-gemini-live' },
    { title: 'Google', href: '/docs/reference/voice/google' },
    { title: 'Mastra Voice', href: '/docs/reference/voice/mastra-voice' },
    { title: 'Murf', href: '/docs/reference/voice/murf' },
    { title: 'Openai Realtime', href: '/docs/reference/voice/openai-realtime' },
    { title: 'Openai', href: '/docs/reference/voice/openai' },
    { title: 'Playai', href: '/docs/reference/voice/playai' },
    { title: 'Sarvam', href: '/docs/reference/voice/sarvam' },
    { title: 'Speechify', href: '/docs/reference/voice/speechify' },
    {
      title: 'Voice.addInstructions',
      href: '/docs/reference/voice/voice.addInstructions',
    },
    { title: 'Voice.addTools', href: '/docs/reference/voice/voice.addTools' },
    { title: 'Voice.answer', href: '/docs/reference/voice/voice.answer' },
    { title: 'Voice.close', href: '/docs/reference/voice/voice.close' },
    { title: 'Voice.connect', href: '/docs/reference/voice/voice.connect' },
    { title: 'Voice.events', href: '/docs/reference/voice/voice.events' },
    { title: 'Voice.getSpeakers', href: '/docs/reference/voice/voice.getSpeakers' },
    { title: 'Voice.listen', href: '/docs/reference/voice/voice.listen' },
    { title: 'Voice.off', href: '/docs/reference/voice/voice.off' },
    { title: 'Voice.on', href: '/docs/reference/voice/voice.on' },
    { title: 'Voice.send', href: '/docs/reference/voice/voice.send' },
    { title: 'Voice.speak', href: '/docs/reference/voice/voice.speak' },
    { title: 'Voice.updateConfig', href: '/docs/reference/voice/voice.updateConfig' },
  ],
  Workflows: [
    { title: 'Cancel', href: '/docs/reference/workflows/run-methods/cancel' },
    { title: 'Resume', href: '/docs/reference/workflows/run-methods/resume' },
    { title: 'Start', href: '/docs/reference/workflows/run-methods/start' },
    { title: 'Watch', href: '/docs/reference/workflows/run-methods/watch' },
    { title: 'Run', href: '/docs/reference/workflows/run' },
    { title: 'Step', href: '/docs/reference/workflows/step' },
    { title: 'Branch', href: '/docs/reference/workflows/workflow-methods/branch' },
    { title: 'Commit', href: '/docs/reference/workflows/workflow-methods/commit' },
    { title: 'Create Run', href: '/docs/reference/workflows/workflow-methods/create-run' },
    { title: 'Dountil', href: '/docs/reference/workflows/workflow-methods/dountil' },
    { title: 'Dowhile', href: '/docs/reference/workflows/workflow-methods/dowhile' },
    { title: 'Foreach', href: '/docs/reference/workflows/workflow-methods/foreach' },
    { title: 'Map', href: '/docs/reference/workflows/workflow-methods/map' },
    { title: 'Parallel', href: '/docs/reference/workflows/workflow-methods/parallel' },
    { title: 'SendEvent', href: '/docs/reference/workflows/workflow-methods/sendEvent' },
    { title: 'Sleep', href: '/docs/reference/workflows/workflow-methods/sleep' },
    { title: 'SleepUntil', href: '/docs/reference/workflows/workflow-methods/sleepUntil' },
    { title: 'Then', href: '/docs/reference/workflows/workflow-methods/then' },
    {
      title: 'WaitForEvent',
      href: '/docs/reference/workflows/workflow-methods/waitForEvent',
    },
    { title: 'Workflow', href: '/docs/reference/workflows/workflow' },
  ],
};

export const sectionTitles = [
  msg('Agents'),
  msg('Auth'),
  msg('CLI'),
  msg('Client SDK'),
  msg('Core'),
  msg('Deployer'),
  msg('Evals'),
  msg('Legacy Workflows'),
  msg('Memory'),
  msg('Observability'),
  msg('Processors'),
  msg('RAG'),
  msg('Scorers'),
  msg('Storage'),
  msg('Streaming'),
  msg('Templates'),
  msg('Tools & MCP'),
  msg('Networks'),
  msg('Voice'),
  msg('Workflows'),
];
