services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - '1433:1433'
    healthcheck:
      test: ['CMD-SHELL', 'echo > /dev/tcp/localhost/1433']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
