const meta = {
  index: "概要",
  openai: "OpenAI",
  anthropic: "Anthropic",
  google: "Google",
  deepseek: "DeepSeek",
  groq: "Groq",
  mistral: "Mistral",
  xai: "xAI",
  aihubmix: "AIHubMix",
  alibaba: "Alibaba",
  "alibaba-cn": "Alibaba（中国）",
  "amazon-bedrock": "Amazon Bedrock",
  azure: "Azure",
  baseten: "Baseten",
  cerebras: "Cerebras",
  chutes: "Chutes",
  "cloudflare-workers-ai": "Cloudflare Workers AI",
  cortecs: "Cortecs",
  deepinfra: "DeepInfra",
  fastrouter: "FastRouter",
  "fireworks-ai": "Fireworks AI",
  "github-models": "GitHub Models",
  "google-vertex": "Google Vertex AI",
  huggingface: "Hugging Face",
  inception: "Inception",
  inference: "Inference",
  llama: "Llama",
  lmstudio: "LMStudio",
  lucidquery: "LucidQuery AI",
  modelscope: "ModelScope",
  moonshotai: "Moonshot AI",
  "moonshotai-cn": "Moonshot AI（中国）",
  morph: "Morph",
  nebius: "Nebius AI Studio",
  nvidia: "NVIDIA",
  ollama: "Ollama",
  opencode: "OpenCode Zen",
  perplexity: "Perplexity",
  requesty: "Requesty",
  scaleway: "Scaleway",
  submodel: "サブモデル",
  synthetic: "Synthetic",
  togetherai: "Together AI",
  upstage: "Upstage",
  venice: "Venice AI",
  vultr: "Vultr",
  wandb: "Weights & Biases",
  zai: "Z.AI",
  "zai-coding-plan": "Z.AI コーディングプラン",
  zhipuai: "Zhipu AI",
  "zhipuai-coding-plan": "Zhipu AI コーディングプラン",
};
export default meta;