const meta = {
  workflow: "ワークフロー",
  "step-class": "Step",
  "step-options": "StepOptions",
  "step-condition": "StepCondition",
  "step-function": ".step()",
  after: ".after()",
  then: ".then()",
  until: ".until()",
  while: ".while()",
  if: ".if()",
  else: ".else()",
  createRun: ".createRun()",
  start: ".start()",
  execute: ".execute()",
  suspend: ".suspend()",
  snapshots: "スナップショット",
  resume: ".resume()",
  commit: ".commit()",
  watch: ".watch()",
  events: "イベント駆動型ワークフロー",
  afterEvent: ".afterEvent()",
  resumeWithEvent: ".resumeWithEvent()",
  "step-retries": "ステップの再試行",
};
export default meta;