import {
  TABLE_WORKFLOW_SNAPSHOT,
  TABLE_MESSAGES,
  TABLE_THREADS,
  TABLE_TRACES,
  TABLE_RESOURCES,
  TABLE_SCORERS,
  TABLE_SPANS,
  TABLE_AGENTS,
  TABLE_AGENT_VERSIONS,
  TABLE_OBSERVATIONAL_MEMORY,
  TABLE_PROMPT_BLOCKS,
  TABLE_PROMPT_BLOCK_VERSIONS,
  TABLE_SCORER_DEFINITIONS,
  TABLE_SCORER_DEFINITION_VERSIONS,
  TABLE_MCP_CLIENTS,
  TABLE_MCP_CLIENT_VERSIONS,
  TABLE_MCP_SERVERS,
  TABLE_MCP_SERVER_VERSIONS,
  TABLE_WORKSPACES,
  TABLE_WORKSPACE_VERSIONS,
  TABLE_SKILLS,
  TABLE_SKILL_VERSIONS,
  TABLE_SKILL_BLOBS,
  TABLE_DATASETS,
  TABLE_DATASET_ITEMS,
  TABLE_DATASET_VERSIONS,
  TABLE_EXPERIMENTS,
  TABLE_EXPERIMENT_RESULTS,
  SCORERS_SCHEMA,
  OLD_SPAN_SCHEMA,
  AGENTS_SCHEMA,
  AGENT_VERSIONS_SCHEMA,
  PROMPT_BLOCKS_SCHEMA,
  PROMPT_BLOCK_VERSIONS_SCHEMA,
  SCORER_DEFINITIONS_SCHEMA,
  SCORER_DEFINITION_VERSIONS_SCHEMA,
  MCP_CLIENTS_SCHEMA,
  MCP_CLIENT_VERSIONS_SCHEMA,
  MCP_SERVERS_SCHEMA,
  MCP_SERVER_VERSIONS_SCHEMA,
  WORKSPACES_SCHEMA,
  WORKSPACE_VERSIONS_SCHEMA,
  SKILLS_SCHEMA,
  SKILL_VERSIONS_SCHEMA,
  SKILL_BLOBS_SCHEMA,
  OBSERVATIONAL_MEMORY_SCHEMA,
  DATASETS_SCHEMA,
  DATASET_ITEMS_SCHEMA,
  DATASET_VERSIONS_SCHEMA,
  EXPERIMENTS_SCHEMA,
  EXPERIMENT_RESULTS_SCHEMA,
  OBSERVATIONAL_MEMORY_TABLE_SCHEMA,
  TABLE_CONFIGS,
} from '@internal/core';
import type { TABLE_NAMES } from '@internal/core';
import { spanRecordSchema } from './domains/observability/types';
import { buildStorageSchema } from './types';
import type { StorageColumn } from './types';

// Import from @internal/core for local use + re-export

export {
  TABLE_WORKFLOW_SNAPSHOT,
  TABLE_MESSAGES,
  TABLE_THREADS,
  TABLE_TRACES,
  TABLE_RESOURCES,
  TABLE_SCORERS,
  TABLE_SPANS,
  TABLE_AGENTS,
  TABLE_AGENT_VERSIONS,
  TABLE_OBSERVATIONAL_MEMORY,
  TABLE_PROMPT_BLOCKS,
  TABLE_PROMPT_BLOCK_VERSIONS,
  TABLE_SCORER_DEFINITIONS,
  TABLE_SCORER_DEFINITION_VERSIONS,
  TABLE_MCP_CLIENTS,
  TABLE_MCP_CLIENT_VERSIONS,
  TABLE_MCP_SERVERS,
  TABLE_MCP_SERVER_VERSIONS,
  TABLE_WORKSPACES,
  TABLE_WORKSPACE_VERSIONS,
  TABLE_SKILLS,
  TABLE_SKILL_VERSIONS,
  TABLE_SKILL_BLOBS,
  TABLE_DATASETS,
  TABLE_DATASET_ITEMS,
  TABLE_DATASET_VERSIONS,
  TABLE_EXPERIMENTS,
  TABLE_EXPERIMENT_RESULTS,
  SCORERS_SCHEMA,
  OLD_SPAN_SCHEMA,
  AGENTS_SCHEMA,
  AGENT_VERSIONS_SCHEMA,
  PROMPT_BLOCKS_SCHEMA,
  PROMPT_BLOCK_VERSIONS_SCHEMA,
  SCORER_DEFINITIONS_SCHEMA,
  SCORER_DEFINITION_VERSIONS_SCHEMA,
  MCP_CLIENTS_SCHEMA,
  MCP_CLIENT_VERSIONS_SCHEMA,
  MCP_SERVERS_SCHEMA,
  MCP_SERVER_VERSIONS_SCHEMA,
  WORKSPACES_SCHEMA,
  WORKSPACE_VERSIONS_SCHEMA,
  SKILLS_SCHEMA,
  SKILL_VERSIONS_SCHEMA,
  SKILL_BLOBS_SCHEMA,
  OBSERVATIONAL_MEMORY_SCHEMA,
  DATASETS_SCHEMA,
  DATASET_ITEMS_SCHEMA,
  DATASET_VERSIONS_SCHEMA,
  EXPERIMENTS_SCHEMA,
  EXPERIMENT_RESULTS_SCHEMA,
  OBSERVATIONAL_MEMORY_TABLE_SCHEMA,
  TABLE_CONFIGS,
  type TABLE_NAMES,
};

// SPAN_SCHEMA depends on spanRecordSchema from the observability domain,
// which is specific to @mastra/core and cannot be extracted to @internal/core.
export const SPAN_SCHEMA = buildStorageSchema(spanRecordSchema);

/**
 * Schema definitions for all core tables.
 */
export const TABLE_SCHEMAS: Record<TABLE_NAMES, Record<string, StorageColumn>> = {
  mastra_workflow_snapshot: {
    workflow_name: { type: 'text' },
    run_id: { type: 'text' },
    resourceId: { type: 'text', nullable: true },
    snapshot: { type: 'jsonb' },
    createdAt: { type: 'timestamp' },
    updatedAt: { type: 'timestamp' },
  },
  mastra_scorers: SCORERS_SCHEMA,
  mastra_threads: {
    id: { type: 'text', nullable: false, primaryKey: true },
    resourceId: { type: 'text', nullable: false },
    title: { type: 'text', nullable: false },
    metadata: { type: 'jsonb', nullable: true },
    createdAt: { type: 'timestamp', nullable: false },
    updatedAt: { type: 'timestamp', nullable: false },
  },
  mastra_messages: {
    id: { type: 'text', nullable: false, primaryKey: true },
    thread_id: { type: 'text', nullable: false },
    content: { type: 'text', nullable: false },
    role: { type: 'text', nullable: false },
    type: { type: 'text', nullable: false },
    createdAt: { type: 'timestamp', nullable: false },
    resourceId: { type: 'text', nullable: true },
  },
  mastra_ai_spans: SPAN_SCHEMA,
  mastra_traces: {
    id: { type: 'text', nullable: false, primaryKey: true },
    parentSpanId: { type: 'text', nullable: true },
    name: { type: 'text', nullable: false },
    traceId: { type: 'text', nullable: false },
    scope: { type: 'text', nullable: false },
    kind: { type: 'integer', nullable: false },
    attributes: { type: 'jsonb', nullable: true },
    status: { type: 'jsonb', nullable: true },
    events: { type: 'jsonb', nullable: true },
    links: { type: 'jsonb', nullable: true },
    other: { type: 'text', nullable: true },
    startTime: { type: 'bigint', nullable: false },
    endTime: { type: 'bigint', nullable: false },
    createdAt: { type: 'timestamp', nullable: false },
  },
  mastra_resources: {
    id: { type: 'text', nullable: false, primaryKey: true },
    workingMemory: { type: 'text', nullable: true },
    metadata: { type: 'jsonb', nullable: true },
    createdAt: { type: 'timestamp', nullable: false },
    updatedAt: { type: 'timestamp', nullable: false },
  },
  mastra_agents: AGENTS_SCHEMA,
  mastra_agent_versions: AGENT_VERSIONS_SCHEMA,
  mastra_prompt_blocks: PROMPT_BLOCKS_SCHEMA,
  mastra_prompt_block_versions: PROMPT_BLOCK_VERSIONS_SCHEMA,
  mastra_scorer_definitions: SCORER_DEFINITIONS_SCHEMA,
  mastra_scorer_definition_versions: SCORER_DEFINITION_VERSIONS_SCHEMA,
  mastra_mcp_clients: MCP_CLIENTS_SCHEMA,
  mastra_mcp_client_versions: MCP_CLIENT_VERSIONS_SCHEMA,
  mastra_mcp_servers: MCP_SERVERS_SCHEMA,
  mastra_mcp_server_versions: MCP_SERVER_VERSIONS_SCHEMA,
  mastra_workspaces: WORKSPACES_SCHEMA,
  mastra_workspace_versions: WORKSPACE_VERSIONS_SCHEMA,
  mastra_skills: SKILLS_SCHEMA,
  mastra_skill_versions: SKILL_VERSIONS_SCHEMA,
  mastra_skill_blobs: SKILL_BLOBS_SCHEMA,
  mastra_datasets: DATASETS_SCHEMA,
  mastra_dataset_items: DATASET_ITEMS_SCHEMA,
  mastra_dataset_versions: DATASET_VERSIONS_SCHEMA,
  mastra_experiments: EXPERIMENTS_SCHEMA,
  mastra_experiment_results: EXPERIMENT_RESULTS_SCHEMA,
};
