services:
  db:
    image: postgres:13
    container_name: 'REPLACE_PROJECT_NAME-db'
    ports:
      - 'REPLACE_DB_PORT:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-kepler}
    volumes:
      - pgdata:/var/lib/postgresql/data
