services:
  db:
    image: clickhouse/clickhouse-server:latest
    container_name: 'clickhouse-test-db'
    ports:
      - '8123:8123'
      - '9000:9000'
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER: ${CLICKHOUSE_USER:-default}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD:-password}
    volumes:
      - clickhouse_data:/var/lib/clickhouse
volumes:
  clickhouse_data:
