// List of all codemods
export const BUNDLE = [
  'v1/mastra-core-imports',
  'v1/runtime-context',
  'v1/experimental-auth',
  'v1/agent-property-access',
  'v1/agent-voice',
  'v1/agent-processor-methods',
  'v1/agent-generate-stream-v-next',
  'v1/voice-property-names',
  'v1/agent-get-agents',
  'v1/evals-get-scorers',
  'v1/mcp-get-mcp-servers',
  'v1/mcp-get-tools',
  'v1/mcp-get-toolsets',
  'v1/workflows-get-workflows',
  'v1/agent-abort-signal',
  'v1/agent-format-parameter',
  'v1/agent-to-step',
  'v1/client-sdk-types',
  'v1/client-to-ai-sdk-format',
];
