// List of all codemods
export const BUNDLE = [
  'v1/mastra-core-imports',
  'v1/runtime-context',
  'v1/not-implemented/mastra-memory',
  'v1/mastra-plural-apis',
  'v1/not-implemented/mastra-required-id',
  'v1/agent-property-access',
  'v1/agent-voice',
  'v1/agent-processor-methods',
  'v1/agent-generate-stream-v-next',
  'v1/agent-abort-signal',
  'v1/not-implemented/agent-format-parameter',
  'v1/not-implemented/agent-to-step',
  'v1/voice-property-names',
  'v1/mcp-get-tools',
  'v1/mcp-get-toolsets',
  'v1/client-sdk-types',
  'v1/client-to-ai-sdk-format',
  'v1/client-offset-limit',
  'v1/client-get-memory-thread',
  'v1/experimental-auth',
];
