export const referenceSections: Record<
  string,
  Array<{ title: string; href: string }>
> = {
  Agents: [
    { title: "Agent", href: "/reference/agents/agent" },
    { title: "Generate", href: "/reference/agents/generate" },
    { title: "GenerateLegacy", href: "/reference/agents/generateLegacy" },
    {
      title: "GetDefaultGenerateOptions",
      href: "/reference/agents/getDefaultGenerateOptions",
    },
    {
      title: "GetDefaultStreamOptions",
      href: "/reference/agents/getDefaultStreamOptions",
    },
    { title: "GetDescription", href: "/reference/agents/getDescription" },
    {
      title: "GetInstructions",
      href: "/reference/agents/getInstructions",
    },
    { title: "GetLLM", href: "/reference/agents/getLLM" },
    { title: "GetMemory", href: "/reference/agents/getMemory" },
    { title: "GetModel", href: "/reference/agents/getModel" },
    { title: "GetScorers", href: "/reference/agents/getScorers" },
    { title: "GetTools", href: "/reference/agents/getTools" },
    { title: "GetVoice", href: "/reference/agents/getVoice" },
    { title: "GetWorkflows", href: "/reference/agents/getWorkflows" },
    { title: "ListAgents", href: "/reference/agents/listAgents" },
    { title: "Network", href: "/reference/agents/network" },
  ],
  Auth: [
    { title: "Auth0", href: "/reference/auth/auth0" },
    { title: "Clerk", href: "/reference/auth/clerk" },
    { title: "Firebase", href: "/reference/auth/firebase" },
    { title: "Jwt", href: "/reference/auth/jwt" },
    { title: "Supabase", href: "/reference/auth/supabase" },
    { title: "Workos", href: "/reference/auth/workos" },
  ],
  CLI: [
    { title: "Create Mastra", href: "/reference/cli/create-mastra" },
    { title: "Mastra", href: "/reference/cli/mastra" },
  ],
  "Client SDK": [
    { title: "Agents", href: "/reference/client-js/agents" },
    {
      title: "Error Handling",
      href: "/reference/client-js/error-handling",
    },
    { title: "Logs", href: "/reference/client-js/logs" },
    { title: "Mastra Client", href: "/reference/client-js/mastra-client" },
    { title: "Memory", href: "/reference/client-js/memory" },
    { title: "Observability", href: "/reference/client-js/observability" },
    { title: "Tools", href: "/reference/client-js/tools" },
    { title: "Vectors", href: "/reference/client-js/vectors" },
    {
      title: "Workflows Legacy",
      href: "/reference/client-js/workflows-legacy",
    },
    { title: "Workflows", href: "/reference/client-js/workflows" },
  ],
  Core: [
    { title: "GetAgent", href: "/reference/core/getAgent" },
    { title: "GetAgentById", href: "/reference/core/getAgentById" },
    { title: "GetAgents", href: "/reference/core/getAgents" },
    { title: "GetDeployer", href: "/reference/core/getDeployer" },
    { title: "GetLogger", href: "/reference/core/getLogger" },
    { title: "GetLogs", href: "/reference/core/getLogs" },
    { title: "GetLogsByRunId", href: "/reference/core/getLogsByRunId" },
    { title: "GetMCPServer", href: "/reference/core/getMCPServer" },
    { title: "GetMCPServers", href: "/reference/core/getMCPServers" },
    { title: "GetMemory", href: "/reference/core/getMemory" },
    { title: "GetScorer", href: "/reference/core/getScorer" },
    { title: "GetScorerByName", href: "/reference/core/getScorerByName" },
    { title: "GetScorers", href: "/reference/core/getScorers" },
    { title: "GetServer", href: "/reference/core/getServer" },
    { title: "GetStorage", href: "/reference/core/getStorage" },
    { title: "GetVector", href: "/reference/core/getVector" },
    { title: "GetVectors", href: "/reference/core/getVectors" },
    { title: "GetWorkflow", href: "/reference/core/getWorkflow" },
    { title: "GetWorkflows", href: "/reference/core/getWorkflows" },
    { title: "Mastra Class", href: "/reference/core/mastra-class" },
    { title: "SetLogger", href: "/reference/core/setLogger" },
    { title: "SetStorage", href: "/reference/core/setStorage" },
  ],
  Deployer: [
    { title: "Cloudflare", href: "/reference/deployer/cloudflare" },
    { title: "Deployer", href: "/reference/deployer/" },
    { title: "Netlify", href: "/reference/deployer/netlify" },
    { title: "Vercel", href: "/reference/deployer/vercel" },
  ],
  Evals: [
    {
      title: "Answer Relevancy",
      href: "/reference/evals/answer-relevancy",
    },
    { title: "Bias", href: "/reference/evals/bias" },
    { title: "Completeness", href: "/reference/evals/completeness" },
    {
      title: "Content Similarity",
      href: "/reference/evals/content-similarity",
    },
    {
      title: "Context Position",
      href: "/reference/evals/context-position",
    },
    {
      title: "Context Precision",
      href: "/reference/evals/context-precision",
    },
    {
      title: "Context Relevancy",
      href: "/reference/evals/context-relevancy",
    },
    {
      title: "Contextual Recall",
      href: "/reference/evals/contextual-recall",
    },
    { title: "Faithfulness", href: "/reference/evals/faithfulness" },
    { title: "Hallucination", href: "/reference/evals/hallucination" },
    {
      title: "Keyword Coverage",
      href: "/reference/evals/keyword-coverage",
    },
    {
      title: "Prompt Alignment",
      href: "/reference/evals/prompt-alignment",
    },
    { title: "Summarization", href: "/reference/evals/summarization" },
    {
      title: "Textual Difference",
      href: "/reference/evals/textual-difference",
    },
    {
      title: "Tone Consistency",
      href: "/reference/evals/tone-consistency",
    },
    { title: "Toxicity", href: "/reference/evals/toxicity" },
  ],
  "Legacy Workflows": [
    { title: "After", href: "/reference/legacyWorkflows/after" },
    { title: "AfterEvent", href: "/reference/legacyWorkflows/afterEvent" },
    { title: "Commit", href: "/reference/legacyWorkflows/commit" },
    { title: "CreateRun", href: "/reference/legacyWorkflows/createRun" },
    { title: "Else", href: "/reference/legacyWorkflows/else" },
    { title: "Events", href: "/reference/legacyWorkflows/events" },
    { title: "Execute", href: "/reference/legacyWorkflows/execute" },
    { title: "If", href: "/reference/legacyWorkflows/if" },
    { title: "Resume", href: "/reference/legacyWorkflows/resume" },
    {
      title: "ResumeWithEvent",
      href: "/reference/legacyWorkflows/resumeWithEvent",
    },
    { title: "Snapshots", href: "/reference/legacyWorkflows/snapshots" },
    { title: "Start", href: "/reference/legacyWorkflows/start" },
    { title: "Step Class", href: "/reference/legacyWorkflows/step-class" },
    {
      title: "Step Condition",
      href: "/reference/legacyWorkflows/step-condition",
    },
    {
      title: "Step Function",
      href: "/reference/legacyWorkflows/step-function",
    },
    {
      title: "Step Options",
      href: "/reference/legacyWorkflows/step-options",
    },
    {
      title: "Step Retries",
      href: "/reference/legacyWorkflows/step-retries",
    },
    { title: "Suspend", href: "/reference/legacyWorkflows/suspend" },
    { title: "Then", href: "/reference/legacyWorkflows/then" },
    { title: "Until", href: "/reference/legacyWorkflows/until" },
    { title: "Watch", href: "/reference/legacyWorkflows/watch" },
    { title: "While", href: "/reference/legacyWorkflows/while" },
    { title: "Workflow", href: "/reference/legacyWorkflows/workflow" },
  ],
  Memory: [
    { title: "Memory", href: "/reference/memory/memory-class" },
    { title: "CreateThread", href: "/reference/memory/createThread" },
    { title: "DeleteMessages", href: "/reference/memory/deleteMessages" },
    { title: "GetThreadById", href: "/reference/memory/getThreadById" },
    {
      title: "GetThreadsByResourceId",
      href: "/reference/memory/getThreadsByResourceId",
    },
    {
      title: "GetThreadsByResourceIdPaginated",
      href: "/reference/memory/getThreadsByResourceIdPaginated",
    },
    { title: "Query", href: "/reference/memory/query" },
  ],
  Observability: [
    {
      title: "Ai Tracing",
      href: "/reference/observability/ai-tracing/",
    },
    {
      title: "Configuration",
      href: "/reference/observability/ai-tracing/configuration",
    },
    {
      title: "Braintrust",
      href: "/reference/observability/ai-tracing/exporters/braintrust",
    },
    {
      title: "Cloud Exporter",
      href: "/reference/observability/ai-tracing/exporters/cloud-exporter",
    },
    {
      title: "Console Exporter",
      href: "/reference/observability/ai-tracing/exporters/console-exporter",
    },
    {
      title: "Default Exporter",
      href: "/reference/observability/ai-tracing/exporters/default-exporter",
    },
    {
      title: "Langfuse",
      href: "/reference/observability/ai-tracing/exporters/langfuse",
    },
    {
      title: "Langsmith",
      href: "/reference/observability/ai-tracing/exporters/langsmith",
    },
    {
      title: "Otel",
      href: "/reference/observability/ai-tracing/exporters/otel",
    },
    {
      title: "Interfaces",
      href: "/reference/observability/ai-tracing/interfaces",
    },
    {
      title: "Sensitive Data Filter",
      href: "/reference/observability/ai-tracing/processors/sensitive-data-filter",
    },
    { title: "Span", href: "/reference/observability/ai-tracing/span" },
    {
      title: "Pino Logger",
      href: "/reference/observability/logging/pino-logger",
    },
    {
      title: "Otel Config",
      href: "/reference/observability/otel-tracing/otel-config",
    },
    {
      title: "Arize Ax",
      href: "/reference/observability/otel-tracing/providers/arize-ax",
    },
    {
      title: "Arize Phoenix",
      href: "/reference/observability/otel-tracing/providers/arize-phoenix",
    },
    {
      title: "Braintrust",
      href: "/reference/observability/otel-tracing/providers/braintrust",
    },
    {
      title: "Dash0",
      href: "/reference/observability/otel-tracing/providers/dash0",
    },
    {
      title: "Keywordsai",
      href: "/reference/observability/otel-tracing/providers/keywordsai",
    },
    {
      title: "Laminar",
      href: "/reference/observability/otel-tracing/providers/laminar",
    },
    {
      title: "Langfuse",
      href: "/reference/observability/otel-tracing/providers/langfuse",
    },
    {
      title: "Langsmith",
      href: "/reference/observability/otel-tracing/providers/langsmith",
    },
    {
      title: "Langwatch",
      href: "/reference/observability/otel-tracing/providers/langwatch",
    },
    {
      title: "New Relic",
      href: "/reference/observability/otel-tracing/providers/new-relic",
    },
    {
      title: "Signoz",
      href: "/reference/observability/otel-tracing/providers/signoz",
    },
    {
      title: "Traceloop",
      href: "/reference/observability/otel-tracing/providers/traceloop",
    },
  ],
  Processors: [
    {
      title: "Batch Parts Processor",
      href: "/reference/processors/batch-parts-processor",
    },
    {
      title: "Language Detector",
      href: "/reference/processors/language-detector",
    },
    {
      title: "Moderation Processor",
      href: "/reference/processors/moderation-processor",
    },
    { title: "Pii Detector", href: "/reference/processors/pii-detector" },
    {
      title: "Prompt Injection Detector",
      href: "/reference/processors/prompt-injection-detector",
    },
    {
      title: "System Prompt Scrubber",
      href: "/reference/processors/system-prompt-scrubber",
    },
    {
      title: "Token Limiter Processor",
      href: "/reference/processors/token-limiter-processor",
    },
    {
      title: "Unicode Normalizer",
      href: "/reference/processors/unicode-normalizer",
    },
  ],
  RAG: [
    { title: "Chunk", href: "/reference/rag/chunk" },
    { title: "Database Config", href: "/reference/rag/database-config" },
    { title: "Document", href: "/reference/rag/document" },
    { title: "Embeddings", href: "/reference/rag/embeddings" },
    { title: "Extract Params", href: "/reference/rag/extract-params" },
    { title: "Graph Rag", href: "/reference/rag/graph-rag" },
    { title: "Metadata Filters", href: "/reference/rag/metadata-filters" },
    { title: "Rerank", href: "/reference/rag/rerank" },
    { title: "RerankWithScorer", href: "/reference/rag/rerankWithScorer" },
  ],
  Scorers: [
    {
      title: "Answer Relevancy",
      href: "/reference/scorers/answer-relevancy",
    },
    {
      title: "Answer Similarity",
      href: "/reference/scorers/answer-similarity",
    },
    { title: "Bias", href: "/reference/scorers/bias" },
    { title: "Completeness", href: "/reference/scorers/completeness" },
    {
      title: "Content Similarity",
      href: "/reference/scorers/content-similarity",
    },
    {
      title: "Context Precision",
      href: "/reference/scorers/context-precision",
    },
    {
      title: "Context Relevance",
      href: "/reference/scorers/context-relevance",
    },
    { title: "Create Scorer", href: "/reference/scorers/create-scorer" },
    { title: "Faithfulness", href: "/reference/scorers/faithfulness" },
    { title: "Hallucination", href: "/reference/scorers/hallucination" },
    {
      title: "Keyword Coverage",
      href: "/reference/scorers/keyword-coverage",
    },
    { title: "Mastra Scorer", href: "/reference/scorers/mastra-scorer" },
    {
      title: "Noise Sensitivity",
      href: "/reference/scorers/noise-sensitivity",
    },
    {
      title: "Prompt Alignment",
      href: "/reference/scorers/prompt-alignment",
    },
    { title: "Run Experiment", href: "/reference/scorers/run-experiment" },
    {
      title: "Textual Difference",
      href: "/reference/scorers/textual-difference",
    },
    {
      title: "Tone Consistency",
      href: "/reference/scorers/tone-consistency",
    },
    {
      title: "Tool Call Accuracy",
      href: "/reference/scorers/tool-call-accuracy",
    },
    { title: "Toxicity", href: "/reference/scorers/toxicity" },
  ],
  Storage: [
    { title: "Cloudflare D1", href: "/reference/storage/cloudflare-d1" },
    { title: "Cloudflare", href: "/reference/storage/cloudflare" },
    { title: "Dynamodb", href: "/reference/storage/dynamodb" },
    { title: "Lance", href: "/reference/storage/lance" },
    { title: "Libsql", href: "/reference/storage/libsql" },
    { title: "Mssql", href: "/reference/storage/mssql" },
    { title: "Postgresql", href: "/reference/storage/postgresql" },
    { title: "Upstash", href: "/reference/storage/upstash" },
  ],
  Streaming: [
    { title: "ChunkType", href: "/reference/streaming/ChunkType" },
    {
      title: "MastraModelOutput",
      href: "/reference/streaming/agents/MastraModelOutput",
    },
    { title: "Stream", href: "/reference/streaming/agents/stream" },
    {
      title: "StreamLegacy",
      href: "/reference/streaming/agents/streamLegacy",
    },
    {
      title: "ObserveStream",
      href: "/reference/streaming/workflows/observeStream",
    },
    {
      title: "ObserveStreamVNext",
      href: "/reference/streaming/workflows/observeStreamVNext",
    },
    {
      title: "ResumeStreamVNext",
      href: "/reference/streaming/workflows/resumeStreamVNext",
    },
    { title: "Stream", href: "/reference/streaming/workflows/stream" },
    {
      title: "StreamVNext",
      href: "/reference/streaming/workflows/streamVNext",
    },
  ],
  Templates: [{ title: "Overview", href: "/reference/templates/overview" }],
  "Tools & MCP": [
    { title: "Client", href: "/reference/tools/client" },
    { title: "Create Tool", href: "/reference/tools/create-tool" },
    {
      title: "Document Chunker Tool",
      href: "/reference/tools/document-chunker-tool",
    },
    { title: "Graph Rag Tool", href: "/reference/tools/graph-rag-tool" },
    { title: "Mcp Client", href: "/reference/tools/mcp-client" },
    { title: "Mcp Server", href: "/reference/tools/mcp-server" },
    {
      title: "Vector Query Tool",
      href: "/reference/tools/vector-query-tool",
    },
  ],
  Networks: [
    { title: "Astra", href: "/reference/vectors/astra" },
    { title: "Chroma", href: "/reference/vectors/chroma" },
    { title: "Couchbase", href: "/reference/vectors/couchbase" },
    { title: "Lance", href: "/reference/vectors/lance" },
    { title: "Libsql", href: "/reference/vectors/libsql" },
    { title: "Mongodb", href: "/reference/vectors/mongodb" },
    { title: "Opensearch", href: "/reference/vectors/opensearch" },
    { title: "Pg", href: "/reference/vectors/pg" },
    { title: "Pinecone", href: "/reference/vectors/pinecone" },
    { title: "Qdrant", href: "/reference/vectors/qdrant" },
    { title: "S3vectors", href: "/reference/vectors/s3vectors" },
    { title: "Turbopuffer", href: "/reference/vectors/turbopuffer" },
    { title: "Upstash", href: "/reference/vectors/upstash" },
    { title: "Vectorize", href: "/reference/vectors/vectorize" },
  ],
  Voice: [
    { title: "Azure", href: "/reference/voice/azure" },
    { title: "Cloudflare", href: "/reference/voice/cloudflare" },
    { title: "Composite Voice", href: "/reference/voice/composite-voice" },
    { title: "Deepgram", href: "/reference/voice/deepgram" },
    { title: "Elevenlabs", href: "/reference/voice/elevenlabs" },
    {
      title: "Google Gemini Live",
      href: "/reference/voice/google-gemini-live",
    },
    { title: "Google", href: "/reference/voice/google" },
    { title: "Mastra Voice", href: "/reference/voice/mastra-voice" },
    { title: "Murf", href: "/reference/voice/murf" },
    { title: "Openai Realtime", href: "/reference/voice/openai-realtime" },
    { title: "Openai", href: "/reference/voice/openai" },
    { title: "Playai", href: "/reference/voice/playai" },
    { title: "Sarvam", href: "/reference/voice/sarvam" },
    { title: "Speechify", href: "/reference/voice/speechify" },
    {
      title: "Voice.addInstructions",
      href: "/reference/voice/voice.addInstructions",
    },
    { title: "Voice.addTools", href: "/reference/voice/voice.addTools" },
    { title: "Voice.answer", href: "/reference/voice/voice.answer" },
    { title: "Voice.close", href: "/reference/voice/voice.close" },
    { title: "Voice.connect", href: "/reference/voice/voice.connect" },
    { title: "Voice.events", href: "/reference/voice/voice.events" },
    {
      title: "Voice.getSpeakers",
      href: "/reference/voice/voice.getSpeakers",
    },
    { title: "Voice.listen", href: "/reference/voice/voice.listen" },
    { title: "Voice.off", href: "/reference/voice/voice.off" },
    { title: "Voice.on", href: "/reference/voice/voice.on" },
    { title: "Voice.send", href: "/reference/voice/voice.send" },
    { title: "Voice.speak", href: "/reference/voice/voice.speak" },
    {
      title: "Voice.updateConfig",
      href: "/reference/voice/voice.updateConfig",
    },
  ],
  Workflows: [
    { title: "Cancel", href: "/reference/workflows/run-methods/cancel" },
    { title: "Resume", href: "/reference/workflows/run-methods/resume" },
    { title: "Start", href: "/reference/workflows/run-methods/start" },
    { title: "Watch", href: "/reference/workflows/run-methods/watch" },
    { title: "Run", href: "/reference/workflows/run" },
    { title: "Step", href: "/reference/workflows/step" },
    {
      title: "Branch",
      href: "/reference/workflows/workflow-methods/branch",
    },
    {
      title: "Commit",
      href: "/reference/workflows/workflow-methods/commit",
    },
    {
      title: "Create Run",
      href: "/reference/workflows/workflow-methods/create-run",
    },
    {
      title: "Dountil",
      href: "/reference/workflows/workflow-methods/dountil",
    },
    {
      title: "Dowhile",
      href: "/reference/workflows/workflow-methods/dowhile",
    },
    {
      title: "Foreach",
      href: "/reference/workflows/workflow-methods/foreach",
    },
    { title: "Map", href: "/reference/workflows/workflow-methods/map" },
    {
      title: "Parallel",
      href: "/reference/workflows/workflow-methods/parallel",
    },
    {
      title: "SendEvent",
      href: "/reference/workflows/workflow-methods/sendEvent",
    },
    {
      title: "Sleep",
      href: "/reference/workflows/workflow-methods/sleep",
    },
    {
      title: "SleepUntil",
      href: "/reference/workflows/workflow-methods/sleepUntil",
    },
    { title: "Then", href: "/reference/workflows/workflow-methods/then" },
    {
      title: "WaitForEvent",
      href: "/reference/workflows/workflow-methods/waitForEvent",
    },
    { title: "Workflow", href: "/reference/workflows/workflow" },
  ],
};

export const sectionTitles = [
  "Agents",
  "Auth",
  "CLI",
  "Client SDK",
  "Core",
  "Deployer",
  "Evals",
  "Legacy Workflows",
  "Memory",
  "Observability",
  "Processors",
  "RAG",
  "Scorers",
  "Storage",
  "Streaming",
  "Templates",
  "Tools & MCP",
  "Networks",
  "Voice",
  "Workflows",
];
