/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Docs sidebar - main documentation
  docsSidebar: [
    "index",
    {
      type: "category",
      label: "Getting Started",
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Agents",
      items: [{ type: "autogenerated", dirName: "agents" }],
    },
    {
      type: "category",
      label: "Workflows",
      items: [{ type: "autogenerated", dirName: "workflows" }],
    },
    {
      type: "category",
      label: "Streaming",
      items: [{ type: "autogenerated", dirName: "streaming" }],
    },
    {
      type: "category",
      label: "Tools & MCP",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "tools-mcp" }],
    },
    {
      type: "category",
      label: "Memory",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "memory" }],
    },
    {
      type: "category",
      label: "RAG",
      items: [{ type: "autogenerated", dirName: "rag" }],
    },
    {
      type: "category",
      label: "Server & DB",
      items: [{ type: "autogenerated", dirName: "server-db" }],
    },
    {
      type: "category",
      label: "Deployment",
      items: [{ type: "autogenerated", dirName: "deployment" }],
    },
    {
      type: "category",
      label: "Mastra Cloud",
      items: [{ type: "autogenerated", dirName: "mastra-cloud" }],
    },
    {
      type: "category",
      label: "Observability",
      items: [{ type: "autogenerated", dirName: "observability" }],
    },
    {
      type: "category",
      label: "Scorers",
      items: [{ type: "autogenerated", dirName: "scorers" }],
    },
    {
      type: "category",
      label: "Auth",
      items: [{ type: "autogenerated", dirName: "auth" }],
    },
    {
      type: "category",
      label: "Voice",
      items: [{ type: "autogenerated", dirName: "voice" }],
    },
    {
      type: "category",
      label: "Frameworks",
      items: [{ type: "autogenerated", dirName: "frameworks" }],
    },
    {
      type: "category",
      label: "Community",
      items: [{ type: "autogenerated", dirName: "community" }],
    },
  ],

  // Guides sidebar
  guidesSidebar: [{ type: "autogenerated", dirName: "guides" }],

  // Examples sidebar
  examplesSidebar: [{ type: "autogenerated", dirName: "examples" }],

  // Reference sidebar
  referenceSidebar: [{ type: "autogenerated", dirName: "reference" }],

  // Models sidebar
  modelsSidebar: [{ type: "autogenerated", dirName: "models" }],
};

export default sidebars;
