export interface StoreOption {
  value: string;
  label: string;
  hint?: string;
  package: string;
  className: string;
  envVar?: string;
  defaultUrl?: string;
  hasStorage: boolean;
  hasVector: boolean;
}

export const FULL_STORAGE_OPTIONS: StoreOption[] = [
  {
    value: 'libsql',
    label: 'LibSQL',
    hint: 'SQLite-compatible, file-based (default)',
    package: '@mastra/libsql',
    className: 'LibSQLStore',
    envVar: undefined,
    defaultUrl: 'file:./mastra.db',
    hasStorage: true,
    hasVector: true,
  },
  {
    value: 'pg',
    label: 'PostgreSQL',
    hint: 'with pgvector',
    package: '@mastra/pg',
    className: 'PGStore',
    envVar: 'POSTGRES_URL',
    defaultUrl: 'postgresql://localhost:5432/mastra',
    hasStorage: true,
    hasVector: true,
  },
  {
    value: 'mongodb',
    label: 'MongoDB',
    hint: 'with Atlas Vector Search',
    package: '@mastra/mongodb',
    className: 'MongoDBStore',
    envVar: 'MONGODB_URI',
    defaultUrl: 'mongodb://localhost:27017/mastra',
    hasStorage: true,
    hasVector: true,
  },
  {
    value: 'lance',
    label: 'Lance',
    hint: 'Columnar format for ML/AI',
    package: '@mastra/lance',
    className: 'LanceStore',
    envVar: 'LANCE_DB_PATH',
    defaultUrl: './lance.db',
    hasStorage: true,
    hasVector: true,
  },
  {
    value: 'upstash',
    label: 'Upstash',
    hint: 'Serverless Redis',
    package: '@mastra/upstash',
    className: 'UpstashStore',
    envVar: 'UPSTASH_REDIS_URL',
    defaultUrl: 'https://your-upstash-url.upstash.io',
    hasStorage: true,
    hasVector: true,
  },
  {
    value: 'duckdb',
    label: 'DuckDB',
    hint: 'Embedded OLAP with HNSW',
    package: '@mastra/duckdb',
    className: 'DuckDBStore',
    envVar: undefined,
    defaultUrl: './mastra.duckdb',
    hasStorage: true,
    hasVector: true,
  },
  {
    value: 'convex',
    label: 'Convex',
    hint: 'Real-time backend',
    package: '@mastra/convex',
    className: 'ConvexStore',
    envVar: 'CONVEX_URL',
    defaultUrl: 'https://your-project.convex.cloud',
    hasStorage: true,
    hasVector: true,
  },
];

export const DB_ONLY_OPTIONS: StoreOption[] = [
  {
    value: 'clickhouse',
    label: 'ClickHouse',
    hint: 'OLAP for analytics',
    package: '@mastra/clickhouse',
    className: 'ClickhouseStore',
    envVar: 'CLICKHOUSE_URL',
    defaultUrl: 'http://localhost:8123',
    hasStorage: true,
    hasVector: false,
  },
  {
    value: 'cloudflare-d1',
    label: 'Cloudflare D1',
    hint: 'Edge SQLite',
    package: '@mastra/cloudflare-d1',
    className: 'CloudflareD1Store',
    envVar: 'CLOUDFLARE_ACCOUNT_ID',
    defaultUrl: 'your-database-id',
    hasStorage: true,
    hasVector: false,
  },
  {
    value: 'dsql',
    label: 'Amazon Aurora DSQL',
    hint: 'Serverless PostgreSQL',
    package: '@mastra/dsql',
    className: 'DSQLStore',
    envVar: 'DSQL_ENDPOINT',
    defaultUrl: 'your-dsql-endpoint.aws.com',
    hasStorage: true,
    hasVector: false,
  },
  {
    value: 'dynamodb',
    label: 'DynamoDB',
    hint: 'AWS NoSQL',
    package: '@mastra/dynamodb',
    className: 'DynamoDBStore',
    envVar: 'AWS_REGION',
    defaultUrl: 'us-east-1',
    hasStorage: true,
    hasVector: false,
  },
  {
    value: 'mssql',
    label: 'Microsoft SQL Server',
    hint: 'Enterprise RDBMS',
    package: '@mastra/mssql',
    className: 'MSSQLStore',
    envVar: 'MSSQL_CONNECTION_STRING',
    defaultUrl: 'Server=localhost;Database=mastra;User Id=sa;Password=yourStrong(!)Password;',
    hasStorage: true,
    hasVector: false,
  },
  {
    value: 'redis',
    label: 'Redis',
    hint: 'In-memory key-value',
    package: '@mastra/redis',
    className: 'RedisStore',
    envVar: 'REDIS_URL',
    defaultUrl: 'redis://localhost:6379',
    hasStorage: true,
    hasVector: false,
  },
  {
    value: 'spanner',
    label: 'Google Cloud Spanner',
    hint: 'Global distributed SQL',
    package: '@mastra/spanner',
    className: 'SpannerStore',
    envVar: 'SPANNER_INSTANCE',
    defaultUrl: 'projects/your-project/instances/your-instance/databases/your-database',
    hasStorage: true,
    hasVector: false,
  },
];

export const VECTOR_ONLY_OPTIONS: StoreOption[] = [
  {
    value: 'pinecone',
    label: 'Pinecone',
    hint: 'Managed vector database',
    package: '@mastra/pinecone',
    className: 'PineconeStore',
    envVar: 'PINECONE_API_KEY',
    defaultUrl: 'your-api-key',
    hasStorage: false,
    hasVector: true,
  },
  {
    value: 'qdrant',
    label: 'Qdrant',
    hint: 'Vector search engine',
    package: '@mastra/qdrant',
    className: 'QdrantStore',
    envVar: 'QDRANT_URL',
    defaultUrl: 'http://localhost:6333',
    hasStorage: false,
    hasVector: true,
  },
  {
    value: 'chroma',
    label: 'Chroma',
    hint: 'AI-native embeddings',
    package: '@mastra/chroma',
    className: 'ChromaStore',
    envVar: 'CHROMA_URL',
    defaultUrl: 'http://localhost:8000',
    hasStorage: false,
    hasVector: true,
  },
  {
    value: 'astra',
    label: 'DataStax Astra',
    hint: 'Cassandra-based',
    package: '@mastra/astra',
    className: 'AstraStore',
    envVar: 'ASTRA_DB_APPLICATION_TOKEN',
    defaultUrl: 'your-token',
    hasStorage: false,
    hasVector: true,
  },
  {
    value: 'couchbase',
    label: 'Couchbase',
    hint: 'NoSQL with vector search',
    package: '@mastra/couchbase',
    className: 'CouchbaseStore',
    envVar: 'COUCHBASE_CONNECTION_STRING',
    defaultUrl: 'couchbase://localhost',
    hasStorage: false,
    hasVector: true,
  },
  {
    value: 'elasticsearch',
    label: 'Elasticsearch',
    hint: 'Search and analytics',
    package: '@mastra/elasticsearch',
    className: 'ElasticsearchStore',
    envVar: 'ELASTICSEARCH_URL',
    defaultUrl: 'http://localhost:9200',
    hasStorage: false,
    hasVector: true,
  },
  {
    value: 'opensearch',
    label: 'OpenSearch',
    hint: 'Open-source search',
    package: '@mastra/opensearch',
    className: 'OpenSearchStore',
    envVar: 'OPENSEARCH_URL',
    defaultUrl: 'http://localhost:9200',
    hasStorage: false,
    hasVector: true,
  },
  {
    value: 's3vectors',
    label: 'Amazon S3 Vectors',
    hint: 'S3-backed vectors',
    package: '@mastra/s3vectors',
    className: 'S3VectorsStore',
    envVar: 'AWS_S3_BUCKET',
    defaultUrl: 'your-bucket-name',
    hasStorage: false,
    hasVector: true,
  },
  {
    value: 'turbopuffer',
    label: 'Turbopuffer',
    hint: 'Fast vector search',
    package: '@mastra/turbopuffer',
    className: 'TurbopufferStore',
    envVar: 'TURBOPUFFER_API_KEY',
    defaultUrl: 'your-api-key',
    hasStorage: false,
    hasVector: true,
  },
  {
    value: 'vectorize',
    label: 'Cloudflare Vectorize',
    hint: 'Edge vector search',
    package: '@mastra/vectorize',
    className: 'VectorizeStore',
    envVar: 'CLOUDFLARE_ACCOUNT_ID',
    defaultUrl: 'your-account-id',
    hasStorage: false,
    hasVector: true,
  },
];

export const OBSERVABILITY_STORAGE_OPTIONS: StoreOption[] = [
  {
    value: 'duckdb',
    label: 'DuckDB',
    hint: 'Embedded OLAP (recommended for dev/low-volume)',
    package: '@mastra/duckdb',
    className: 'DuckDBStore',
    envVar: undefined,
    defaultUrl: './mastra.duckdb',
    hasStorage: true,
    hasVector: true,
  },
  {
    value: 'clickhouse',
    label: 'ClickHouse',
    hint: 'Recommended for production',
    package: '@mastra/clickhouse',
    className: 'ClickhouseStore',
    envVar: 'CLICKHOUSE_URL',
    defaultUrl: 'http://localhost:8123',
    hasStorage: true,
    hasVector: false,
  },
  {
    value: 'pg',
    label: 'PostgreSQL',
    hint: 'Use for low-volume only',
    package: '@mastra/pg',
    className: 'PGStore',
    envVar: 'POSTGRES_URL',
    defaultUrl: 'postgresql://localhost:5432/mastra',
    hasStorage: true,
    hasVector: true,
  },
  {
    value: 'mongodb',
    label: 'MongoDB',
    hint: 'Use for low-volume only',
    package: '@mastra/mongodb',
    className: 'MongoDBStore',
    envVar: 'MONGODB_URI',
    defaultUrl: 'mongodb://localhost:27017/mastra',
    hasStorage: true,
    hasVector: true,
  },
  {
    value: 'dsql',
    label: 'Amazon Aurora DSQL',
    hint: 'Use for low-volume only',
    package: '@mastra/dsql',
    className: 'DSQLStore',
    envVar: 'DSQL_ENDPOINT',
    defaultUrl: 'your-dsql-endpoint.aws.com',
    hasStorage: true,
    hasVector: false,
  },
  {
    value: 'mssql',
    label: 'Microsoft SQL Server',
    hint: 'Use for low-volume only',
    package: '@mastra/mssql',
    className: 'MSSQLStore',
    envVar: 'MSSQL_CONNECTION_STRING',
    defaultUrl: 'Server=localhost;Database=mastra;User Id=sa;Password=yourStrong(!)Password;',
    hasStorage: true,
    hasVector: false,
  },
  {
    value: 'spanner',
    label: 'Google Cloud Spanner',
    hint: 'Use for low-volume only',
    package: '@mastra/spanner',
    className: 'SpannerStore',
    envVar: 'SPANNER_INSTANCE',
    defaultUrl: 'projects/your-project/instances/your-instance/databases/your-database',
    hasStorage: true,
    hasVector: false,
  },
];

export const ALL_STORAGE_OPTIONS = [...FULL_STORAGE_OPTIONS, ...DB_ONLY_OPTIONS];
export const ALL_VECTOR_OPTIONS = [...FULL_STORAGE_OPTIONS, ...VECTOR_ONLY_OPTIONS];

export function getStoreOption(value: string): StoreOption | undefined {
  return [...FULL_STORAGE_OPTIONS, ...DB_ONLY_OPTIONS, ...VECTOR_ONLY_OPTIONS, ...OBSERVABILITY_STORAGE_OPTIONS].find(
    opt => opt.value === value,
  );
}

export function hasVectorSupport(storageValue: string): boolean {
  const option = getStoreOption(storageValue);
  return option?.hasVector ?? false;
}

export function hasStorageSupport(storageValue: string): boolean {
  const option = getStoreOption(storageValue);
  return option?.hasStorage ?? false;
}
