#!/usr/bin/env tsx

import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { existsSync, readFileSync, realpathSync, writeFileSync } from 'node:fs';
import { mkdir } from 'node:fs/promises';
import { basename, join, relative, resolve } from 'node:path';
import process from 'node:process';
import { pathToFileURL } from 'node:url';

const START = '<!-- mastra-knowledge-reference:start -->';
const END = '<!-- mastra-knowledge-reference:end -->';
const REFERENCE_FILES = [
  'configuration.md',
  'access.md',
  'records.md',
  'imports.md',
  'capture.md',
  'curation.md',
  'ui.md',
];
const REFERENCE_ANCHORS: Record<string, string> = {
  configuration: 'configuration',
  access: 'access-and-scopes',
  records: 'nodes-and-records',
  imports: 'importers',
  capture: 'capture',
  curation: 'curation',
  ui: 'knowledge-ui',
};

export interface SyncOfficialSkillsOptions {
  sourceRoot: string;
  targetRoot: string;
  check: boolean;
  release?: boolean;
  sourceCommit?: string;
  sourceDate?: string;
}

function replaceManagedSection(content: string, section: string): string {
  const managed = `${START}\n${section.trim()}\n${END}`;
  const start = content.indexOf(START);
  const end = content.indexOf(END);
  if (start === -1 && end === -1) return `${content.trimEnd()}\n\n${managed}\n`;
  if (start === -1 || end === -1 || end < start) throw new Error('Malformed Mastra Knowledge sync markers.');
  return `${content.slice(0, start)}${managed}${content.slice(end + END.length)}`;
}

function gitOutput(cwd: string, args: string[]): string {
  return execFileSync('git', args, { cwd, encoding: 'utf8' }).trim();
}

function gitValue(sourceRoot: string, format: string): string {
  return gitOutput(sourceRoot, ['show', '-s', `--format=${format}`, 'HEAD']);
}

function withoutFrontmatter(markdown: string): string {
  return markdown.replace(/^---\n[\s\S]*?\n---\n+/, '');
}

export async function syncOfficialSkills(options: SyncOfficialSkillsOptions): Promise<void> {
  const sourceDir = join(options.sourceRoot, 'packages/core/src/knowledge/skill');
  const targetSkillDir = join(options.targetRoot, 'skills/mastra');
  const targetReference = join(targetSkillDir, 'references/knowledge.md');
  const targetSkill = join(targetSkillDir, 'SKILL.md');
  const targetReadme = join(options.targetRoot, 'README.md');

  for (const path of [
    join(sourceDir, 'SKILL.md'),
    ...REFERENCE_FILES.map(file => join(sourceDir, 'references', file)),
  ]) {
    if (!existsSync(path)) throw new Error(`Missing Knowledge skill source: ${relative(options.sourceRoot, path)}`);
  }
  for (const path of [targetSkill, targetReadme]) {
    if (!existsSync(path)) throw new Error(`Missing official skills repository file: ${path}`);
  }

  const fixtureMode = Boolean(options.sourceCommit && options.sourceDate);
  if (!fixtureMode) {
    if (!options.check && !options.release) {
      throw new Error('Official skill writes require the release-gated sync command.');
    }
    if (gitOutput(options.sourceRoot, ['status', '--porcelain'])) {
      throw new Error('Commit the Mastra checkout before generating exact provenance.');
    }

    const targetTopLevel = realpathSync(resolve(gitOutput(options.targetRoot, ['rev-parse', '--show-toplevel'])));
    if (targetTopLevel !== realpathSync(resolve(options.targetRoot))) {
      throw new Error(`Target must be the official skills repository root: ${targetTopLevel}`);
    }
    const remote = gitOutput(options.targetRoot, ['remote', 'get-url', 'origin']);
    if (
      !/^(?:git@github\.com:|https:\/\/github\.com\/|ssh:\/\/git@github\.com\/)mastra-ai\/skills(?:\.git)?$/.test(
        remote,
      )
    ) {
      throw new Error(`Target is not the official mastra-ai/skills checkout: ${remote}`);
    }
    if (!options.check && gitOutput(options.targetRoot, ['status', '--porcelain'])) {
      throw new Error('The official skills checkout must be clean before synchronization.');
    }
  }

  const sourceParts = [
    withoutFrontmatter(readFileSync(join(sourceDir, 'SKILL.md'), 'utf8')),
    ...REFERENCE_FILES.map(file => readFileSync(join(sourceDir, 'references', file), 'utf8')),
  ];
  const sourceHash = createHash('sha256').update(sourceParts.join('\n')).digest('hex');
  const sourceCommit = options.sourceCommit ?? gitValue(options.sourceRoot, '%H');
  const sourceDate = options.sourceDate ?? gitValue(options.sourceRoot, '%cI');
  const body = `${sourceParts
    .join('\n\n')
    .replaceAll(/\.\/references\/([a-z-]+)\.md/g, (_link, name: string) => {
      const anchor = REFERENCE_ANCHORS[name];
      if (!anchor) throw new Error(`Missing generated anchor mapping for ${name}.md`);
      return `#${anchor}`;
    })
    .trim()}\n`;
  const bodyHash = createHash('sha256').update(body).digest('hex');
  const generated = `<!-- Generated by scripts/sync-official-skills.ts. Do not edit directly. -->\n<!-- source-commit: ${sourceCommit} -->\n<!-- source-date: ${sourceDate} -->\n<!-- source-path: packages/core/src/knowledge/skill -->\n<!-- source-sha256: ${sourceHash} -->\n<!-- generated-body-sha256: ${bodyHash} -->\n\n${body}`;

  if (!options.check && existsSync(targetReference)) {
    const current = readFileSync(targetReference, 'utf8');
    const declaredHash = current.match(/^<!-- generated-body-sha256: ([a-f0-9]{64}) -->$/m)?.[1];
    const bodyStart = current.indexOf('\n\n');
    const currentBodyHash =
      bodyStart === -1
        ? undefined
        : createHash('sha256')
            .update(current.slice(bodyStart + 2))
            .digest('hex');
    if (!declaredHash || declaredHash !== currentBodyHash) {
      throw new Error('Refusing to overwrite a manually edited official Knowledge reference.');
    }
  }

  const nextSkill = replaceManagedSection(
    readFileSync(targetSkill, 'utf8'),
    '## Knowledge\n\nFor scoped, durable application knowledge, read [Knowledge](references/knowledge.md).',
  );
  const nextReadme = replaceManagedSection(
    readFileSync(targetReadme, 'utf8'),
    'The Mastra skill includes a generated [Knowledge reference](skills/mastra/references/knowledge.md) for configuration, access, capture, curation, and operations.',
  );
  const outputs = new Map([
    [targetReference, generated],
    [targetSkill, nextSkill],
    [targetReadme, nextReadme],
  ]);
  const drift = [...outputs].filter(([path, expected]) => !existsSync(path) || readFileSync(path, 'utf8') !== expected);

  if (options.check) {
    if (drift.length) {
      throw new Error(
        `Official skill drift detected:\n${drift.map(([path]) => `- ${relative(options.targetRoot, path)}`).join('\n')}`,
      );
    }
    console.info(`Official Knowledge skill is synchronized (${sourceCommit.slice(0, 12)}).`);
    return;
  }

  for (const [path, content] of outputs) {
    await mkdir(resolve(path, '..'), { recursive: true });
    writeFileSync(path, content);
  }
  console.info(`Synchronized Knowledge guidance to ${basename(options.targetRoot)} (${sourceCommit.slice(0, 12)}).`);
}

export function parseArgs(argv: string[]): SyncOfficialSkillsOptions {
  const value = (name: string) => {
    const index = argv.indexOf(name);
    if (index === -1) return undefined;
    const argument = argv[index + 1];
    if (!argument || argument.startsWith('--')) throw new Error(`${name} requires a value.`);
    return argument;
  };
  const targetRoot = value('--target') ?? process.env.MASTRA_SKILLS_REPO;
  if (!targetRoot) throw new Error('Pass --target <mastra-ai/skills checkout> or set MASTRA_SKILLS_REPO.');
  return {
    sourceRoot: resolve(value('--source') ?? process.cwd()),
    targetRoot: resolve(targetRoot),
    check: argv.includes('--check'),
    release: argv.includes('--release'),
  };
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? '').href) {
  syncOfficialSkills(parseArgs(process.argv.slice(2))).catch(error => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
