const meta = {
  "mastra-voice": "Mastra Voice",
  "composite-voice": "Composite Voice",
  "voice.speak": ".speak()",
  "voice.listen": ".listen()",
  "voice.getSpeakers": ".getSpeakers()",
  "voice.connect": ".connect()",
  "voice.send": ".send()",
  "voice.answer": ".answer()",
  "voice.on": ".on()",
  "voice.events": "events",
  "voice.off": ".off()",
  "voice.close": ".close()",
  "voice.addInstructions": ".addInstructions()",
  "voice.addTools": ".addTools()",
  "voice.updateConfig": ".updateConfig()",
  deepgram: "Deepgram",
  elevenlabs: "ElevenLabs",
  google: "Google",
  "google-gemini-live": "Google Gemini Live",
  murf: "Murf",
  openai: "OpenAI",
  "openai-realtime": "OpenAI Realtime",
  playai: "PlayAI",
  sarvam: "Sarvam",
  speechify: "Speechify",
  azure: "Azure",
  cloudflare: "Cloudflare",
};

export default meta;
