/**
 * Auto-generated Drizzle schema for Mastra tables.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Regenerate with: pnpm generate:drizzle
 *
 * @generated
 */
import { sqliteTable, type AnySQLiteColumn, text, numeric, real } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
import { relations } from 'drizzle-orm/relations';

export interface MastraSchemaConfig {
  /** Prefix for all table names (e.g., 'prod_' -> 'prod_mastra_threads') */
  tablePrefix?: string;
}

export function createMastraSchema(config?: MastraSchemaConfig) {
  const tablePrefix = config?.tablePrefix ?? '';
  const tableName = (name: string) => `${tablePrefix}${name}`;
  const mastraThreads = sqliteTable(tableName('mastra_threads'), {
    id: text().primaryKey().notNull(),
    resourceId: text().notNull(),
    title: text().notNull(),
    metadata: text(),
    createdAt: numeric().notNull(),
    updatedAt: numeric().notNull(),
  });

  const mastraMessages = sqliteTable(tableName('mastra_messages'), {
    id: text().primaryKey().notNull(),
    threadId: text('thread_id').notNull(),
    content: text().notNull(),
    role: text().notNull(),
    type: text().notNull(),
    createdAt: numeric().notNull(),
    resourceId: text(),
  });

  const mastraResources = sqliteTable(tableName('mastra_resources'), {
    id: text().primaryKey().notNull(),
    workingMemory: text(),
    metadata: text(),
    createdAt: numeric().notNull(),
    updatedAt: numeric().notNull(),
  });

  const mastraScorers = sqliteTable(tableName('mastra_scorers'), {
    id: text().primaryKey().notNull(),
    scorerId: text(),
    traceId: text(),
    spanId: text(),
    runId: text(),
    scorer: text(),
    preprocessStepResult: text(),
    extractStepResult: text(),
    analyzeStepResult: text(),
    score: real(),
    reason: text(),
    metadata: text(),
    preprocessPrompt: text(),
    extractPrompt: text(),
    generateScorePrompt: text(),
    generateReasonPrompt: text(),
    analyzePrompt: text(),
    reasonPrompt: text(),
    input: text(),
    output: text(),
    additionalContext: text(),
    requestContext: text(),
    entityType: text(),
    entity: text(),
    entityId: text(),
    source: text(),
    resourceId: text(),
    threadId: text(),
    createdAt: numeric(),
    updatedAt: numeric(),
  });

  const mastraWorkflowSnapshot = sqliteTable(tableName('mastra_workflow_snapshot'), {
    workflowName: text('workflow_name'),
    runId: text('run_id'),
    resourceId: text(),
    snapshot: text(),
    createdAt: numeric(),
    updatedAt: numeric(),
  });
  return { mastraThreads, mastraMessages, mastraResources, mastraScorers, mastraWorkflowSnapshot };
}

/** Type representing all Mastra tables. Use for compile-time safety. */
export type MastraSchema = ReturnType<typeof createMastraSchema>;

/**
 * Create Drizzle relations for the Mastra schema.
 * Pass the schema from createMastraSchema() to get typed relations.
 */
export function createMastraRelations(schema: MastraSchema) {
  const {} = schema;

  return {};
}

/** Type representing Mastra relations. */
export type MastraRelations = ReturnType<typeof createMastraRelations>;
