import { writeFileSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildApiSchemaManifest } from '../src/server/server-adapter/api-schema-manifest';

const rootDir = resolve(dirname(fileURLToPath(import.meta.url)), '../../..');
const outputPath = resolve(rootDir, join('packages', 'cli', 'src', 'commands', 'api', 'route-metadata.generated.ts'));

const apiSchemaManifest = buildApiSchemaManifest();

const metadata = Object.fromEntries(
  apiSchemaManifest.routes.map(route => [
    `${route.method} ${route.path}`,
    {
      method: route.method,
      path: route.path,
      pathParams: extractPathParams(route.path),
      queryParams: extractSchemaProperties(route.queryParamSchema),
      bodyParams: extractSchemaProperties(route.bodySchema),
      hasQuery: Boolean(route.queryParamSchema),
      hasBody: Boolean(route.bodySchema),
      responseShape: route.responseShape,
    },
  ]),
);

writeFileSync(
  outputPath,
  `// This file is generated by packages/server/scripts/generate-api-cli-route-metadata.ts. Do not edit by hand.\n\n` +
    `export const API_ROUTE_METADATA = ${JSON.stringify(metadata, null, 2)} as const;\n`,
);

function extractPathParams(path: string): string[] {
  return [...path.matchAll(/:([A-Za-z0-9_]+)/g)]
    .map(match => match[1])
    .filter((value): value is string => Boolean(value));
}

function extractSchemaProperties(
  schema: { properties?: unknown; anyOf?: unknown; oneOf?: unknown; allOf?: unknown } | undefined,
): string[] {
  if (!schema) return [];
  const keys = new Set<string>();
  collectSchemaProperties(schema, keys);
  return [...keys].sort();
}

function collectSchemaProperties(
  schema: { properties?: unknown; anyOf?: unknown; oneOf?: unknown; allOf?: unknown },
  keys: Set<string>,
): void {
  if (schema.properties && typeof schema.properties === 'object' && !Array.isArray(schema.properties)) {
    for (const key of Object.keys(schema.properties)) keys.add(key);
  }
  for (const field of ['anyOf', 'oneOf', 'allOf'] as const) {
    const variants = schema[field];
    if (!Array.isArray(variants)) continue;
    for (const variant of variants) {
      if (variant && typeof variant === 'object' && !Array.isArray(variant)) {
        collectSchemaProperties(
          variant as { properties?: unknown; anyOf?: unknown; oneOf?: unknown; allOf?: unknown },
          keys,
        );
      }
    }
  }
}
