/**
 * Shared permission generation logic.
 *
 * This module derives permissions from SERVER_ROUTES and generates the
 * TypeScript content for permissions.generated.ts.
 *
 * Used by both generate-permissions.ts and check-permissions.ts.
 */

import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import { SERVER_ROUTES } from '../src/server/server-adapter/routes/index.js';
import { extractResource, deriveAction } from '../src/server/server-adapter/routes/permissions.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/** Path to the generated permissions file in @mastra/core */
export const OUTPUT_PATH = path.join(__dirname, '../../core/src/auth/interfaces/permissions.generated.ts');

/** Studio-specific resources that don't have routes but are used in role definitions */
const STUDIO_RESOURCES = ['studio', 'users', 'settings'];

/** Studio-specific actions not derived from HTTP methods */
const STUDIO_ACTIONS = ['admin', 'invite'];

export interface PermissionData {
  resources: string[];
  actions: string[];
  permissions: string[];
}

/**
 * Derives permission data from SERVER_ROUTES.
 */
export function derivePermissionData(): PermissionData {
  const resourceSet = new Set<string>();
  const permissionSet = new Set<string>();

  for (const route of SERVER_ROUTES) {
    // Skip routes with ALL method (MCP transports)
    if (route.method === 'ALL') continue;

    const resource = extractResource(route.path);
    if (resource) {
      resourceSet.add(resource);
      const action = deriveAction(route.method, route.path);
      permissionSet.add(`${resource}:${action}`);
    }
  }

  // Add Studio-specific resources
  for (const resource of STUDIO_RESOURCES) {
    resourceSet.add(resource);
  }

  const resources = [...resourceSet].sort();

  // Actions: derive from routes + add Studio-specific actions
  const routeActions = new Set<string>();
  for (const route of SERVER_ROUTES) {
    if (route.method !== 'ALL') {
      routeActions.add(deriveAction(route.method, route.path));
    }
  }
  const actions = [...new Set([...routeActions, ...STUDIO_ACTIONS])].sort();

  // Generate all permission combinations (resource x action matrix)
  // This ensures all valid combinations exist for wildcards to work correctly
  for (const resource of resources) {
    for (const action of actions) {
      permissionSet.add(`${resource}:${action}`);
    }
  }

  const permissions = [...permissionSet].sort();

  return { resources, actions, permissions };
}

/**
 * Generates the TypeScript file content from permission data.
 */
export function generatePermissionFileContent(data: PermissionData): string {
  const { resources, actions, permissions } = data;

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is generated by packages/server/scripts/generate-permissions.ts
 * Run \`pnpm generate:permissions\` from packages/server to regenerate.
 *
 * Source of truth: SERVER_ROUTES in @mastra/server
 */

/**
 * All known API resources.
 * Derived from SERVER_ROUTES paths in @mastra/server.
 */
export const RESOURCES = [
${resources.map(r => `  '${r}',`).join('\n')}
] as const;

/**
 * Resource type union.
 */
export type Resource = (typeof RESOURCES)[number];

/**
 * All permission actions.
 * Derived from METHOD_TO_ACTION mapping:
 * - GET → read
 * - POST → write or execute (context-dependent)
 * - PUT/PATCH → write
 * - DELETE → delete
 * Plus Studio-specific actions: admin, invite
 */
export const ACTIONS = [${actions.map(a => `'${a}'`).join(', ')}] as const;

/**
 * Action type union.
 */
export type Action = (typeof ACTIONS)[number];

/**
 * All valid resource:action permission combinations.
 */
export const PERMISSIONS = [
${permissions.map(p => `  '${p}',`).join('\n')}
] as const;

/**
 * Specific permission type (e.g., 'agents:read', 'workflows:execute').
 */
export type Permission = (typeof PERMISSIONS)[number];

/**
 * Permission pattern that can be used in role definitions.
 * Supports:
 * - Specific permissions: 'agents:read', 'workflows:execute'
 * - Resource wildcards: 'agents:*', 'workflows:*' (all actions on a resource)
 * - Action wildcards: '*:read', '*:write' (an action across all resources)
 * - Global wildcard: '*' (full access)
 */
export type PermissionPattern = Permission | '*' | \`\${Resource}:*\` | \`*:\${Action}\`;

/**
 * Type-safe role mapping configuration.
 *
 * Maps role names (from your identity provider) to Mastra permission patterns.
 *
 * @example
 * \`\`\`typescript
 * const roleMapping: TypedRoleMapping = {
 *   "Engineering": ["agents:*", "workflows:*"],
 *   "Product": ["agents:read", "workflows:read"],
 *   "Admin": ["*"],
 *   "_default": [],
 * };
 * \`\`\`
 */
export type TypedRoleMapping = {
  [role: string]: PermissionPattern[];
};

/**
 * Validates that a string is a valid permission pattern.
 * Useful for runtime validation of permission strings.
 */
export function isValidPermissionPattern(pattern: string): pattern is PermissionPattern {
  if (pattern === '*') return true;
  // Resource wildcard: 'agents:*'
  if (pattern.endsWith(':*')) {
    const resource = pattern.slice(0, -2);
    return (RESOURCES as readonly string[]).includes(resource);
  }
  // Action wildcard: '*:read'
  if (pattern.startsWith('*:')) {
    const action = pattern.slice(2);
    return (ACTIONS as readonly string[]).includes(action);
  }
  return (PERMISSIONS as readonly string[]).includes(pattern);
}

/**
 * Validates that all permissions in an array are valid patterns.
 */
export function validatePermissions(permissions: string[]): permissions is PermissionPattern[] {
  return permissions.every(isValidPermissionPattern);
}
`;
}
