/**
 * Shared permission generation logic.
 *
 * This module derives permissions from SERVER_ROUTES and generates the
 * TypeScript content for permissions.generated.ts.
 *
 * Used by both generate-permissions.ts and check-permissions.ts.
 */

import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

import { SERVER_ROUTES } from '../src/server/server-adapter/routes/index.js';
import { getEffectivePermission } from '../src/server/server-adapter/routes/permissions.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/** Path to the generated permissions file in @mastra/core */
export const OUTPUT_PATH = path.join(__dirname, '../../core/src/auth/interfaces/permissions.generated.ts');

export interface PermissionData {
  resources: string[];
  actions: string[];
  permissions: string[];
}

/**
 * Derives permission data from SERVER_ROUTES using getEffectivePermission.
 * This ensures the generated permissions match runtime behavior exactly.
 */
export function derivePermissionData(): PermissionData {
  const resourceSet = new Set<string>();
  const actionSet = new Set<string>();
  const permissionSet = new Set<string>();

  for (const route of SERVER_ROUTES) {
    const permission = getEffectivePermission(route);
    if (permission) {
      const [resource, action] = permission.split(':');
      if (resource && action) {
        resourceSet.add(resource);
        actionSet.add(action);
        permissionSet.add(permission);
      }
    }
  }

  const resources = [...resourceSet].sort();
  const actions = [...actionSet].sort();
  const permissions = [...permissionSet].sort();

  return { resources, actions, permissions };
}

/**
 * Generates the TypeScript file content from permission data.
 */
export function generatePermissionFileContent(data: PermissionData): string {
  const { resources, actions, permissions } = data;

  // Build all permission patterns (wildcards + specific permissions)
  const allPatterns: string[] = [
    '*', // Global wildcard
    ...actions.map(a => `*:${a}`), // Action wildcards
    ...resources.map(r => `${r}:*`), // Resource wildcards
    ...permissions, // Specific permissions
  ];

  // Generate the PERMISSION_PATTERNS object entries
  const patternEntries = allPatterns.map(pattern => `  '${pattern}': '${pattern}'`).join(',\n');

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is generated by packages/server/scripts/generate-permissions.ts
 * Run \`pnpm generate:permissions\` from packages/server to regenerate.
 *
 * Source of truth: SERVER_ROUTES in @mastra/server
 */

/**
 * All known API resources.
 * Derived from SERVER_ROUTES paths in @mastra/server.
 */
export const RESOURCES = [
${resources.map(r => `  '${r}',`).join('\n')}
] as const;

/**
 * Resource type union.
 */
export type Resource = (typeof RESOURCES)[number];

/**
 * All permission actions.
 * Derived from HTTP methods and route overrides:
 * - GET → read
 * - POST → write or execute (context-dependent)
 * - PUT/PATCH → write
 * - DELETE → delete
 * - Additional actions from explicit requiresPermission overrides
 */
export const ACTIONS = [${actions.map(a => `'${a}'`).join(', ')}] as const;

/**
 * Action type union.
 */
export type Action = (typeof ACTIONS)[number];

/**
 * All valid permission patterns.
 * Use \`keyof typeof PERMISSION_PATTERNS\` or the \`PermissionPattern\` type.
 */
export const PERMISSION_PATTERNS = {
${patternEntries},
} as const;

/**
 * Permission pattern that can be used in role definitions.
 * Supports:
 * - Specific permissions: 'agents:read', 'workflows:execute'
 * - Resource wildcards: 'agents:*', 'workflows:*' (all actions on a resource)
 * - Action wildcards: '*:read', '*:write' (an action across all resources)
 * - Global wildcard: '*' (full access)
 */
export type PermissionPattern = keyof typeof PERMISSION_PATTERNS;

/**
 * All valid resource:action permission combinations (excludes wildcards).
 */
export const PERMISSIONS = [
${permissions.map(p => `  '${p}',`).join('\n')}
] as const;

/**
 * Specific permission type (e.g., 'agents:read', 'workflows:execute').
 */
export type Permission = (typeof PERMISSIONS)[number];

/**
 * Type-safe role mapping configuration.
 *
 * Maps role names (from your identity provider) to Mastra permission patterns.
 *
 * @example
 * \`\`\`typescript
 * const roleMapping: TypedRoleMapping = {
 *   "Engineering": ["agents:*", "workflows:*"],
 *   "Product": ["agents:read", "workflows:read"],
 *   "Admin": ["*"],
 *   "_default": [],
 * };
 * \`\`\`
 */
export type TypedRoleMapping = {
  [role: string]: PermissionPattern[];
};

/**
 * Validates that a string is a valid permission pattern.
 * Useful for runtime validation of permission strings.
 */
export function isValidPermissionPattern(pattern: string): pattern is PermissionPattern {
  return pattern in PERMISSION_PATTERNS;
}

/**
 * Validates that all permissions in an array are valid patterns.
 */
export function validatePermissions(permissions: string[]): permissions is PermissionPattern[] {
  return permissions.every(isValidPermissionPattern);
}
`;
}
