/**
 * Auto-generated Drizzle schema for Mastra tables.
 *
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Regenerate with: pnpm generate:drizzle
 *
 * @generated
 */
import { sqliteTable, type AnySQLiteColumn, text, uniqueIndex, integer, real } from 'drizzle-orm/sqlite-core';
import { sql } from 'drizzle-orm';
import { relations } from 'drizzle-orm/relations';

export function createMastraSchema() {
  const mastraAgents = sqliteTable('mastra_agents', {
    id: text().primaryKey().notNull(),
    name: text().notNull(),
    description: text(),
    instructions: text().notNull(),
    model: text().notNull(),
    tools: text(),
    defaultOptions: text(),
    workflows: text(),
    agents: text(),
    inputProcessors: text(),
    outputProcessors: text(),
    memory: text(),
    scorers: text(),
    metadata: text(),
    createdAt: text().notNull(),
    updatedAt: text().notNull(),
  });

  const mastraThreads = sqliteTable('mastra_threads', {
    id: text().primaryKey().notNull(),
    resourceId: text().notNull(),
    title: text().notNull(),
    metadata: text(),
    createdAt: text().notNull(),
    updatedAt: text().notNull(),
  });

  const mastraMessages = sqliteTable('mastra_messages', {
    id: text().primaryKey().notNull(),
    threadId: text('thread_id').notNull(),
    content: text().notNull(),
    role: text().notNull(),
    type: text().notNull(),
    createdAt: text().notNull(),
    resourceId: text(),
  });

  const mastraResources = sqliteTable('mastra_resources', {
    id: text().primaryKey().notNull(),
    workingMemory: text(),
    metadata: text(),
    createdAt: text().notNull(),
    updatedAt: text().notNull(),
  });

  const mastraAiSpans = sqliteTable(
    'mastra_ai_spans',
    {
      traceId: text().notNull(),
      spanId: text().notNull(),
      name: text().notNull(),
      spanType: text().notNull(),
      isEvent: integer().notNull(),
      startedAt: text().notNull(),
      parentSpanId: text(),
      entityType: text(),
      entityId: text(),
      entityName: text(),
      userId: text(),
      organizationId: text(),
      resourceId: text(),
      runId: text(),
      sessionId: text(),
      threadId: text(),
      requestId: text(),
      environment: text(),
      source: text(),
      serviceName: text(),
      scope: text(),
      metadata: text(),
      tags: text(),
      attributes: text(),
      links: text(),
      input: text(),
      output: text(),
      error: text(),
      endedAt: text(),
      createdAt: text().notNull(),
      updatedAt: text(),
    },
    table => [uniqueIndex('mastra_ai_spans_spanid_traceid_idx').on(table.spanId, table.traceId)],
  );

  const mastraScorers = sqliteTable('mastra_scorers', {
    id: text().primaryKey().notNull(),
    scorerId: text(),
    traceId: text(),
    spanId: text(),
    runId: text(),
    scorer: text(),
    preprocessStepResult: text(),
    extractStepResult: text(),
    analyzeStepResult: text(),
    score: real(),
    reason: text(),
    metadata: text(),
    preprocessPrompt: text(),
    extractPrompt: text(),
    generateScorePrompt: text(),
    generateReasonPrompt: text(),
    analyzePrompt: text(),
    reasonPrompt: text(),
    input: text(),
    output: text(),
    additionalContext: text(),
    requestContext: text(),
    entityType: text(),
    entity: text(),
    entityId: text(),
    source: text(),
    resourceId: text(),
    threadId: text(),
    createdAt: text(),
    updatedAt: text(),
  });

  const mastraWorkflowSnapshot = sqliteTable('mastra_workflow_snapshot', {
    workflowName: text('workflow_name'),
    runId: text('run_id'),
    resourceId: text(),
    snapshot: text(),
    createdAt: text(),
    updatedAt: text(),
  });
  return {
    mastraAgents,
    mastraThreads,
    mastraMessages,
    mastraResources,
    mastraAiSpans,
    mastraScorers,
    mastraWorkflowSnapshot,
  };
}

/** Type representing all Mastra tables. Use for compile-time safety. */
export type MastraSchema = ReturnType<typeof createMastraSchema>;

/**
 * Create Drizzle relations for the Mastra schema.
 * Pass the schema from createMastraSchema() to get typed relations.
 */
export function createMastraRelations(schema: MastraSchema) {
  const {} = schema;

  return {};
}

/** Type representing Mastra relations. */
export type MastraRelations = ReturnType<typeof createMastraRelations>;
