import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { Command } from 'commander';

import { API_COMMANDS, registerApiCommand } from '../src/commands/api/index.js';

registerApiCommand(new Command());

const operations = Object.values(API_COMMANDS).map(command => ({
  name: command.name.replaceAll(' ', '_').replaceAll('-', '_'),
  description: command.description,
  method: command.method,
  path: command.path,
  ...(command.verbose ? { verbosePath: command.verbose.path } : {}),
  destructive: command.name.includes(' delete') || command.name.includes(' cancel'),
}));

const output = `// This file is generated by packages/cli/scripts/generate-mcp-api-operations.ts. Do not edit by hand.

export const MASTRA_API_OPERATIONS = ${JSON.stringify(operations, null, 2)} as const;
`;

const outputPath = path.resolve(import.meta.dirname, '../../mcp/src/server/mastra-api-operations.generated.ts');
await writeFile(outputPath, output);
