name: Turbo Changed
description: |
  Detect if a package's task inputs have changed using Turborepo's task hash comparison.
  This respects the `inputs` configuration in turbo.json, so files excluded from task inputs
  (like *.md files) won't trigger a change detection.

inputs:
  package:
    description: 'The package to check for changes (e.g., @mastra/rag)'
    required: true
  tasks:
    description: 'Comma-separated list of tasks to check (e.g., build:lib,test)'
    required: false
    default: 'build,test'
  base-ref:
    description: 'The base ref to compare against (e.g., origin/main)'
    required: false
    default: 'origin/main'

outputs:
  changed:
    description: 'Whether any of the specified task inputs changed (true/false)'
    value: ${{ steps.compare.outputs.changed }}

runs:
  using: composite
  steps:
    - name: Compare turbo task hashes
      id: compare
      shell: bash
      run: |
        set -e
        set -o pipefail

        PACKAGE="${{ inputs.package }}"
        TASKS="${{ inputs.tasks }}"
        BASE_REF="${{ inputs.base-ref }}"

        # Get task hash for a specific package and task
        # Uses turbo's dry-run to get the computed hash based on task inputs
        get_task_hash() {
          local task=$1
          pnpm turbo "$task" --filter="$PACKAGE" --dry-run=json 2>/dev/null | \
            jq -r ".tasks[] | select(.package == \"$PACKAGE\" and .task == \"$task\") | .hash"
        }

        # Save current ref to return to later
        CURRENT_REF=$(git rev-parse HEAD)

        # Initialize results
        declare -A HEAD_HASHES
        declare -A BASE_HASHES
        CHANGED=false

        # Convert comma-separated tasks to array
        IFS=',' read -ra TASK_ARRAY <<< "$TASKS"

        # Get current HEAD hashes
        echo "Getting task hashes for HEAD ($CURRENT_REF)..."
        for task in "${TASK_ARRAY[@]}"; do
          task=$(echo "$task" | xargs)  # trim whitespace
          hash=$(get_task_hash "$task")
          
          # Validate hash is non-empty
          if [ -z "$hash" ] || [ "$hash" = "null" ]; then
            echo "::error::Failed to get hash for task '$task' in package '$PACKAGE' at ref $CURRENT_REF. Check that the task exists in turbo.json and the package name is correct."
            exit 1
          fi
          
          HEAD_HASHES["$task"]="$hash"
          echo "  $task: $hash"
        done

        # Get base branch hashes
        echo "Getting task hashes for $BASE_REF..."
        git checkout "$BASE_REF" --quiet 2>/dev/null || {
          echo "Warning: Could not checkout $BASE_REF, fetching..."
          git fetch origin "${BASE_REF#origin/}" --quiet
          git checkout "$BASE_REF" --quiet
        }

        for task in "${TASK_ARRAY[@]}"; do
          task=$(echo "$task" | xargs)  # trim whitespace
          hash=$(get_task_hash "$task")
          
          # Validate hash is non-empty
          if [ -z "$hash" ] || [ "$hash" = "null" ]; then
            echo "::error::Failed to get hash for task '$task' in package '$PACKAGE' at ref $BASE_REF. Check that the task exists in turbo.json and the package name is correct."
            exit 1
          fi
          
          BASE_HASHES["$task"]="$hash"
          echo "  $task: $hash"
        done

        # Return to original ref
        git checkout "$CURRENT_REF" --quiet

        # Compare hashes
        echo ""
        echo "Comparing hashes..."
        for task in "${TASK_ARRAY[@]}"; do
          task=$(echo "$task" | xargs)  # trim whitespace
          head_hash="${HEAD_HASHES[$task]}"
          base_hash="${BASE_HASHES[$task]}"
          
          if [ "$head_hash" != "$base_hash" ]; then
            echo "  $task: CHANGED"
            CHANGED=true
          else
            echo "  $task: unchanged"
          fi
        done

        echo ""
        echo "changed=$CHANGED" >> $GITHUB_OUTPUT
