version: '3.8'
services:
  libsql:
    image: ghcr.io/tursodatabase/libsql-server:latest
    ports:
      - "8080:8080"
    environment:
      LIBSQL_DATABASE_URL: file:local.db
    volumes:
      - libsql_data:/var/lib/libsql

volumes:
  libsql_data:
