name: Publish

on:
  workflow_call:
    inputs:
      dry-run:
        description: 'Include --dry-run argument'
        type: boolean
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          always-auth: true
          registry-url: https://npm.pkg.github.com

      - run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc

      - name: Setup Environment
        run: |
          echo "DB_URL=postgres://postgres:postgres@localhost:5432/postgres?schema=arkwright" >> packages/core/.env

      - name: Install `pnpm`
        run: npm install -g pnpm

      - name: Install Modules
        run: pnpm install --frozen-lockfile

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm -r publish \
            --no-git-checks \
            --filter "./packages/**/*" \
            ${{ inputs.dry-run && '--dry-run' || '' }}
