name: GH_Issue_Triage
on:
  issues:
    types: [opened, reopened]

jobs:
  issue_created:
    # Only run on the main repository, not on forks
    if: ${{ github.repository == 'mastra-ai/mastra' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.1
          cache: "pnpm"

      - name: Install dependencies
        run: npm install
        working-directory: scripts/gh-issue-triage

      - name: Label Issue
        run: npx tsx index.ts
        working-directory: scripts/gh-issue-triage
        env:
          GITHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          MASTRA_BASE_URL: "https://few-substantial-engine.mastra.cloud"
