name: Website link checker
on: [deployment_status]

permissions:
  contents: read

jobs:
  link-checker-docs:
    name: Run link checker
    if: false # disable this for now, model router added like 1000 links and its making this take forever and hogging up CI runners. most people also ignore failures in this anyway
    # if: ${{ github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview – mastra-docs' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.19.5'
          registry-url: 'https://registry.yarnpkg.com'
      - name: Check links
        run: npx --force --ignore-engine github:wardpeet/broken-link-checker ${{ github.event.deployment_status.target_url }}/docs -roef

  validate-redirects:
    name: Validate next.config.mjs redirects
    if: ${{ github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Preview – mastra-docs' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.19.5'
          cache: 'npm'

      - name: Install dependencies for docs
        run: npm ci --registry=https://registry.yarnpkg.com
        working-directory: docs

      - name: Set deployment URL as env var
        run: echo "MASTRA_DEPLOYMENT_URL=${{ github.event.deployment_status.target_url }}" >> $GITHUB_ENV

      - name: Run validate-redirects
        run: node .github/scripts/validate-redirects.js
