name: Publish

on:
  push:
    branches:
      - main
  pull_request: # TODO: Remove before merging
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          token: '${{ github.NPM_TOKEN }}'
          always-auth: 'true'

      - name: Setup Environment
        run: |
          echo "DB_URL=postgres://postgres:postgres@localhost:5432/postgres?schema=arkwright" >> packages/core/.env

      - name: Install `pnpm`
        run: npm install -g pnpm

      - name: Install Modules
        run: pnpm install --frozen-lockfile

      - name: Publish
        run: pnpm publish --dry-run --no-git-checks --filter "./packages/**/*"
