name: Publish

on:
  push:
    branches:
      - main
  pull_request: # TODO: Remove before merging
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          token: '${{ github.NPM_TOKEN }}'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Publish
        run: pnpm publish --dry-run --no-git-checks --filter "./packages/**/*" # TODO: Remove dry-run before merging


