name: Regenerate Provider Registry

permissions:
  contents: write

on:
  # Run daily to keep provider registry up-to-date
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  regenerate:
    # Only run on the main repository, not on forks
    if: ${{ github.repository == 'mastra-ai/mastra' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          # Use default token for direct commits to main
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure npm registry
        run: mkdir -p ~/setup-pnpm && echo "registry=https://registry.yarnpkg.com" > ~/setup-pnpm/.npmrc

      - uses: wardpeet/action-setup@pnpm-registry
        name: Install pnpm
        with:
          registry: https://registry.yarnpkg.com
          run_install: false

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.1
          cache: 'pnpm'
          registry-url: 'https://registry.yarnpkg.com'

      - name: Install dependencies
        run: pnpm install

      - name: Generate provider registry
        run: pnpm --filter @mastra/core generate:providers

      - name: Format generated files with Prettier
        run: |
          prettier --write packages/core/src/llm/model/provider-registry.json
          prettier --write packages/core/src/llm/model/provider-types.generated.d.ts

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code packages/core/src/llm/model/provider-registry.json packages/core/src/llm/model/provider-types.generated.d.ts || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Create changeset
        if: steps.git-check.outputs.changed == 'true'
        run: |
          # Generate a unique changeset filename
          CHANGESET_ID="automated-provider-registry-$(date +%Y%m%d)"
          CHANGESET_FILE=".changeset/${CHANGESET_ID}.md"
          
          # Create changeset for @mastra/core with patch bump
          cat > "${CHANGESET_FILE}" << 'EOF'
          ---
          '@mastra/core': patch
          ---

          Update provider registry with latest models and providers
          EOF
          
          echo "Created changeset: ${CHANGESET_FILE}"

      - name: Commit and push changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add packages/core/src/llm/model/provider-registry.json
          git add packages/core/src/llm/model/provider-types.generated.d.ts
          git add .changeset/*.md
          git commit -m "chore: regenerate provider registry [skip ci]"
          git push

      - name: Log summary
        if: steps.git-check.outputs.changed == 'true'
        run: echo "✅ Provider registry updated with changeset and committed to main"

      - name: Log no changes
        if: steps.git-check.outputs.changed != 'true'
        run: echo "ℹ️ No changes detected in provider registry"
