name: Combined store Tests (vector+storage)

on:
  pull_request:
    branches: [main]
    paths:
      - "stores/**"
      - "stores/*/package.json"
      - ".github/workflows/test-combined-stores.yml"

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.7.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build core
        run: pnpm build:core

      - name: Build combined storage packages
        run: pnpm build:combined-stores

      - name: Run combined storage tests
        run: pnpm test:combined-stores
