name: Core Package Tests

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/core/**'
      - '.github/workflows/test-core.yml'

jobs:
  test-core:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-environment.yml

      - name: Run Core tests
        run: pnpm test:core
        env:
          NODE_OPTIONS: "--max_old_space_size=8096"
