name: Engine Tests

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/engine/**'
      - '.github/workflows/test-engine.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mastra
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.7.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build core
        run: pnpm build:core

      - name: Build engine
        run: pnpm build:engine && pnpm copy:drizzle

      - name: Setup database
        run: pnpm db:setup
        env:
          DB_URL: 'postgresql://postgres:postgres@localhost:5432/mastra'

      - name: Run Engine tests
        run: pnpm test:engine
        env:
          NODE_OPTIONS: '--max_old_space_size=8096'
          DB_URL: 'postgresql://postgres:postgres@localhost:5432/mastra'
