name: Schema Tests

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches: [main, 0.x]
    paths:
      - 'packages/schema-compat/**'
      - '.github/workflows/test-schema.yml'

jobs:
  test:
    # Only run on the main repository, not on forks
    if: ${{ github.repository == 'mastra-ai/mastra' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Setup pnpm and Node.js
        uses: ./.github/actions/setup-pnpm-node

      - name: Build @mastra/schema-compat
        run: pnpm turbo --filter="./packages/schema-compat" build

      - name: Run Schema tests
        run: pnpm run test:schema-compat
