name: Core Package Tests

on:
  pull_request:
    branches: [main]
    paths:
      - 'packages/core/**'
      - '.github/workflows/test-core.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.7.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build:cli

      - name: Run Core tests
        run: pnpm test:core
        env:
          NODE_OPTIONS: "--max_old_space_size=8096"
