name: Memory Tests

on:
  pull_request:
    branches: [main]
    paths:
      - "packages/memory/**"
      - "packages/memory/*/package.json"
      - "storage/**"
      - "storage/*/package.json"
      - ".github/workflows/test-memory.yml"

jobs:
  test:
    # Only run on the main repository, not on forks
    if: ${{ github.repository == 'mastra-ai/mastra' }}
    runs-on: ubuntu-latest
    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mastra
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.7.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build core
        run: pnpm build:core

      - name: Build storage packages
        run: pnpm --filter "@mastra/store-*" build

      - name: Build vector packages
        run: pnpm --filter "@mastra/vector-*" build

      - name: Build vector+store packages
        run: pnpm build:combined-stores

      - name: Build memory
        run: pnpm build:memory

      - name: Run Memory tests
        run: pnpm test:memory
        env:
          NODE_OPTIONS: "--max_old_space_size=8096"
          DB_URL: "postgresql://postgres:postgres@localhost:5432/mastra"
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          KV_REST_API_URL: ${{ secrets.KV_REST_API_URL }}
          KV_REST_API_TOKEN: ${{ secrets.KV_REST_API_TOKEN }}
